"use strict";

  function syncDeviceDefault(){return /iPad|iPhone|Macintosh.*Mobile/i.test(navigator.userAgent)?'iPad':'PC';}
  function syncDateStamp(){const d=new Date();return`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}_${String(d.getHours()).padStart(2,'0')}${String(d.getMinutes()).padStart(2,'0')}${String(d.getSeconds()).padStart(2,'0')}`;}
  function safeFilePart(value){return String(value||'').replace(/[\\/:*?"<>|\s]+/g,'_');}
  const MAX_IMPORT_BYTES=25*1024*1024;
  async function readImportText(file,label='ファイル'){
    if(!file)throw new Error(`${label}を選択してください`);
    if(Number(file.size)>MAX_IMPORT_BYTES)throw new Error(`${label}が大きすぎます。25MB以下のファイルを選んでください`);
    return file.text();
  }
  function validateEncryptedEnvelope(envelope){
    if(!envelope||typeof envelope!=='object'||Array.isArray(envelope))throw new Error('暗号化ファイルの形式が正しくありません');
    if(envelope.format!=='class-support-encrypted'||![1,2].includes(Number(envelope.version)))throw new Error('対応していない暗号化ファイルです');
    if(!envelope.crypto||typeof envelope.crypto!=='object'||typeof envelope.ciphertext!=='string'||!envelope.ciphertext)throw new Error('暗号化データが不足しています');
    if(envelope.ciphertext.length>MAX_IMPORT_BYTES*2)throw new Error('暗号化データが大きすぎます');
    return envelope;
  }
  function validateSyncPayload(payload){
    if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('復号したデータの形式が正しくありません');
    if(payload.format!=='class-support-sync-payload'||Number(payload.schemaVersion)!==1)throw new Error('このバージョンでは読み込めないデータ形式です');
    if(typeof payload.yearId!=='string'||!payload.yearId||typeof payload.yearLabel!=='string'||!payload.yearLabel)throw new Error('年度情報が不足しています');
    if(!payload.data||typeof payload.data!=='object'||Array.isArray(payload.data))throw new Error('保存データの本体がありません');
    const stores=['years','classes','students','enrollments','records','trash','meta'];let total=0;
    for(const store of stores){const items=payload.data[store];if(!Array.isArray(items))throw new Error(`${store}のデータ形式が正しくありません`);total+=items.length;if(total>200000)throw new Error('保存件数が多すぎるため読み込めません');const key=store==='meta'?'key':'id',seen=new Set();for(const item of items){if(!item||typeof item!=='object'||Array.isArray(item)||typeof item[key]!=='string'||!item[key])throw new Error(`${store}に識別情報のないデータがあります`);if(seen.has(item[key]))throw new Error(`${store}に同じ識別情報が重複しています`);seen.add(item[key]);for(const unsafe of ['__proto__','prototype','constructor'])if(Object.prototype.hasOwnProperty.call(item,unsafe))throw new Error(`${store}に安全でない項目があります`);}}
    const yearIds=new Set(payload.data.years.map(item=>item.id)),classIds=new Set(payload.data.classes.map(item=>item.id)),studentIds=new Set(payload.data.students.map(item=>item.id));
    if(!yearIds.has(payload.yearId))throw new Error('対象年度と年度データが一致しません');
    for(const item of payload.data.classes)if(!yearIds.has(item.yearId))throw new Error('所属年度が不明なクラスがあります');
    for(const item of payload.data.enrollments){if(!classIds.has(item.classId))throw new Error('所属クラスが不明な在籍情報があります');if(!studentIds.has(item.studentId))throw new Error('児童が不明な在籍情報があります');}
    for(const item of payload.data.records){if(!classIds.has(item.classId))throw new Error('所属クラスが不明な記録があります');if(item.studentId&&!studentIds.has(item.studentId))throw new Error('児童が不明な記録があります');}
    return payload;
  }
  async function recordSyncHistory(kind,details={}){const labels={export:'同期ファイル作成',import:'同期ファイル取込',backup:'バックアップ保存',archive:'年度保管'};const history=await ClassDB.getMeta('syncHistory',[]);const entry={id:ClassDB.uid('syncHistory'),at:ClassDB.now(),kind,kindLabel:labels[kind]||kind,device:details.device||await ClassDB.getMeta('syncDeviceName',syncDeviceDefault()),yearLabel:state.year?.label||'',add:details.add||0,update:details.update||0,delete:details.delete||0};await ClassDB.setMeta('syncHistory',[entry,...history].slice(0,20));return entry;}
  function syncHistoryHtml(history){if(!history?.length)return'<p class="muted">同期・バックアップの履歴はまだありません。</p>';return`<div class="sync-history-list">${history.slice(0,8).map(item=>`<div class="sync-history-row"><span class="sync-history-icon">${item.kind==='import'?'↓':item.kind==='backup'||item.kind==='archive'?'▣':'↑'}</span><div><strong>${esc(item.kindLabel||item.kind)}</strong><div class="row-meta">${esc(new Date(item.at).toLocaleString('ja-JP'))}・${esc(item.device||'端末名なし')}</div></div><span class="sync-history-count">${item.add||item.update||item.delete?`+${item.add||0} / 更新${item.update||0} / 削除${item.delete||0}`:'保存'}</span></div>`).join('')}</div>`;}
  function syncGuideHtml(){return`<ol class="sync-steps"><li><b>1</b><span><strong>移す元の端末でファイルを作る</strong><small>iPadで日常記録をした後など、記録を送る端末で「ファイルを作る」を押します。</small></span></li><li><b>2</b><span><strong>Teamsの自分用領域などへ置く</strong><small>作ったJSONファイルを、移動先の端末で開ける場所へ置きます。</small></span></li><li><b>3</b><span><strong>移動先の端末で取り込む</strong><small>PCで印刷や所見作成をする前などに取り込み、内容を確認して統合します。</small></span></li></ol><details class="sync-practice"><summary>本番前に、個人情報のないファイルで練習する</summary><p class="muted small">「練習用ファイル」をTeams経由で移動先の端末へ移し、そこで選んでください。実際の名簿や記録には一切触れません。</p><div class="button-row"><button type="button" class="button" id="sync-practice-export">練習用ファイルを作る</button><label class="button">移した練習用ファイルを選ぶ<input type="file" id="sync-practice-import" accept=".json,.json.txt,application/json,text/plain" hidden></label></div></details>`;}
  function createSyncPracticeFile(){const sample={format:'class-support-sync-practice',version:1,createdAt:ClassDB.now(),message:'このファイルには実際の児童情報や記録は入っていません。'};downloadText(`同期練習用_${syncDateStamp()}.json`,JSON.stringify(sample,null,2));showToast('練習用ファイルを保存しました');}
  async function inspectSyncPracticeFile(file){if(!file)return;try{const sample=JSON.parse(await readImportText(file,'練習用ファイル'));if(sample?.format!=='class-support-sync-practice')throw new Error('練習用ファイルではありません');openDialog('<h2>練習成功</h2><p>この端末でファイルを受け取れました。本番では、この下にある「別の端末で作ったファイルを取り込む」を使います。</p><p class="notice">練習では名簿や記録を変更していません。</p><div class="dialog-actions"><button type="button" class="button primary" id="sync-practice-close">OK</button></div>');document.getElementById('sync-practice-close').addEventListener('click',closeDialog);}catch(problem){openDialog(`<h2>練習用ファイルを確認できません</h2><p>${esc(problem.message||'ファイルを確認してください')}</p><div class="dialog-actions"><button type="button" class="button primary" id="sync-practice-close">OK</button></div>`);document.getElementById('sync-practice-close').addEventListener('click',closeDialog);}}
  async function deriveEncryptionKey(secret,salt,iterations=250000){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
  async function protectText(value,secret){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),iterations=250000,key=await deriveEncryptionKey(secret,salt,iterations),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(value));return{iterations,salt:bytesToBase64(salt),iv:bytesToBase64(iv),ciphertext:bytesToBase64(new Uint8Array(encrypted))};}
  async function unprotectText(bundle,secret){const key=await deriveEncryptionKey(secret,base64ToBytes(bundle.salt),bundle.iterations),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(bundle.iv)},key,base64ToBytes(bundle.ciphertext));return new TextDecoder().decode(plain);}
  async function wrapDataKey(rawKey,secret){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),iterations=250000,key=await deriveEncryptionKey(secret,salt,iterations),wrapped=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,rawKey);return{iterations,salt:bytesToBase64(salt),iv:bytesToBase64(iv),wrappedKey:bytesToBase64(new Uint8Array(wrapped))};}
  async function unwrapDataKey(bundle,secret){const key=await deriveEncryptionKey(secret,base64ToBytes(bundle.salt),bundle.iterations);return crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(bundle.iv)},key,base64ToBytes(bundle.wrappedKey));}
  async function recoverySecretForSession(){if(!state.year.recoverySecretProtected||!state.sessionSecret)return null;try{return await unprotectText(state.year.recoverySecretProtected,state.sessionSecret);}catch{return null;}}
  async function encryptPayload(payload,kind,includeRecovery=true){const rawKey=crypto.getRandomValues(new Uint8Array(32)),dataKey=await crypto.subtle.importKey('raw',rawKey,'AES-GCM',false,['encrypt','decrypt']),payloadIv=crypto.getRandomValues(new Uint8Array(12)),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv:payloadIv},dataKey,new TextEncoder().encode(JSON.stringify(payload))),recoverySecret=includeRecovery?await recoverySecretForSession():null;const wraps={password:await wrapDataKey(rawKey,state.sessionSecret)};if(recoverySecret)wraps.recovery=await wrapDataKey(rawKey,recoverySecret);return{format:'class-support-encrypted',version:2,kind,yearLabel:state.year.label,passwordHint:state.year.passwordHint||'',createdAt:ClassDB.now(),device:payload.device,crypto:{algorithm:'AES-GCM',kdf:'PBKDF2-SHA-256',payloadIv:bytesToBase64(payloadIv),wraps},ciphertext:bytesToBase64(new Uint8Array(encrypted))};}
  async function decryptEnvelope(envelope,credential=state.sessionSecret,method='password'){validateEncryptedEnvelope(envelope);try{if(envelope.version===1){if(method==='recovery')throw new Error('この旧形式ファイルは年度パスワードで開いてください');const key=await deriveEncryptionKey(credential,base64ToBytes(envelope.crypto.salt),envelope.crypto.iterations),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(envelope.crypto.iv)},key,base64ToBytes(envelope.ciphertext));return JSON.parse(new TextDecoder().decode(plain));}const wrap=envelope.crypto.wraps?.[method];if(!wrap)throw new Error(method==='recovery'?'このバックアップには復旧コード情報がありません':'年度パスワード用の情報がありません');const rawKey=await unwrapDataKey(wrap,credential),dataKey=await crypto.subtle.importKey('raw',rawKey,'AES-GCM',false,['decrypt']),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:base64ToBytes(envelope.crypto.payloadIv)},dataKey,base64ToBytes(envelope.ciphertext));return JSON.parse(new TextDecoder().decode(plain));}catch(error){if(error.message?.includes('旧形式')||error.message?.includes('情報がありません'))throw error;throw new Error(method==='recovery'?'復旧コードが異なるか、ファイルが破損しています':'パスワードが異なるか、ファイルが破損しています');}}

  async function collectYearPayload(){const classItems=await ClassDB.getAllByIndex('classes','yearId',state.year.id),classIds=new Set(classItems.map(item=>item.id));const allEnrollments=await ClassDB.getAll('enrollments'),enrollments=allEnrollments.filter(item=>classIds.has(item.classId));const studentIds=new Set(enrollments.map(item=>item.studentId));const students=(await ClassDB.getAll('students')).filter(item=>studentIds.has(item.id));const records=(await ClassDB.getAll('records')).filter(item=>classIds.has(item.classId));const trash=(await ClassDB.getAll('trash')).filter(item=>classIds.has(item.record?.classId));const localMeta=new Set(['lastMode','selectedClassId','activeYearId','preSyncSnapshots']);const meta=(await ClassDB.getAll('meta')).filter(item=>!localMeta.has(item.key));const device=await ClassDB.getMeta('syncDeviceName',syncDeviceDefault());return{format:'class-support-sync-payload',schemaVersion:1,yearId:state.year.id,yearLabel:state.year.label,generatedAt:ClassDB.now(),device,data:{years:[state.year],classes:classItems,students,enrollments,records,trash,meta}};}
  async function createEncryptedFile(kind,download=true){if(!await requestAnnualPassword())return null;if(['backup','archive'].includes(kind)&&!state.year.recoverySecretProtected){const ready=await prepareBackupExport();if(!ready)return null;}const payload=await collectYearPayload(),envelope=await encryptPayload(payload,kind);if(download){const prefix=kind==='backup'?'暗号化バックアップ':kind==='archive'?'年度保管':'同期';downloadText(`${prefix}_${safeFilePart(state.year.label)}_${syncDateStamp()}_${safeFilePart(payload.device)}.json`,JSON.stringify(envelope));if(kind==='backup'){state.lastBackupAt=ClassDB.now();state.backupDismissedUntil=null;await ClassDB.setMeta('lastBackupAt',state.lastBackupAt);await ClassDB.setMeta('backupDismissedUntil',null);}if(kind==='sync')await recordSyncHistory('export',{device:payload.device});if(kind==='backup')await recordSyncHistory('backup',{device:payload.device});if(kind==='archive')await recordSyncHistory('archive',{device:payload.device});}return envelope;}

  async function savePreSyncSnapshot(){
    const payload=await collectYearPayload(),envelope=await encryptPayload(payload,'pre-sync',false);
    const cutoff=Date.now()-30*86400000,existing=await ClassDB.getMeta('preSyncSnapshots',[]);
    const snapshots=[{id:ClassDB.uid('preSync'),createdAt:ClassDB.now(),yearId:payload.yearId,yearLabel:payload.yearLabel,envelope},...existing.filter(item=>Date.parse(item.createdAt)>=cutoff)].slice(0,3);
    await ClassDB.setMeta('preSyncSnapshots',snapshots);
    return snapshots[0];
  }

  async function restorePreSyncSnapshot(snapshotId,inSettings){
    if(!await requestAnnualPassword())return;
    try{
      const snapshots=await ClassDB.getMeta('preSyncSnapshots',[]),snapshot=snapshots.find(item=>item.id===snapshotId);
      if(!snapshot)throw new Error('同期前の保存が見つかりません');
      const payload=validateSyncPayload(await decryptEnvelope(snapshot.envelope));
      if(payload.yearId!==state.year.id)throw new Error('現在とは異なる年度の保存です');
      const classes=payload.data.classes.filter(item=>item.yearId===payload.yearId).sort((a,b)=>(b.isOwn-a.isOwn)||(a.order-b.order));
      if(!classes.length)throw new Error('戻せるクラスがありません');
      const selectedClassId=classes.some(item=>item.id===state.selectedClassId)?state.selectedClassId:classes[0].id,timestamp=ClassDB.now(),deviceId=ClassDB.deviceId();
      const meta=payload.data.meta.filter(item=>!['activeYearId','selectedClassId','lastMode','preSyncSnapshots'].includes(item.key));
      meta.push({key:'activeYearId',value:payload.yearId,updatedAt:timestamp,deviceId},{key:'selectedClassId',value:selectedClassId,updatedAt:timestamp,deviceId},{key:'preSyncSnapshots',value:snapshots,updatedAt:timestamp,deviceId});
      const replacement={...payload.data,meta};
      openDialog(`<h2>同期前の状態へ戻しますか</h2><p>${esc(new Date(snapshot.createdAt).toLocaleString('ja-JP'))}時点の、クラス ${classes.length}件・児童 ${payload.data.students.length}人・記録 ${payload.data.records.length}件へ戻します。</p><p class="notice">この操作では、同期後に追加・変更された内容が同期前の状態へ戻ります。</p><div class="dialog-actions"><button type="button" class="button" id="pre-sync-cancel">キャンセル</button><button type="button" class="button primary" id="pre-sync-confirm">同期前へ戻す</button></div>`);
      document.getElementById('pre-sync-cancel').addEventListener('click',closeDialog);
      document.getElementById('pre-sync-confirm').addEventListener('click',event=>runOnce(event.currentTarget,async()=>{try{await ClassDB.replaceAllRaw(replacement);state.year=payload.data.years.find(item=>item.id===payload.yearId);state.classes=classes;state.selectedClassId=selectedClassId;closeDialog();showToast('同期前の状態へ戻しました');renderDataExchange(inSettings);}catch(problem){openDialog(`<h2>元に戻せませんでした</h2><p>${esc(problem.message||'保存処理を完了できませんでした')}</p><div class="dialog-actions"><button type="button" class="button primary" id="pre-sync-error-close">OK</button></div>`);document.getElementById('pre-sync-error-close').addEventListener('click',closeDialog);}}));
    }catch(problem){openDialog(`<h2>同期前の保存を開けませんでした</h2><p>${esc(problem.message||'保存内容を確認できませんでした')}</p><div class="dialog-actions"><button type="button" class="button primary" id="pre-sync-error-close">OK</button></div>`);document.getElementById('pre-sync-error-close').addEventListener('click',closeDialog);}
  }

  async function restoreBackupFile(file){
    if(!file||!await requestAnnualPassword())return;
    try{
      const envelope=validateEncryptedEnvelope(JSON.parse(await readImportText(file,'暗号化バックアップ'))),payload=validateSyncPayload(await decryptEnvelope(envelope));
      if(!['backup','archive'].includes(envelope.kind))throw new Error('故障時の復旧には、バックアップまたは年度保管ファイルを選んでください');
      const year=payload.data.years.find(item=>item.id===payload.yearId),classes=payload.data.classes.filter(item=>item.yearId===payload.yearId).sort((a,b)=>(b.isOwn-a.isOwn)||(a.order-b.order));
      if(!year||!classes.length)throw new Error('復旧できる年度・クラスがありません');
      const selectedClassId=classes[0].id,timestamp=ClassDB.now(),deviceId=ClassDB.deviceId(),meta=payload.data.meta.filter(item=>!['activeYearId','selectedClassId','lastMode','preSyncSnapshots'].includes(item.key));
      meta.push({key:'activeYearId',value:year.id,updatedAt:timestamp,deviceId},{key:'selectedClassId',value:selectedClassId,updatedAt:timestamp,deviceId});
      const replacement={...payload.data,meta};
      openDialog(`<h2>${esc(payload.yearLabel)}のバックアップを戻しますか</h2><p>クラス ${classes.length}件、児童 ${payload.data.students.length}人、記録 ${payload.data.records.length}件を確認しました。</p><p class="notice"><strong>この端末に現在ある新形式データを、バックアップの内容へ置き換えます。</strong><br>iPadとPCの記録を追加統合する場合は、上の「別の端末で作ったファイルを取り込む」を使ってください。</p><div class="dialog-actions"><button type="button" class="button" id="backup-restore-cancel">キャンセル</button><button type="button" class="button primary" id="backup-restore-confirm">確認して復旧</button></div>`);
      document.getElementById('backup-restore-cancel').addEventListener('click',closeDialog);
      document.getElementById('backup-restore-confirm').addEventListener('click',event=>runOnce(event.currentTarget,async()=>{try{await ClassDB.replaceAllRaw(replacement);state.year=year;state.classes=classes;state.selectedClassId=selectedClassId;closeDialog();showToast('バックアップの内容へ復旧しました');renderHome();}catch(problem){openDialog(`<h2>復旧を完了できませんでした</h2><p>${esc(problem.message||'端末への保存に失敗しました')}</p><p class="muted">元のデータは変更されていません。</p><div class="dialog-actions"><button type="button" class="button primary" id="backup-restore-error-close">OK</button></div>`);document.getElementById('backup-restore-error-close').addEventListener('click',closeDialog);}}));
    }catch(problem){openDialog(`<h2>バックアップを開けませんでした</h2><p>${esc(problem.message||'ファイルを確認してください')}</p><div class="dialog-actions"><button type="button" class="button primary" id="backup-restore-error-close">OK</button></div>`);document.getElementById('backup-restore-error-close').addEventListener('click',closeDialog);}
  }

  async function prepareBackupExport(){if(state.year.recoverySecretProtected)return true;return new Promise(resolve=>{let settled=false;const finish=value=>{if(settled)return;settled=true;dialog.removeEventListener('cancel',onDialogCancel);resolve(value);},onDialogCancel=()=>finish(false);openDialog(`<h2>復旧コードを確認</h2><p class="muted">この端末の設定は旧形式です。今回だけ復旧コードを入力すると、今後のバックアップを復旧コードでも開けるようになります。</p><form id="backup-recovery-form"><div class="field"><label for="backup-recovery-code">${esc(state.year.label)}の復旧コード</label><input class="input" id="backup-recovery-code" autocomplete="off" required></div><p class="error" id="backup-recovery-error"></p><div class="dialog-actions"><button type="button" class="button" id="backup-recovery-cancel">キャンセル</button><button type="submit" class="button primary">確認して保存</button></div></form>`);dialog.addEventListener('cancel',onDialogCancel,{once:true});document.getElementById('backup-recovery-cancel').addEventListener('click',()=>{closeDialog();finish(false);});document.getElementById('backup-recovery-form').addEventListener('submit',async event=>{event.preventDefault();const code=document.getElementById('backup-recovery-code').value.trim().toUpperCase();if(!await verifySecret(code,state.year.recoveryAuth)){document.getElementById('backup-recovery-error').textContent='復旧コードが一致しません。';return;}state.year=await ClassDB.put('years',{...state.year,recoverySecretProtected:await protectText(code,state.sessionSecret)});closeDialog();finish(true);});});}

  function importHash(value){let hash=2166136261;for(const char of String(value||'')){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(36);}
  function parseExternalTable(text){const lines=String(text||'').split(/\r?\n/).filter(line=>line.trim());return lines.map(line=>{const cells=[];let cell='',quoted=false;for(let i=0;i<line.length;i++){const char=line[i],next=line[i+1];if(char==='"'&&quoted&&next==='"'){cell+='"';i++;continue;}if(char==='"'){quoted=!quoted;continue;}if(!quoted&&(char===','||char==='\t')){cells.push(cell.trim());cell='';continue;}cell+=char;}cells.push(cell.trim());return cells;});}
  function importHeader(value){return String(value||'').normalize('NFKC').replace(/[\s　_・]/g,'').toLowerCase();}
  function externalImportRows(rows){if(!rows.length)return[];const aliases={date:['日付','提出日','提出予定日','実施日','date'],title:['宿題名','提出物名','課題名','タイトル','宿題','title'],name:['氏名','名前','児童名','生徒名','name'],number:['出席番号','番号','no','no.','number'],status:['状態','提出状況','結果','status'],subject:['教科','subject'],unit:['単元','unit']};const header=rows[0].map(importHeader),columns={};for(const [key,names] of Object.entries(aliases)){const found=header.findIndex(value=>names.includes(value));if(found>=0)columns[key]=found;}const hasHeader=Object.keys(columns).length>=2&&('name'in columns||'number'in columns),data=hasHeader?rows.slice(1):rows;return data.map(cells=>Object.fromEntries(Object.entries(columns).map(([key,index])=>[key,String(cells[index]??'').trim()]))).filter(row=>Object.values(row).some(Boolean));}
  function inferExternalImportType(rows,fileName=''){
    const text=[fileName,...rows.flatMap(row=>[row.title,row.subject,row.unit])].join(' ').normalize('NFKC').toLowerCase(),scores={daily:0,weekly:0,occasional:0},reasons={daily:'日付・児童名・提出状況の並び',weekly:'日付・児童名・提出状況の並び',occasional:'日付・児童名・提出状況の並び'};
    if(/毎日|daily|音読|漢字|計算/.test(text)){scores.daily+=4;reasons.daily='毎日の宿題を示す言葉';}
    if(/週宿題|週ごと|weekly|自主学習|自学|週末/.test(text)){scores.weekly+=5;reasons.weekly='週ごとの宿題を示す言葉';}
    if(/提出物|書類|同意書|申込|参加票|調査票|集金|家庭から/.test(text)){scores.occasional+=5;reasons.occasional='家庭から集める提出物を示す言葉';}
    if(rows.some(row=>row.title)&&!scores.daily&&!scores.weekly&&!scores.occasional){scores.weekly=2;scores.occasional=2;reasons.weekly=reasons.occasional='課題名と提出状況';}
    const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]),type=ranked[0][1]>0?ranked[0][0]:'weekly',labels={daily:'毎日の宿題',weekly:'週宿題',occasional:'提出物'},confident=ranked[0][1]>ranked[1][1];
    return{type,label:labels[type],reason:reasons[type],confident};
  }
  function importedStatus(value,type){const text=String(value||'').trim().toLowerCase();if(['提出','提出済み','済','submitted','提出済'].includes(text))return'submitted';if(['忘れた','忘れ','forgotten','未提出（忘れ）'].includes(text))return type==='daily'?'forgotten':'unsubmitted';if(['欠席','absent'].includes(text))return'absent';return type==='daily'?'unconfirmed':'unsubmitted';}
  async function matchImportedStudent(classId,row,date){const roster=await rosterForClass(classId,false,date||today()),number=Number(String(row.number||'').replace(/[^0-9]/g,''))||null,name=normalizeStudentName(row.name);const byNumber=number?roster.filter(item=>Number(item.enrollment.number)===number):[],byName=name?roster.filter(item=>normalizeStudentName(item.student.name)===name):[],candidates=[...new Map([...byNumber,...byName].map(item=>[item.student.id,item])).values()];if(byNumber.length===1&&(!byName.length||byName[0].student.id===byNumber[0].student.id))return{row,match:byNumber[0],candidates,reason:'出席番号'};if(byName.length===1)return{row,match:byName[0],candidates,reason:'氏名'};return{row,match:null,candidates,reason:candidates.length?'候補が複数':'一致なし'};}
  async function applyExternalImport(type,classId,rows,sourceKey,matches){matches=matches||[];if(!matches.length)for(const row of rows)matches.push(await matchImportedStudent(classId,row,row.date));const unresolved=matches.filter(item=>!item.match);if(unresolved.length){openDialog(`<h2>名寄せを確認してください</h2><p>${unresolved.length}行の児童を特定できませんでした。候補を選ぶか、氏名・出席番号を修正して再度取り込んでください。</p><div class="list section">${unresolved.slice(0,12).map(item=>`<div class="list-row"><span>${esc(item.row.name||'氏名なし')}</span><span class="row-meta">${esc(item.row.number||'番号なし')}・${esc(item.reason)}</span></div>`).join('')}</div><div class="dialog-actions"><button type="button" class="button primary" id="external-import-close">戻る</button></div>`);document.getElementById('external-import-close').addEventListener('click',closeDialog);return;}
    const puts={records:[]},occurrenceCache=new Map(),itemCache=new Map();for(const item of matches){const row=item.row,student=item.match.student,date=row.date||today(),title=row.title||`${type==='daily'?'毎日の宿題':type==='weekly'?'週宿題':'提出物'}`;if(type==='daily'){const id=`dailyHomework_${classId}_${date}_${student.id}`,current=await ClassDB.get('records',id);puts.records.push({...current,id,type:'dailyHomework',classId,studentId:student.id,date,status:importedStatus(row.status,'daily'),sourceImportKey:sourceKey});}else if(type==='weekly'){const key=`${date}|${title}`;let occurrence=occurrenceCache.get(key);if(!occurrence){occurrence=(await ClassDB.getAllByIndex('records','classId',classId)).find(record=>record.type==='weeklyOccurrence'&&record.dueDate===date&&record.title===title);if(!occurrence)occurrence={id:ClassDB.uid('weeklyOccurrence'),type:'weeklyOccurrence',classId,studentId:null,date,dueDate:date,weekStart:mondayOf(date),title,recurring:false,sourceImportKey:sourceKey};occurrenceCache.set(key,occurrence);puts.records.push(occurrence);}const id=`weekly_${occurrence.id}_${student.id}`,current=await ClassDB.get('records',id);puts.records.push({...current,id,type:'weeklySubmission',classId,studentId:student.id,date,dueDate:date,title,occurrenceId:occurrence.id,status:importedStatus(row.status,'weekly'),sourceImportKey:sourceKey});}else{const key=`${date}|${title}`;let recordItem=itemCache.get(key);if(!recordItem){recordItem=(await ClassDB.getAllByIndex('records','classId',classId)).find(record=>record.type==='occasionalItem'&&record.dueDate===date&&record.title===title);if(!recordItem)recordItem={id:ClassDB.uid('occasionalItem'),type:'occasionalItem',classId,studentId:null,date,dueDate:date,title,continueDisplay:true,archived:false,sourceImportKey:sourceKey};itemCache.set(key,recordItem);puts.records.push(recordItem);}const id=`occasional_${recordItem.id}_${student.id}`,current=await ClassDB.get('records',id);puts.records.push({...current,id,type:'occasionalSubmission',classId,studentId:student.id,date,dueDate:date,title,itemId:recordItem.id,status:importedStatus(row.status,'occasional'),sourceImportKey:sourceKey});}}
    await ClassDB.putMany('records',puts.records);const imports=await ClassDB.getMeta('externalImportHistory',[]);await ClassDB.setMeta('externalImportHistory',[{id:ClassDB.uid('externalImport'),at:ClassDB.now(),sourceKey,type,rows:rows.length},...imports].slice(0,30));closeDialog();showToast(`${rows.length}行を取り込みました`);renderDataExchange(true);
  }
  function openExternalImport(initialFile=null){
    openDialog(`<h2>ファイルの内容を判別して取り込む</h2><p class="muted">CSV・Excel・テキスト、または表の貼り付けに対応します。内容から登録先を推測し、実際に登録する前に確認します。</p><form id="external-import-form"><div class="field"><label for="external-import-type">登録先</label><select class="select" id="external-import-type"><option value="auto">内容から自動で推測</option><option value="daily">毎日の宿題</option><option value="weekly">週宿題</option><option value="occasional">提出物</option></select></div>${initialFile?`<p class="notice small">選択中：${esc(initialFile.name)}</p>`:''}<div class="field"><label for="external-import-file">${initialFile?'別のファイルを選び直す':'CSV・Excel・テキストファイル'}</label><input class="input" id="external-import-file" type="file" accept=".csv,.txt,.xlsx,text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"></div><div class="field"><label for="external-import-paste">または表を貼り付け</label><textarea class="textarea" id="external-import-paste" placeholder="日付,出席番号,氏名,宿題名,状態"></textarea></div><p class="error" id="external-import-error"></p><div class="dialog-actions"><button type="button" class="button" id="external-import-cancel">キャンセル</button><button type="submit" class="button primary">判別して内容を確認</button></div></form>`);
    document.getElementById('external-import-cancel').addEventListener('click',closeDialog);
    document.getElementById('external-import-form').addEventListener('submit',async event=>{
      event.preventDefault();const chosen=document.getElementById('external-import-type').value,file=document.getElementById('external-import-file').files[0]||initialFile,paste=document.getElementById('external-import-paste').value,error=document.getElementById('external-import-error');
      try{
        let rows=paste?parseExternalTable(paste):[];if(file)rows=file.name.toLowerCase().endsWith('.xlsx')?await XlsxRosterReader.read(file):parseExternalTable(await readImportText(file,'取込ファイル'));
        const parsed=externalImportRows(rows);if(!parsed.length){error.textContent='氏名または出席番号を含む表を選んでください。';return;}
        const inferred=inferExternalImportType(parsed,file?.name||'貼り付けた表'),type=chosen==='auto'?inferred.type:chosen,labels={daily:'毎日の宿題',weekly:'週宿題',occasional:'提出物'},matches=[];for(const row of parsed)matches.push(await matchImportedStudent(selectedClass().id,row,row.date));const unresolved=matches.filter(item=>!item.match),unresolvable=unresolved.filter(item=>!item.candidates.length);
        openDialog(`<h2>「${esc(labels[type])}」に登録しますか？</h2><div class="import-detection ${inferred.confident?'good':'warn'}"><strong>${chosen==='auto'?`ファイル内容から「${esc(inferred.label)}」と推測しました`:`登録先として「${esc(labels[type])}」が選ばれています`}</strong><span>${esc(inferred.reason)}を手がかりに判別しています。違う場合は下で変更できます。</span></div><div class="field section"><label for="external-confirm-type">実際の登録先</label><select class="select" id="external-confirm-type"><option value="daily" ${type==='daily'?'selected':''}>毎日の宿題</option><option value="weekly" ${type==='weekly'?'selected':''}>週宿題</option><option value="occasional" ${type==='occasional'?'selected':''}>提出物</option></select></div><p>全${parsed.length}行・名寄せ成功 ${parsed.length-unresolved.length}行・要確認 ${unresolved.length}行</p><div class="list section">${matches.map((item,index)=>`<div class="list-row"><span>${esc(item.row.name||'氏名なし')}</span><span class="row-meta">${item.match?`→ ${esc(item.match.student.name)}（${esc(item.reason)}）`:item.candidates.length?`<select class="select" data-external-candidate="${index}"><option value="">候補を選択</option>${item.candidates.map(candidate=>`<option value="${candidate.student.id}">${esc(candidate.enrollment.number||'未設定')}　${esc(candidate.student.name)}</option>`).join('')}</select>`:'名簿に一致なし'}</span></div>`).join('')}</div><p class="muted small">候補がある行は児童を選択してください。名簿に一致しない行は登録できません。</p><div class="dialog-actions"><button type="button" class="button" id="external-preview-cancel">キャンセル</button><button type="button" class="button primary" id="external-preview-apply" ${unresolved.length?'disabled':''}>${esc(labels[type])}に登録</button></div>`);
        document.getElementById('external-preview-cancel').addEventListener('click',closeDialog);const applyButton=document.getElementById('external-preview-apply'),typeSelect=document.getElementById('external-confirm-type'),updateApply=()=>{const actualLabel=labels[typeSelect.value];applyButton.textContent=`${actualLabel}に登録`;applyButton.disabled=matches.some(item=>!item.match)||unresolvable.length>0;};typeSelect.addEventListener('change',updateApply);document.querySelectorAll('[data-external-candidate]').forEach(select=>select.addEventListener('change',()=>{const item=matches[Number(select.dataset.externalCandidate)],candidate=item.candidates.find(row=>row.student.id===select.value);item.match=candidate||null;item.reason=candidate?'手動選択':'候補未選択';updateApply();}));updateApply();applyButton.addEventListener('click',async()=>{const actualType=typeSelect.value,sourceKey=importHash(`${actualType}|${JSON.stringify(rows)}`),history=await ClassDB.getMeta('externalImportHistory',[]);if(history.some(item=>item.sourceKey===sourceKey)){openDialog(`<h2>取り込み済みです</h2><p>同じ内容は、すでに${esc(labels[actualType])}へ取り込まれています。</p><div class="dialog-actions"><button type="button" class="button primary" id="external-import-close">OK</button></div>`);document.getElementById('external-import-close').addEventListener('click',closeDialog);return;}applyExternalImport(actualType,selectedClass().id,parsed,sourceKey,matches);});
      }catch(problem){error.textContent=problem.message||'ファイルを読み取れませんでした';}
    });
  }

  async function restoreTrashRecord(trashId){const item=await ClassDB.get('trash',trashId);if(!item?.record)return 0;let items=[item],relatedRecords=[];const record=item.record,timestamp=ClassDB.now(),deviceId=ClassDB.deviceId(),puts={};
    if(record.type==='weeklyOccurrence'){const allTrash=await ClassDB.getAll('trash');items=allTrash.filter(row=>row.id===item.id||(row.record?.type==='weeklySubmission'&&row.record?.occurrenceId===record.id));if(record.recurring&&record.seriesId&&record.seriesActive!==false){relatedRecords=(await ClassDB.getAllByIndex('records','classId',record.classId)).filter(row=>row.type==='weeklyOccurrence'&&row.seriesId===record.seriesId).map(row=>({...row,seriesActive:true,updatedAt:timestamp,deviceId}));const skipped=await ClassDB.getMeta('weeklySkippedWeeks',[]),skipKey=`${record.classId}|${record.seriesId}|${mondayOf(record.dueDate)}`;puts.meta=[{key:'weeklySkippedWeeks',value:(Array.isArray(skipped)?skipped:[]).filter(key=>key!==skipKey),updatedAt:timestamp,deviceId}];}}
    puts.records=[...items.map(row=>{const restored={...row.record,updatedAt:timestamp,deviceId};delete restored.deletedAt;return restored;}),...relatedRecords];await ClassDB.applyBatch({puts,deletes:{trash:items.map(row=>row.id)}});return items.length;
  }

  async function renderDataExchange(inSettings=false){
    if(!teacherActive()){renderPupil();return;}
    state.route=inSettings?'teacher-settings':'teacher-data';state.activeTool=inSettings?'settings':'data';state.dataInSettings=inSettings;applyClassTheme(selectedClass());
    const device=await ClassDB.getMeta('syncDeviceName',syncDeviceDefault());
    const lastBackup=await ClassDB.getMeta('lastBackupAt',null);
    const syncHistory=await ClassDB.getMeta('syncHistory',[]);
    const preSyncSnapshots=(await ClassDB.getMeta('preSyncSnapshots',[])).filter(item=>Date.parse(item.createdAt)>=Date.now()-30*86400000).slice(0,3);
    const trash=(await ClassDB.getAll('trash')).filter(item=>item.record?.classId&&state.classes.some(classItem=>classItem.id===item.record.classId)).sort((a,b)=>String(b.deletedAt).localeCompare(String(a.deletedAt)));
    const term=currentTermRange();
    const body=`
      <section class="panel data-heading"><h1>データ管理</h1><p>普段使うのは次の2つです。ほかの操作は、必要なときだけ下の項目を開いてください。</p><nav class="data-task-grid primary-data-tasks" aria-label="普段使うデータ操作"><button type="button" data-data-section="data-sync"><strong>iPadとPCの記録をまとめる</strong><span>両方の端末を使ったあと</span></button><button type="button" data-data-section="data-backup"><strong>故障に備えて保存する</strong><span>月に1回</span></button></nav></section>
      <section class="panel credential-status" id="data-sync"><h2>iPadとPCの記録をまとめる</h2><div><span class="status-pill good">教師画面PIN：認証済み</span><span class="status-pill ${state.sessionSecret?'good':'neutral'}">データ保護パスワード：${state.sessionSecret?'確認済み':'未確認'}</span></div><p class="muted small">両方の端末で別々に付けた記録を一つにします。作成・取り込みには年度のデータ保護パスワードを使います。復旧コードは、パスワードを忘れた場合だけ使用します。</p>${syncGuideHtml()}<div class="form-grid section"><div class="field"><label for="sync-device-name">この端末の名前 <small>例：職員室PC・教室iPad</small></label><input class="input" id="sync-device-name" value="${esc(device)}"></div><div class="field" style="align-self:end"><button type="button" class="button primary" id="sync-export">移す元の端末でファイルを作る</button></div><div class="field full"><label for="sync-import">移動先の端末でファイルを取り込む</label><input class="input" id="sync-import" type="file" accept=".json,.json.txt,application/json,text/plain"></div></div></section>
      <details class="panel data-advanced"><summary>最近の同期・保存履歴を確認する</summary><div class="button-row section" style="justify-content:space-between"><p class="muted">この端末で行った最近の履歴です。</p><button type="button" class="button" id="sync-history-refresh">更新</button></div>${syncHistoryHtml(syncHistory)}</details>
      <details class="panel data-advanced"><summary>直前の同期前へ戻す（${preSyncSnapshots.length}件）</summary><div class="section"><p class="muted">同期の直前に自動保存した状態を、最大3回分・30日間保持します。同期結果に問題があった場合だけ使います。</p>${preSyncSnapshots.length?`<div class="list section">${preSyncSnapshots.map(item=>`<div class="list-row"><div><strong>${esc(item.yearLabel)}</strong><div class="row-meta">同期前 ${esc(new Date(item.createdAt).toLocaleString('ja-JP'))}</div></div><button type="button" class="button" data-pre-sync-restore="${item.id}">この状態へ戻す</button></div>`).join('')}</div>`:'<p class="empty-state">同期前の保存はまだありません。</p>'}</div></details>
      <section class="panel" id="data-backup"><h2>故障に備えて保存する</h2><p class="muted">端末が壊れた場合や年度末の保管に備え、すべてのデータを安全なファイルにします。最終保存：${lastBackup?esc(new Date(lastBackup).toLocaleString('ja-JP')):'まだありません'}</p><div class="button-row"><button type="button" class="button primary" id="backup-export">全データを安全なファイルに保存</button><label class="button">保存したデータを戻す<input id="backup-import" type="file" accept=".json,.json.txt,application/json,text/plain" hidden></label></div></section>
      <details class="panel data-advanced"><summary>前年度に保存したデータを確認する</summary><p class="muted section">アプリへ戻さず、保管した年度・クラス・人数・記録件数だけを確認します。</p><label class="button">保管ファイルを選ぶ<input id="archive-inspect" type="file" accept=".json,.json.txt,application/json,text/plain" hidden></label></details>
      <details class="panel data-advanced" id="data-export"><summary>Excelで確認する一覧を作る</summary><div class="section"><p class="muted">選んだ期間の提出状況やノート評価を、PCのExcelで開ける表として保存します。</p><div class="form-grid"><div class="field"><label for="csv-class">クラス</label><select class="select" id="csv-class">${state.classes.map(item=>`<option value="${item.id}" ${item.id===state.selectedClassId?'selected':''}>${esc(item.name)}</option>`).join('')}</select></div><div></div><div class="field"><label for="csv-start">開始日</label><input class="input" id="csv-start" type="date" value="${term.start}"></div><div class="field"><label for="csv-end">終了日</label><input class="input" id="csv-end" type="date" value="${term.end}"></div></div><p class="error" id="csv-error" role="alert"></p><div class="button-row section"><button type="button" class="button primary" id="submission-csv">提出状況の表を保存</button><button type="button" class="button primary" id="assessment-csv">ノート評価の表を保存</button></div></div></details>
      <details class="panel data-advanced"><summary>ほかのツールや以前のデータを取り込む</summary><div class="section"><p class="muted">ファイルの内容を確認して、旧クラスチェッカー、席替え、行動記録、毎日の宿題、週宿題、提出物のどれかを推測します。ファイルを選んだだけでは保存されません。必ず次に「内容を確認」の画面が出ます。</p><div class="button-row"><label class="button primary">ファイルを選んで内容を確認<input id="smart-import-files" type="file" accept=".json,.csv,.txt,.xlsx,application/json,text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" multiple hidden></label><button type="button" class="button" id="external-record-import">表を貼り付けて取り込む</button><button type="button" class="button" id="legacy-scan">この端末の旧ツールを確認</button></div><p class="muted small" id="smart-import-status" role="status">まだファイルは選ばれていません。</p></div></details>
      <details class="panel data-advanced" id="data-restore"><summary>削除した記録を戻す（ごみ箱 ${trash.length}件）</summary><div class="section"><p class="muted">削除した記録は30日間ここから戻せます。</p>${trash.length?`<div class="list section">${trash.slice(0,50).map(item=>`<div class="list-row"><div><strong>${esc(item.record?.title||({memo:'児童メモ',notebookAssessment:'ノート評価',certificate:'ミニ賞状'}[item.record?.type]||'記録'))}</strong><div class="row-meta">${esc(jpDate(item.record?.date))}・削除 ${esc(new Date(item.deletedAt).toLocaleString('ja-JP'))}</div></div><button type="button" class="button" data-trash-restore="${item.id}">復元</button></div>`).join('')}</div>`:'<p class="empty-state">ごみ箱は空です。</p>'}</div></details>
      <details class="panel data-advanced"><summary>アプリの表示が古いとき</summary><p class="muted section">現在の公開版：v${APP_VERSION}<br>アップデート日時：${APP_UPDATED_AT}<br>GitHub Pagesの表示が古いと感じた場合だけ、更新確認を実行してください。</p><button type="button" class="button" id="app-update-check">更新を確認して再読み込み</button></details>
      <details class="panel danger-zone data-advanced"><summary>クラスやデータを削除する</summary><p class="muted section">必要な保存ファイルを作ったことを確認してから使います。以前のツールのデータは削除しません。</p><div class="button-row"><button type="button" class="button danger" id="delete-class-records">現在のクラスの記録を削除</button><button type="button" class="button danger" id="delete-current-class">名簿を含めてクラスを削除</button><button type="button" class="button danger" id="delete-all-data">全データを削除（旧版データは残す）</button></div></details>`;
    if(inSettings&&document.getElementById('settings-content'))document.getElementById('settings-content').innerHTML=body;else{app.innerHTML=teacherToolShell('データ管理',body);wireToolHome();}
    document.getElementById('sync-device-name').addEventListener('change',async event=>{await ClassDB.setMeta('syncDeviceName',event.target.value.trim()||syncDeviceDefault());showToast('端末名を保存しました');});
    document.querySelectorAll('[data-data-section]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.dataSection)?.scrollIntoView({behavior:'smooth',block:'start'})));
    document.getElementById('sync-export').addEventListener('click',event=>runOnce(event.currentTarget,async()=>{await saveDeviceNameFromScreen();const saved=await createEncryptedFile('sync');if(saved)showToast('暗号化同期ファイルを保存しました');}));
    document.getElementById('backup-export').addEventListener('click',event=>runOnce(event.currentTarget,async()=>{await saveDeviceNameFromScreen();const saved=await createEncryptedFile('backup');if(saved)showToast('暗号化バックアップを保存しました');}));
    document.getElementById('sync-history-refresh').addEventListener('click',event=>runOnce(event.currentTarget,async()=>renderDataExchange(inSettings)));
    document.getElementById('sync-import').addEventListener('change',event=>readEncryptedImport(event.target.files[0]));
    document.getElementById('sync-practice-export').addEventListener('click',createSyncPracticeFile);
    document.getElementById('sync-practice-import').addEventListener('change',event=>inspectSyncPracticeFile(event.target.files[0]));
    document.getElementById('backup-import').addEventListener('change',event=>restoreBackupFile(event.target.files[0]));
    document.getElementById('archive-inspect').addEventListener('change',event=>inspectArchiveFile(event.target.files[0]));
    document.getElementById('submission-csv').addEventListener('click',event=>runOnce(event.currentTarget,()=>exportClassCsv('submission')));
    document.getElementById('assessment-csv').addEventListener('click',event=>runOnce(event.currentTarget,()=>exportClassCsv('assessment')));
    document.getElementById('legacy-scan').addEventListener('click',()=>openLegacyMigrationReview(LegacyMigration.fromStorage()));document.getElementById('external-record-import').addEventListener('click',()=>openExternalImport());
    document.getElementById('smart-import-files').addEventListener('change',async event=>{const files=[...event.target.files],status=document.getElementById('smart-import-status');event.target.value='';if(!files.length)return;if(status)status.textContent=`${files.length}個のファイルを読み取っています…`;await inspectSmartImportFiles(files);});
    document.querySelectorAll('[data-trash-restore]').forEach(button=>button.addEventListener('click',async()=>{const count=await restoreTrashRecord(button.dataset.trashRestore);showToast(count>1?`宿題と提出記録${count-1}件を復元しました`:'記録を復元しました');renderDataExchange(inSettings);}));
    document.querySelectorAll('[data-pre-sync-restore]').forEach(button=>button.addEventListener('click',()=>restorePreSyncSnapshot(button.dataset.preSyncRestore,inSettings)));
    document.getElementById('app-update-check').addEventListener('click',async()=>{const registration=await navigator.serviceWorker?.getRegistration();await registration?.update();if('caches'in window)for(const key of await caches.keys())if(key!==`class-support-shell-v${APP_VERSION}`)await caches.delete(key);location.reload();});
    document.getElementById('delete-current-class').addEventListener('click',confirmDeleteCurrentClass);
    document.getElementById('delete-class-records').addEventListener('click',confirmDeleteClassRecords);
    document.getElementById('delete-all-data').addEventListener('click',confirmDeleteAllData);
  }

  async function resetToWelcomePreservingLegacy(){
    await ClassDB.resetAll();
    localStorage.removeItem(PIN_ATTEMPT_KEY);
    clearTimeout(state.lockTimer);
    Object.assign(state,{year:null,classes:[],selectedClassId:null,teacherUntil:0,sessionSecret:null,pinFailures:0,pinLockedUntil:0,route:'setup',settingsTab:'year',classSettingsView:'list',rosterDraft:[],rosterLoadedForClassId:null,activeTool:null,toolDraft:{},pupilTool:'all',pupilDate:null,pupilWeeklyId:null,pupilOccasionalId:null,migrationSources:[],migrationPromptShown:false,verifiedLegacyCleanupKeys:[],setupDraft:null,rolloverArchiveVerified:null,rolloverDraft:null,rolloverContinue:false,lockTimer:null,dataInSettings:false,weeklyPromptShown:new Set(),feedback:null,iconMode:'standard',emojiIcons:{...DEFAULT_EMOJI_ICONS},rewardIcon:'✨',showMonthlyForgotten:true,pupilKanaMode:false,showExplanations:true,onboardingStep:0});
    renderSetup();
  }

  async function confirmDeleteAllData(){
    const counts={classes:(await ClassDB.getAll('classes')).length,students:(await ClassDB.getAll('students')).length,records:(await ClassDB.getAll('records')).length};
    openDialog(`<h2>このアプリの全データを削除しますか</h2><p>年度設定、教師用PIN、クラス ${counts.classes}件、児童 ${counts.students}人、記録 ${counts.records}件をこの端末から削除します。</p><p class="notice"><strong>旧版ツールのデータは削除しません。</strong><br>次回は「ようこそ」画面から始まり、旧データを移行するか選べます。</p><p class="error">この操作は元に戻せません。必要なら先に暗号化バックアップを保存してください。</p><label class="check-row"><input type="checkbox" id="delete-all-confirm-check"> 内容を確認し、全データを削除します</label><div class="dialog-actions"><button type="button" class="button" id="delete-all-cancel">キャンセル</button><button type="button" class="button danger" id="delete-all-confirm" disabled>全データを削除</button></div>`);
    const check=document.getElementById('delete-all-confirm-check'),button=document.getElementById('delete-all-confirm');
    check.addEventListener('change',()=>button.disabled=!check.checked);
    document.getElementById('delete-all-cancel').addEventListener('click',closeDialog);
    button.addEventListener('click',event=>runOnce(event.currentTarget,async()=>{closeDialog();await resetToWelcomePreservingLegacy();showToast('全データを削除しました');}));
  }

  async function confirmDeleteClassRecords(){const classItem=selectedClass();if(!classItem)return;const records=await ClassDB.getAllByIndex('records','classId',classItem.id);openDialog(`<h2>${esc(classItem.name)}の記録を削除しますか</h2><p>宿題・提出物・評価・メモなど ${records.length}件を30日間ごみ箱へ移します。名簿とクラス設定は残ります。</p><div class="dialog-actions"><button type="button" class="button" id="records-delete-cancel">キャンセル</button><button type="button" class="button danger" id="records-delete-confirm">${records.length}件を削除</button></div>`);document.getElementById('records-delete-cancel').addEventListener('click',closeDialog);document.getElementById('records-delete-confirm').addEventListener('click',async()=>{const timestamp=ClassDB.now(),deviceId=ClassDB.deviceId(),meta={key:'lastLegacyMigration',value:null,updatedAt:timestamp,deviceId};await ClassDB.applyBatch({puts:{trash:records.map(trashEntryFor),meta:[meta]},deletes:{records:records.map(record=>record.id)}});closeDialog();showToast(`${records.length}件をごみ箱へ移動しました`);renderDataExchange(true);});}

  async function confirmDeleteCurrentClass(){const classItem=selectedClass();if(!classItem)return;const roster=(await rosterForClass(classItem.id)).length,records=(await ClassDB.getAllByIndex('records','classId',classItem.id)).length;openDialog(`<h2>${esc(classItem.name)}を削除しますか</h2><p>名簿 ${roster}人、記録 ${records}件が対象です。旧ツールのデータは削除しません。</p><p class="error">この操作は元に戻せません。必要なら先に暗号化バックアップを保存してください。</p><div class="dialog-actions"><button type="button" class="button" id="class-delete-cancel">キャンセル</button><button type="button" class="button danger" id="class-delete-confirm">クラスを削除</button></div>`);document.getElementById('class-delete-cancel').addEventListener('click',closeDialog);document.getElementById('class-delete-confirm').addEventListener('click',async()=>{const enrollments=await ClassDB.getAllByIndex('enrollments','classId',classItem.id),classRecords=await ClassDB.getAllByIndex('records','classId',classItem.id),allEnrollments=await ClassDB.getAll('enrollments'),studentIds=new Set(enrollments.map(item=>item.studentId)),usedElsewhere=new Set(allEnrollments.filter(item=>item.classId!==classItem.id).map(item=>item.studentId));state.classes=state.classes.filter(item=>item.id!==classItem.id);state.selectedClassId=state.classes[0]?.id||null;const timestamp=ClassDB.now(),deviceId=ClassDB.deviceId(),meta=[{key:'selectedClassId',value:state.selectedClassId,updatedAt:timestamp,deviceId},{key:'lastLegacyMigration',value:null,updatedAt:timestamp,deviceId}];await ClassDB.applyBatch({puts:{meta},deletes:{records:classRecords.map(item=>item.id),enrollments:enrollments.map(item=>item.id),classes:[classItem.id],students:[...studentIds].filter(id=>!usedElsewhere.has(id)),meta:[`seatingSettings_${classItem.id}`]}});closeDialog();if(!state.classes.length){await resetToWelcomePreservingLegacy();showToast('クラスがなくなったため、初期設定へ戻りました');}else renderHome();});}

  async function inspectArchiveFile(file){
    if(!file)return;try{const envelope=validateEncryptedEnvelope(JSON.parse(await readImportText(file,'保管ファイル')));openDialog(`<h2>${esc(envelope.yearLabel||'保管年度')}を確認</h2><p class="panel small">パスワードのヒント：${esc(envelope.passwordHint||'ファイル表面には保存されていません')}</p><form id="archive-inspect-form"><div class="field"><label for="archive-method">開く方法</label><select class="select" id="archive-method"><option value="password">年度パスワード</option><option value="recovery">復旧コード</option></select></div><div class="field section"><label for="archive-credential">パスワードまたは復旧コード</label><input class="input" id="archive-credential" type="password" required autofocus></div><p class="error" id="archive-inspect-error"></p><div class="dialog-actions"><button type="button" class="button" id="archive-inspect-cancel">キャンセル</button><button type="submit" class="button primary">内容を確認</button></div></form>`);document.getElementById('archive-inspect-cancel').addEventListener('click',closeDialog);document.getElementById('archive-inspect-form').addEventListener('submit',async event=>{event.preventDefault();const error=document.getElementById('archive-inspect-error'),method=document.getElementById('archive-method').value,credential=document.getElementById('archive-credential').value.trim();error.textContent='読み取っています…';try{const payload=validateSyncPayload(await decryptEnvelope(envelope,method==='recovery'?credential.toUpperCase():credential,method)),data=payload.data,classes=data.classes,students=data.students,records=data.records;openDialog(`<h2>${esc(payload.yearLabel||envelope.yearLabel||'保管年度')}の内容</h2><div class="overview-stats"><div class="overview-stat"><span class="row-meta">クラス</span><strong>${classes.length}</strong></div><div class="overview-stat"><span class="row-meta">児童</span><strong>${students.length}</strong></div><div class="overview-stat"><span class="row-meta">記録</span><strong>${records.length}</strong></div></div><div class="list section">${classes.map(item=>`<div class="list-row"><strong>${esc(item.name)}</strong><span class="row-meta">${data.enrollments.filter(row=>row.classId===item.id).length}人</span></div>`).join('')}</div><p class="muted section">この確認では、現在のアプリへデータを追加していません。</p><div class="dialog-actions"><button type="button" class="button primary" id="archive-result-close">OK</button></div>`);document.getElementById('archive-result-close').addEventListener('click',closeDialog);}catch(problem){error.textContent=problem.message||'保管ファイルを読み取れませんでした';}});}catch(problem){openDialog(`<h2>読み込めませんでした</h2><p>${esc(problem.message||'ファイルを確認してください')}</p><div class="dialog-actions"><button type="button" class="button primary" id="archive-error-close">OK</button></div>`);document.getElementById('archive-error-close').addEventListener('click',closeDialog);}
  }

  async function exportClassCsv(kind){
    const classId=document.getElementById('csv-class').value,start=document.getElementById('csv-start').value,end=document.getElementById('csv-end').value,error=document.getElementById('csv-error');
    error.textContent='';if(!start||!end||start>end){error.textContent='出力期間を確認してください。';return;}
    const classItem=state.classes.find(item=>item.id===classId);if(!classItem){error.textContent='クラスを選択してください。';return;}
    const roster=await rosterForRange(classId,start,end),records=await ClassDB.getAllByIndex('records','classId',classId),args={classItem,roster,records,start,end};
    const rows=kind==='submission'?ClassCsvExport.submissionRows(args):ClassCsvExport.assessmentRows(args),label=kind==='submission'?'提出状況':'評価一覧';
    downloadCsv(`${label}_${safeFilePart(classItem.name)}_${start.replaceAll('-','')}-${end.replaceAll('-','')}.csv`,ClassCsvExport.csv(rows));showToast(`${label}CSVを保存しました（${Math.max(0,rows.length-1)}件）`);
  }

  async function inspectSmartImportFiles(files){
    if(!files.length)return;try{
      const legacy=await LegacyMigration.fromFiles(files),recognized=new Set(legacy.flatMap(source=>source.fileNames||[])),tables=files.filter(file=>!recognized.has(file.name));
      if(legacy.length&&!tables.length){await openLegacyMigrationReview(legacy);return;}
      if(!legacy.length&&tables.length===1){openExternalImport(tables[0]);return;}
      openDialog(`<h2>ファイルの種類を確認しました</h2><p class="muted">判別できたものから、取り込みたい内容を選んでください。</p><div class="import-choice-list section">${legacy.length?`<button type="button" class="import-choice" id="smart-open-legacy"><strong>以前のツールのデータ</strong><span>${legacy.length}件のデータ群を検出しました</span><b>内容を確認 ›</b></button>`:''}${tables.map((file,index)=>`<button type="button" class="import-choice" data-smart-table="${index}"><strong>${esc(file.name)}</strong><span>表の内容から、毎日の宿題・週宿題・提出物を推測します</span><b>判別する ›</b></button>`).join('')}</div><div class="dialog-actions"><button type="button" class="button" id="smart-import-close">閉じる</button></div>`);document.getElementById('smart-import-close').addEventListener('click',closeDialog);document.getElementById('smart-open-legacy')?.addEventListener('click',()=>{closeDialog();openLegacyMigrationReview(legacy);});document.querySelectorAll('[data-smart-table]').forEach(button=>button.addEventListener('click',()=>{const file=tables[Number(button.dataset.smartTable)];closeDialog();openExternalImport(file);}));
    }catch(problem){openDialog(`<h2>ファイルを判別できませんでした</h2><p>${esc(problem.message||'ファイルの形式を確認してください')}</p><p class="muted">CSV・Excelは表の見出しに「日付」「氏名または出席番号」「状態」を入れると判別しやすくなります。</p><div class="dialog-actions"><button type="button" class="button primary" id="smart-import-close">OK</button></div>`);document.getElementById('smart-import-close').addEventListener('click',closeDialog);}
  }

  function legacySourceDescription(source){const descriptions={classChecker:['自クラスのクラスチェッカー','毎日の宿題・週宿題（自主学習ノートなど）・賞状・メモ・ノート評価・座席を移します'],multi:['他クラスのノート評価','複数クラスチェッカーのノート評価を、選んだクラスへ移します'],seating:['席替えメーカー','名簿・座席・配慮設定を席替えへ移します'],behavior:['行動記録・所見文ツール','児童メモまたは個別支援級の学習記録へ移します']};return descriptions[source.kind]||['旧ツールのデータ','内容を確認して対応する記録へ移します'];}

  async function openLegacyMigrationReview(sources){
    if(!sources?.length){showToast('移行できる旧データは見つかりませんでした');return;}
    state.migrationSources=sources;
    const years=await ClassDB.getAll('years'),classes=await ClassDB.getAll('classes');
    const targets=classes.map(item=>{const year=years.find(row=>row.id===item.yearId);return{...item,yearLabel:year?.label||'年度不明'};});
    if(!targets.length){openDialog(`<h2>先に移行先のクラスを作成してください</h2><p>旧データを入れるクラスがまだありません。「クラス・児童」からクラスを作ると、取り込み先を選べるようになります。</p><div class="dialog-actions"><button type="button" class="button" id="migration-no-target-close">閉じる</button><button type="button" class="button primary" id="migration-no-target-classes">クラスを作る</button></div>`);document.getElementById('migration-no-target-close').addEventListener('click',closeDialog);document.getElementById('migration-no-target-classes').addEventListener('click',()=>{closeDialog();state.settingsTab='classes';state.classSettingsView='list';renderSettings();});return;}
    const defaultId=selectedClass()?.id||targets[0]?.id;
    const body=`<section class="panel"><div class="setup-steps" aria-label="取込の進行状況"><span class="step active"></span><span class="step active"></span><span class="step"></span></div><h1>ファイルの種類と移行内容を確認</h1><p class="muted">①ファイルを読みました。②移行先を選びます。まだデータは保存されていません。</p></section><section class="panel"><div class="list">${sources.map(source=>{const [kind,description]=legacySourceDescription(source);return`<div class="list-row migration-row"><div><span class="status-pill neutral">${esc(kind)}と推測</span><div class="row-title">${esc(source.label)}</div><div class="row-meta">${esc(description)}</div><div class="row-meta">児童 ${source.studentCount}人・移行できる記録 ${source.recordCount}件</div></div><div class="field migration-target"><label for="migration-${source.id}">移行先</label><select class="select" id="migration-${source.id}" data-migration-target="${source.id}">${targets.map(target=>`<option value="${target.id}" ${target.id===defaultId?'selected':''}>${esc(target.yearLabel)}・${esc(target.name)}</option>`).join('')}</select></div></div>`;}).join('')}</div><p class="notice small">移行先を確認したら、下のボタンを押してください。同じ記録は重複させません。</p><div class="button-row end section"><button type="button" class="button" id="migration-cancel">キャンセル</button><button type="button" class="button primary" id="migration-apply">この内容で一括移行</button></div></section>`;
    if(state.dataInSettings){state.settingsTab='data';await renderDataExchange(true);document.getElementById('settings-content').innerHTML=body;}else{app.innerHTML=teacherToolShell('旧データ移行',body);wireToolHome();}
    document.getElementById('migration-cancel').addEventListener('click',()=>renderDataExchange(state.dataInSettings));
+    document.getElementById('migration-apply').addEventListener('click',event=>runOnce(event.currentTarget,applyLegacyMigration));
  }

  async function legacyRosterMap(source,classId){
    const existing=await rosterForClass(classId),byNumber=new Map(),nameByNumber=new Map(),byName=new Map(),sourceNumberMap=new Map();
    existing.forEach(row=>{byNumber.set(Number(row.enrollment.number),row.student.id);nameByNumber.set(Number(row.enrollment.number),normalizeStudentName(row.student.name));byName.set(normalizeStudentName(row.student.name),row.student.id);});
    for(const row of LegacyMigration.roster(source)){
      const requested=Number(row.number)||null,name=normalizeStudentName(row.name),numberMatch=requested&&nameByNumber.get(requested)===name?byNumber.get(requested):null;
      let studentId=byName.get(name)||numberMatch;
      if(!studentId){const classItem=await ClassDB.get('classes',classId),year=classItem?await ClassDB.get('years',classItem.yearId):state.year;const student=await ClassDB.put('students',{id:ClassDB.uid('student'),name:row.name});studentId=student.id;let assigned=requested;if(!assigned||byNumber.has(assigned)){assigned=1;while(byNumber.has(assigned))assigned++;}await ClassDB.put('enrollments',{id:ClassDB.uid('enrollment'),classId,studentId,number:assigned,grade:row.grade||'',gender:row.gender||'',startDate:year?.startDate||state.year.startDate});byNumber.set(assigned,studentId);nameByNumber.set(assigned,name);}
      if(requested)sourceNumberMap.set(requested,studentId);byName.set(name,studentId);
    }
    return{resolve:({number,name})=>byName.get(normalizeStudentName(name))||(number?sourceNumberMap.get(Number(number)):null)||null};
  }

  function comparableLegacy(record){const copy={...record};for(const key of ['createdAt','updatedAt','deviceId'])delete copy[key];return JSON.stringify(copy);}
  async function saveLegacyRecord(record){
    const existing=await ClassDB.get('records',record.id);
    if(!existing){await ClassDB.put('records',record);return'added';}
    if(comparableLegacy(existing)===comparableLegacy(record))return'skipped';
    await ClassDB.put('records',{...record,id:ClassDB.uid('legacyConflict'),conflictOriginalId:record.id,needsReview:true});return'conflict';
  }

  async function applyLegacyMigration(){
    const counts={students:0,records:0,conflicts:0,skipped:0},cleanup=new Set(await ClassDB.getMeta('legacyCleanupKeys',[]));
    for(const source of state.migrationSources){
      const classId=document.querySelector(`[data-migration-target="${source.id}"]`)?.value;if(!classId)continue;
      const before=(await rosterForClass(classId)).length,map=await legacyRosterMap(source,classId),after=(await rosterForClass(classId)).length;counts.students+=Math.max(0,after-before);
      const targetClass=await ClassDB.get('classes',classId);const converted=LegacyMigration.records(source,map.resolve,classId).map(record=>source.kind==='behavior'&&!isSupportClass(targetClass)?{...record,type:'memo',tags:record.tags||[]}:record);
      for(const record of converted){const result=await saveLegacyRecord(record);if(result==='added')counts.records++;else if(result==='conflict')counts.conflicts++;else counts.skipped++;}
      const patch=LegacyMigration.classPatch(source,map.resolve);if(patch){const {__seatingSettings,...classFields}=patch;await ClassDB.put('classes',{...targetClass,...classFields});if(__seatingSettings)await ClassDB.setMeta(`seatingSettings_${classId}`,__seatingSettings);}
      source.cleanupKeys.forEach(key=>cleanup.add(key));
    }
    await ClassDB.setMeta('legacyCleanupKeys',[...cleanup]);
    await ClassDB.setMeta('lastLegacyMigration',{at:ClassDB.now(),sources:state.migrationSources.map(item=>item.label),counts});
    state.classes=(await ClassDB.getAllByIndex('classes','yearId',state.year.id)).sort((a,b)=>(b.isOwn-a.isOwn)||(a.order-b.order));state.migrationSources=[];
    openDialog(`<h2>旧データを移行しました</h2><p>新しい児童 ${counts.students}人、記録 ${counts.records}件を追加しました。${counts.conflicts?`内容が異なる記録 ${counts.conflicts}件は両方を残しています。`:''}</p><p class="muted">旧データはまだ削除していません。暗号化バックアップを保存し、そのファイルを読み直して確認すると削除できます。</p><div class="dialog-actions"><button type="button" class="button primary" id="migration-done">OK</button></div>`);
    document.getElementById('migration-done').addEventListener('click',()=>{closeDialog();renderDataExchange(state.dataInSettings);});
  }
  async function saveDeviceNameFromScreen(){const input=document.getElementById('sync-device-name');if(input)await ClassDB.setMeta('syncDeviceName',input.value.trim()||syncDeviceDefault());}

  function newerThan(incoming,local){return String(incoming?.updatedAt||incoming?.deletedAt||'')>String(local?.updatedAt||local?.deletedAt||'');}
  async function buildSyncPlan(payload){const stores=['years','classes','students','enrollments','records','trash'];const plan={payload,writes:{},deletes:[],counts:{add:0,update:0,conflict:0,delete:0,skip:0}};const localTrash=await ClassDB.getAll('trash');const deletedByRecord=new Map(localTrash.map(item=>[item.record?.id,item]));for(const store of stores){plan.writes[store]=[];for(const incoming of payload.data?.[store]||[]){if(store==='records'){const deleted=deletedByRecord.get(incoming.id);if(deleted&&String(deleted.deletedAt||'')>=String(incoming.updatedAt||'')){plan.counts.skip++;continue;}}const local=await ClassDB.get(store,incoming.id);if(!local){plan.writes[store].push(incoming);plan.counts.add++;continue;}if(newerThan(incoming,local)){plan.writes[store].push(incoming);plan.counts.update++;continue;}if(!incoming.updatedAt&&!local.updatedAt&&JSON.stringify(incoming)!==JSON.stringify(local)&&store==='records'){plan.writes[store].push({...incoming,id:ClassDB.uid('syncConflict'),conflictOriginalId:incoming.id,needsReview:true});plan.counts.conflict++;}else plan.counts.skip++;}}
    for(const incomingTrash of payload.data?.trash||[]){const recordId=incomingTrash.record?.id;if(!recordId)continue;const localRecord=await ClassDB.get('records',recordId);if(localRecord&&String(incomingTrash.deletedAt||'')>=String(localRecord.updatedAt||'')){plan.deletes.push({record:localRecord,trash:incomingTrash});}}
    plan.deletes=[...new Map(plan.deletes.map(item=>[item.record.id,item])).values()];plan.counts.delete=plan.deletes.length;plan.meta=[];const localOnly=new Set(['activeYearId','selectedClassId','lastMode','preSyncSnapshots']);for(const incoming of payload.data?.meta||[]){if(localOnly.has(incoming.key)){plan.counts.skip++;continue;}const local=await ClassDB.get('meta',incoming.key);if(!local||newerThan(incoming,local)){plan.meta.push(incoming);local?plan.counts.update++:plan.counts.add++;}else plan.counts.skip++;}return plan;}

  async function readEncryptedImport(file){if(!file)return;if(!await requestAnnualPassword())return;try{const envelope=validateEncryptedEnvelope(JSON.parse(await readImportText(file,'同期・バックアップファイル'))),payload=validateSyncPayload(await decryptEnvelope(envelope));if(payload.yearLabel!==state.year.label||payload.yearId!==state.year.id){showToast(`このファイルは${payload.yearLabel||'別年度'}のデータです`);return;}const cleanup=await ClassDB.getMeta('legacyCleanupKeys',[]);state.verifiedLegacyCleanupKeys=envelope.kind==='backup'&&payload.data.records.some(item=>item.legacyImported)?cleanup:[];const plan=await buildSyncPlan(payload);state.pendingSync={plan,envelope};openSyncPreview(false);}catch(error){openDialog(`<h2>読み込めませんでした</h2><p>${esc(error.message)}</p><div class="dialog-actions"><button type="button" class="button primary" id="sync-error-close">OK</button></div>`);document.getElementById('sync-error-close').addEventListener('click',closeDialog);}}
  function syncSummaryHtml(plan,detailed=false){const c=plan.counts;return`<div class="sync-summary"><div><strong>${c.add}</strong><span>追加</span></div><div><strong>${c.update}</strong><span>更新</span></div><div><strong>${c.conflict}</strong><span>要確認</span></div><div><strong>${c.delete}</strong><span>削除候補</span></div></div>${detailed?`<div class="list section"><div class="list-row"><span>変更しないデータ</span><strong>${c.skip}件</strong></div><div class="list-row"><span>取込元</span><strong>${esc(plan.payload.device||'不明')}</strong></div><div class="list-row"><span>作成日時</span><strong>${esc(new Date(plan.payload.generatedAt).toLocaleString('ja-JP'))}</strong></div></div>${c.delete?`<label class="check-row"><input type="checkbox" id="approve-sync-deletes"> 削除候補${c.delete}件をまとめて承認する</label>`:''}`:''}`;}
  function openSyncPreview(detailed){const pending=state.pendingSync;if(!pending)return;const plan=pending.plan;openDialog(`<h2>同期内容を確認</h2><p class="muted">更新日時が新しい方を採用します。</p>${syncSummaryHtml(plan,detailed)}<div class="dialog-actions"><button type="button" class="button" id="sync-cancel">同期キャンセル</button>${detailed?'':`<button type="button" class="button" id="sync-detail">詳細を表示</button>`}<button type="button" class="button primary" id="sync-apply">${detailed?'同期する':'OK'}</button></div>`);document.getElementById('sync-cancel').addEventListener('click',()=>{state.pendingSync=null;closeDialog();});document.getElementById('sync-detail')?.addEventListener('click',()=>openSyncPreview(true));document.getElementById('sync-apply').addEventListener('click',event=>runOnce(event.currentTarget,async()=>{if(plan.counts.delete&&!detailed){openSyncPreview(true);return;}await applySyncPlan(Boolean(document.getElementById('approve-sync-deletes')?.checked));}));}
  async function applySyncPlan(approveDeletes){
    const pending=state.pendingSync;if(!pending)return;const plan=pending.plan;
    await savePreSyncSnapshot();
    const puts={...plan.writes,meta:plan.meta};
    if(approveDeletes)puts.trash=[...(puts.trash||[]),...plan.deletes.map(item=>item.trash)];
    const deletes=approveDeletes?{records:plan.deletes.map(item=>item.record.id)}:{};
    await ClassDB.applyBatch({puts,deletes});
    state.year=await ClassDB.get('years',state.year.id);state.classes=(await ClassDB.getAllByIndex('classes','yearId',state.year.id)).sort((a,b)=>(b.isOwn-a.isOwn)||(a.order-b.order));state.pendingSync=null;
    const merged=await createEncryptedFile('sync',false);state.mergedSyncEnvelope=merged;await recordSyncHistory('import',{device:plan.payload.device,add:plan.counts.add,update:plan.counts.update,delete:approveDeletes?plan.counts.delete:0});const canClean=state.verifiedLegacyCleanupKeys.length>0;
    openDialog(`<h2>同期しました</h2><p>追加 ${plan.counts.add}件、更新 ${plan.counts.update}件${approveDeletes?`、削除 ${plan.counts.delete}件`:''}を反映しました。</p>${canClean?'<p class="notice"><strong>移行後の暗号化バックアップを正常に読み取れました。</strong><br>この端末に残した旧形式データを削除できます。</p>':''}<div class="dialog-actions"><button type="button" class="button" id="sync-done">OK</button>${canClean?'<button type="button" class="button danger" id="legacy-cleanup">確認済みの旧データを削除</button>':''}<button type="button" class="button primary" id="sync-save-merged">統合済み同期ファイルを保存</button></div>`);
    document.getElementById('sync-done').addEventListener('click',()=>{state.verifiedLegacyCleanupKeys=[];closeDialog();renderDataExchange(state.dataInSettings);});
    document.getElementById('legacy-cleanup')?.addEventListener('click',confirmLegacyCleanup);
    document.getElementById('sync-save-merged').addEventListener('click',()=>{const device=state.mergedSyncEnvelope.device||syncDeviceDefault();downloadText(`同期済み_${safeFilePart(state.year.label)}_${syncDateStamp()}_${safeFilePart(device)}.json`,JSON.stringify(state.mergedSyncEnvelope));showToast('統合済み同期ファイルを保存しました');});
  }

  function confirmLegacyCleanup(){
    openDialog(`<h2>旧形式データを削除しますか</h2><p>暗号化バックアップで移行済みデータを確認できました。この端末の旧ツール用データだけを削除します。新アプリの記録は削除されません。</p><div class="dialog-actions"><button type="button" class="button" id="legacy-cleanup-cancel">キャンセル</button><button type="button" class="button danger" id="legacy-cleanup-apply">削除する</button></div>`);
    document.getElementById('legacy-cleanup-cancel').addEventListener('click',closeDialog);
    document.getElementById('legacy-cleanup-apply').addEventListener('click',async()=>{for(const key of state.verifiedLegacyCleanupKeys)localStorage.removeItem(key);state.verifiedLegacyCleanupKeys=[];await ClassDB.setMeta('legacyCleanupKeys',[]);closeDialog();showToast('確認済みの旧形式データを削除しました');renderDataExchange(state.dataInSettings);});
  }

  function renderDataSettings(){renderDataExchange(true);}
  async function openDataManagement(){state.settingsTab='data';await renderSettings();await renderDataExchange(true);}
