"use strict";

  async function renderMemos(){
    if(!teacherActive()){renderPupil();return;}
    state.route='teacher-memo';state.activeTool='memo';
    const classItem=selectedClass();applyClassTheme(classItem);const date=state.toolDraft.memoDate||today();state.toolDraft.memoDate=date;
    const records=(await ClassDB.getAllByIndex('records','classId',classItem.id)).filter(item=>item.type==='memo'&&item.date===date&&!item.deletedAt);
    const shortages=await memoShortages(classItem,date);
    const latest=new Map();records.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).forEach(item=>{if(!latest.has(item.studentId))latest.set(item.studentId,item);});
    const cards=await teacherRosterCards(classItem.id,[...latest.values()],{orderMode:teacherOrderMode(),atDate:date,status:record=>record?(record.tags?.join('・')||record.viewpoint||'記録あり'):'記録を追加'});
    const shortageHtml=isSupportClass(classItem)?`<section class="panel memo-shortage"><h2>メモが不足　${shortages.length}人</h2>${shortages.length?`<div class="list">${shortages.map(item=>`<div class="shortage-row"><strong>${esc(item.student.name)}</strong><div class="shortage-subjects">${item.subjects.map(subject=>`<button type="button" data-shortage-student="${item.student.id}" data-shortage-subject="${esc(subject)}">${esc(subject)}</button>`).join('')}</div></div>`).join('')}</div>`:'<p class="muted">設定したすべての教科にメモがあります。</p>'}</section>`:'';
    app.innerHTML=teacherToolShell('児童メモ',`${pupilDateNav(date,'memo-prev','memo-next')}<section class="panel"><div class="toolbar-line"><div><h1>${esc(classItem.name)}の児童メモ</h1><p class="muted">教科とタグを選ぶだけでも保存できます。必要なときだけ自由記述を加えます。</p></div>${teacherOrderControlHtml()}</div></section>${shortageHtml}${cards}`);
    wireToolHome();wireStudentDetails();wireTeacherOrder(renderMemos);
    document.getElementById('memo-prev').addEventListener('click',()=>{state.toolDraft.memoDate=moveDate(date,-1);renderMemos();});document.getElementById('memo-next').addEventListener('click',()=>{state.toolDraft.memoDate=moveDate(date,1);renderMemos();});
    document.querySelectorAll('[data-tool-student]').forEach(button=>button.addEventListener('click',()=>openMemoEditor(button.dataset.toolStudent)));
    document.querySelectorAll('[data-shortage-student]').forEach(button=>button.addEventListener('click',()=>openMemoEditor(button.dataset.shortageStudent,button.dataset.shortageSubject)));
  }

  async function openMemoEditor(studentId,defaultSubject=''){
    const student=await ClassDB.get('students',studentId);const classItem=selectedClass();
    const memoTags=await ClassDB.getMeta('memoTags',MEMO_TAGS);
    openDialog(`<h2>${esc(student.name)}のメモ</h2><form id="memo-form"><div class="form-grid"><div class="field"><label for="memo-date">日付</label><input class="input" id="memo-date" type="date" value="${state.toolDraft.memoDate||today()}" required></div><div class="field"><label for="memo-subject">教科</label><select class="select" id="memo-subject"><option value="">教科なし</option>${classSubjects(classItem).map(subject=>`<option ${subject===defaultSubject?'selected':''}>${esc(subject)}</option>`).join('')}</select></div><div class="field full"><span class="field-label">プラス評価タグ（複数選択可）</span><div class="tag-list" id="memo-tags">${memoTags.map(tag=>`<button type="button" class="tag-chip" data-memo-tag="${esc(tag)}" aria-pressed="false">${esc(tag)}</button>`).join('')}</div></div><div class="field full"><label for="memo-text">自由記述（任意）</label><textarea class="textarea" id="memo-text"></textarea></div></div><div class="dialog-actions"><button type="button" class="button" id="memo-cancel">キャンセル</button><button type="submit" class="button primary">保存</button></div></form>`);
    document.querySelectorAll('[data-memo-tag]').forEach(button=>button.addEventListener('click',()=>button.setAttribute('aria-pressed',String(button.getAttribute('aria-pressed')!=='true'))));
    document.getElementById('memo-cancel').addEventListener('click',closeDialog);
    document.getElementById('memo-form').addEventListener('submit',async event=>{event.preventDefault();const tags=[...document.querySelectorAll('#memo-tags [aria-pressed="true"]')].map(button=>button.dataset.memoTag);await ClassDB.put('records',{id:ClassDB.uid('memo'),type:'memo',classId:classItem.id,studentId,date:document.getElementById('memo-date').value,subject:document.getElementById('memo-subject').value,tags,text:document.getElementById('memo-text').value.trim()});closeDialog();showToast('児童メモを保存しました');renderMemos();});
  }

  async function renderCertificates(){
    if(!teacherActive()){renderPupil();return;}
    state.route='teacher-certificate';state.activeTool='certificate';
    const classItem=selectedClass();applyClassTheme(classItem);const date=state.toolDraft.certificateDate||today();state.toolDraft.certificateDate=date;
    const records=(await ClassDB.getAllByIndex('records','classId',classItem.id)).filter(item=>item.type==='certificate'&&item.date===date&&!item.deletedAt);
    const allCertificates=(await ClassDB.getAllByIndex('records','classId',classItem.id)).filter(item=>item.type==='certificate'&&item.date<=date&&!item.deletedAt);const certificateSummary=new Map();for(const item of allCertificates.sort((a,b)=>a.date.localeCompare(b.date))){const summary=certificateSummary.get(item.studentId)||{count:0,dates:[]};summary.count++;summary.dates.push(item.date);certificateSummary.set(item.studentId,summary);}const cards=await teacherRosterCards(classItem.id,records,{orderMode:teacherOrderMode(),atDate:date,status:(record,row)=>{const summary=certificateSummary.get(row.student.id)||{count:0,dates:[]},prior=summary.dates.filter(value=>value<date).at(-1),days=prior?Math.max(0,Math.round((new Date(`${date}T00:00:00`)-new Date(`${prior}T00:00:00`))/86400000)):null;if(record)return`本日配付・今年度${summary.count}回${days!==null?`・前回から${days}日`:''}`;if(!summary.count)return'今年度0回・未配付';const last=summary.dates.at(-1),since=Math.max(0,Math.round((new Date(`${date}T00:00:00`)-new Date(`${last}T00:00:00`))/86400000));return`今年度${summary.count}回・前回から${since}日`;},statusClass:record=>record?'good':''});
    app.innerHTML=teacherToolShell('ミニ賞状',`${pupilDateNav(date,'certificate-prev','certificate-next')}<section class="panel"><div class="toolbar-line"><div><h1>${esc(classItem.name)}のミニ賞状</h1><p class="muted">児童名を押して、渡したことを記録します。</p></div>${teacherOrderControlHtml()}</div>${operationTipHtml('押し方を見る','1回目で「渡した」と記録します。同じ名前をもう一度押すと、理由タグの追加や配付取消ができます。')}</section>${cards}`);
    wireToolHome();wireStudentDetails();wireTeacherOrder(renderCertificates);
    document.getElementById('certificate-prev').addEventListener('click',()=>{state.toolDraft.certificateDate=moveDate(date,-1);renderCertificates();});document.getElementById('certificate-next').addEventListener('click',()=>{state.toolDraft.certificateDate=moveDate(date,1);renderCertificates();});
    document.querySelectorAll('[data-tool-student]').forEach(button=>button.addEventListener('click',()=>handleCertificateTap(button.dataset.toolStudent)));
  }

  async function handleCertificateTap(studentId){
    const classItem=selectedClass();const date=state.toolDraft.certificateDate||today();const id=`certificate_${classItem.id}_${date}_${studentId}`;const record=await ClassDB.get('records',id);
    if(!record){await ClassDB.put('records',{id,type:'certificate',classId:classItem.id,studentId,date,tags:[],text:''});showToast('渡したとして記録しました');renderCertificates();return;}
    const student=await ClassDB.get('students',studentId);
    const tags=await ClassDB.getMeta('certificateTags',['最後まで取り組んだ','工夫した','友達を助けた','よく発表した','丁寧に仕上げた','成長が見られた']);
    openDialog(`<h2>${esc(student.name)}のミニ賞状</h2><p class="muted">渡した理由を選び、必要ならメモを加えます。</p><form id="certificate-form"><div class="tag-list" id="certificate-tags">${tags.map(tag=>`<button type="button" class="tag-chip" data-tag="${esc(tag)}" aria-pressed="${record.tags?.includes(tag)||false}">${esc(tag)}</button>`).join('')}</div><div class="field section"><label for="certificate-text">メモ（任意）</label><textarea class="textarea" id="certificate-text">${esc(record.text||'')}</textarea></div><div class="dialog-actions"><button type="button" class="button danger" id="certificate-delete">渡すのを取り消す</button><button type="button" class="button" id="certificate-close">閉じる</button><button type="submit" class="button primary">保存</button></div></form>`);
    document.querySelectorAll('#certificate-tags [data-tag]').forEach(button=>button.addEventListener('click',()=>button.setAttribute('aria-pressed',String(button.getAttribute('aria-pressed')!=='true'))));
    document.getElementById('certificate-close').addEventListener('click',closeDialog);
    document.getElementById('certificate-delete').addEventListener('click',async()=>{await moveToTrash(record);closeDialog();showToast('配付を取り消しました');renderCertificates();});
    document.getElementById('certificate-form').addEventListener('submit',async event=>{event.preventDefault();const selected=[...document.querySelectorAll('#certificate-tags [aria-pressed="true"]')].map(item=>item.dataset.tag);await ClassDB.put('records',{...record,tags:selected,text:document.getElementById('certificate-text').value.trim()});closeDialog();showToast('理由メモを保存しました');renderCertificates();});
  }

  function simpleHash(value){let hash=2166136261;for(let i=0;i<value.length;i++){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(36);}
  function notebookDraft(){return state.toolDraft.notebook||(state.toolDraft.notebook={date:today(),subject:'国語',unit:'',title:''});}
  function notebookSessionKey(draft){return simpleHash([draft.date,draft.subject,draft.unit,draft.title].join('|'));}
  const NOTEBOOK_POINTS={'A':5,'B+':4,'B':3,'B-':2,'C':1};
  const NOTEBOOK_VIEWPOINTS=[{key:'knowledge',short:'知',label:'知識・技能'},{key:'thinking',short:'思',label:'思考・判断・表現'},{key:'attitude',short:'態',label:'主体的に学習に取り組む態度'}];
  const NOTEBOOK_DEFAULT_GRADES={knowledge:'B',thinking:'B',attitude:'B'};
  function notebookGradeText(grade){return String(grade||'—').replace('+','＋').replace('-','－');}
  function notebookViewpointGrades(record){const fallback=Object.prototype.hasOwnProperty.call(NOTEBOOK_POINTS,record?.grade)?record.grade:'B',saved=record?.viewpointGrades||{};return Object.fromEntries(NOTEBOOK_VIEWPOINTS.map(item=>[item.key,Object.prototype.hasOwnProperty.call(NOTEBOOK_POINTS,saved[item.key])?saved[item.key]:fallback]));}
  function notebookOverallGrade(grades){const values=NOTEBOOK_VIEWPOINTS.map(item=>NOTEBOOK_POINTS[grades?.[item.key]]).filter(Number.isFinite);if(!values.length)return null;const average=values.reduce((sum,value)=>sum+value,0)/values.length;if(average>=4.5)return'A';if(average>=3.5)return'B+';if(average>=2.5)return'B';if(average>=1.5)return'B-';return'C';}
  function notebookViewpointText(record){if(record?.status==='absent')return'欠席';if(record?.status==='unsubmitted')return'未提出';const grades=notebookViewpointGrades(record);return NOTEBOOK_VIEWPOINTS.map(item=>`${item.short}${notebookGradeText(grades[item.key])}`).join('・');}
  function notebookViewpointPickerHtml(grades){return`<div class="viewpoint-grade-editor">${NOTEBOOK_VIEWPOINTS.map(item=>`<div class="viewpoint-grade-row"><div class="viewpoint-grade-label"><span>${item.short}</span><strong>${item.label}</strong></div><div class="viewpoint-grade-choices" role="group" aria-label="${item.label}の評価">${Object.keys(NOTEBOOK_POINTS).map(grade=>`<button type="button" class="viewpoint-grade-button grade-${grade.toLowerCase().replace('+','plus').replace('-','minus')}" data-viewpoint-key="${item.key}" data-viewpoint-grade="${grade}" aria-pressed="${grades[item.key]===grade}">${notebookGradeText(grade)}</button>`).join('')}</div></div>`).join('')}</div>`;}
  function wireNotebookViewpointPicker(root=document){root.querySelectorAll('[data-viewpoint-grade]').forEach(button=>button.addEventListener('click',()=>{root.querySelectorAll(`[data-viewpoint-key="${button.dataset.viewpointKey}"]`).forEach(item=>item.setAttribute('aria-pressed',String(item===button)));}));}
  function readNotebookViewpointGrades(root=document){return Object.fromEntries(NOTEBOOK_VIEWPOINTS.map(item=>[item.key,root.querySelector(`[data-viewpoint-key="${item.key}"][aria-pressed="true"]`)?.dataset.viewpointGrade||'B']));}
  function resetNotebookViewpointPicker(root=document){root.querySelectorAll('[data-viewpoint-grade]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.viewpointGrade==='B')));}
  function notebookSummaryPeriod(draft){return['front','back','year'].includes(draft.summaryPeriod)?draft.summaryPeriod:(draft.date<=state.year.firstTermEnd?'front':'back');}
  function notebookSummaryPeriodRange(period){
    if(period==='front')return{label:'前期',start:state.year.startDate,end:state.year.firstTermEnd};
    if(period==='back')return{label:'後期',start:moveDate(state.year.firstTermEnd,1),end:state.year.endDate};
    return{label:'年間',start:state.year.startDate,end:state.year.endDate};
  }
  function notebookAverageLabel(value){if(value===null)return'—';if(value>=4.5)return'A';if(value>=3.5)return'B＋';if(value>=2.5)return'B';if(value>=1.5)return'B－';return'C';}
  function notebookStudentSummary(records){
    const distribution={'A':0,'B+':0,'B':0,'B-':0,'C':0},viewpoints=Object.fromEntries(NOTEBOOK_VIEWPOINTS.map(item=>[item.key,{points:0,count:0,average:null}]));let points=0,pointCount=0,count=0,absent=0,unsubmitted=0;
    for(const record of records){if(record.status==='absent'){absent++;continue;}if(record.status==='unsubmitted'){unsubmitted++;continue;}const grades=notebookViewpointGrades(record);count++;for(const item of NOTEBOOK_VIEWPOINTS){const grade=grades[item.key],value=NOTEBOOK_POINTS[grade];if(!Number.isFinite(value))continue;distribution[grade]++;points+=value;pointCount++;viewpoints[item.key].points+=value;viewpoints[item.key].count++;}}
    for(const item of NOTEBOOK_VIEWPOINTS){const summary=viewpoints[item.key];summary.average=summary.count?summary.points/summary.count:null;}
    return{distribution,viewpoints,points,pointCount,count,absent,unsubmitted,average:pointCount?points/pointCount:null};
  }
  async function notebookSummaryHtml(classItem,draft,allRecords){
    const period=notebookSummaryPeriod(draft),range=notebookSummaryPeriodRange(period),roster=await rosterForRange(classItem.id,range.start,range.end);
    const subjectRecords=allRecords.filter(item=>item.subject===draft.subject&&item.date>=range.start&&item.date<=range.end),byStudent=new Map();
    for(const record of subjectRecords){if(!byStudent.has(record.studentId))byStudent.set(record.studentId,[]);byStudent.get(record.studentId).push(record);}
    let totalPoints=0,totalPointCount=0,totalCount=0,evaluatedStudents=0;const viewpointTotals=Object.fromEntries(NOTEBOOK_VIEWPOINTS.map(item=>[item.key,{points:0,count:0}]));
    const rows=roster.map(row=>{
      const{distribution,viewpoints,points,pointCount,count,absent,unsubmitted,average}=notebookStudentSummary(byStudent.get(row.student.id)||[]);if(count){totalPoints+=points;totalPointCount+=pointCount;totalCount+=count;evaluatedStudents++;for(const item of NOTEBOOK_VIEWPOINTS){viewpointTotals[item.key].points+=viewpoints[item.key].points;viewpointTotals[item.key].count+=viewpoints[item.key].count;}}
      const viewpointValues=NOTEBOOK_VIEWPOINTS.map(item=>`<div class="notebook-summary-value"><span>${item.short}平均</span><strong>${viewpoints[item.key].average===null?'—':viewpoints[item.key].average.toFixed(2)}</strong></div>`).join('');
      return`<div class="notebook-summary-row ${count?'':'no-data'}"><div class="notebook-summary-name"><span class="student-number">${esc(row.enrollment.number||'—')}</span><strong>${esc(row.student.name)}</strong></div>${viewpointValues}<div class="notebook-summary-value"><span>3観点</span><strong>${average===null?'—':`${average.toFixed(2)} <small>${notebookAverageLabel(average)}</small>`}</strong></div><div class="notebook-summary-value"><span>回数</span><strong>${count}回</strong></div><div class="notebook-summary-meta"><div class="notebook-distribution" aria-label="3観点の評価内訳"><span>A ${distribution.A}</span><span>B＋ ${distribution['B+']}</span><span>B ${distribution.B}</span><span>B－ ${distribution['B-']}</span><span>C ${distribution.C}</span><small>3観点の合計</small></div><div class="notebook-exceptions"><span>欠席 ${absent}</span><span>未提出 ${unsubmitted}</span></div></div></div>`;
    }).join('');
    const classAverage=totalPointCount?(totalPoints/totalPointCount).toFixed(2):'—',viewpointStats=NOTEBOOK_VIEWPOINTS.map(item=>{const value=viewpointTotals[item.key];return`<div><span>${item.label}</span><strong>${value.count?(value.points/value.count).toFixed(2):'—'}</strong></div>`;}).join('');
    return`<details class="panel notebook-summary-panel" ${draft.summaryOpen?'open':''}><summary class="notebook-summary-toggle"><span><strong>${esc(draft.subject)}の3観点評価集計</strong><small>前期・後期・年間の平均と内訳を確認</small></span></summary><div class="notebook-summary-content"><div class="toolbar-line"><p class="muted">${esc(range.label)}　${esc(jpDate(range.start))}〜${esc(jpDate(range.end))}</p><div class="notebook-period-switch" role="group" aria-label="集計期間"><button type="button" data-notebook-period="front" aria-pressed="${period==='front'}">前期</button><button type="button" data-notebook-period="back" aria-pressed="${period==='back'}">後期</button><button type="button" data-notebook-period="year" aria-pressed="${period==='year'}">年間</button></div></div><div class="notebook-summary-stats">${viewpointStats}<div><span>3観点の平均</span><strong>${classAverage}${totalPointCount?` <small>${notebookAverageLabel(totalPoints/totalPointCount)}</small>`:''}</strong></div><div><span>評価した回数</span><strong>${totalCount}回</strong></div><div><span>記録がある児童</span><strong>${evaluatedStudents} / ${roster.length}人</strong></div></div><div class="notebook-summary-list">${rows||'<div class="empty-state">この期間に在籍する児童がいません。</div>'}</div><details class="operation-tip" ${state.informationMode==='detailed'?'open':''}><summary>平均の計算方法</summary><p>各観点をA=5、B＋=4、B=3、B－=2、C=1として平均します。欠席・未提出は平均から除外し、回数だけを別に表示します。平均に添えた段階は成績を考えるための目安で、通知表の評定を自動決定するものではありません。</p></details></div></details>`;
  }

  async function renderNotebook(){
    if(!teacherActive()){renderPupil();return;}
    state.route='teacher-assessment';state.activeTool='assessment';
    const classItem=selectedClass();applyClassTheme(classItem);const draft=notebookDraft();const subjects=classSubjects(classItem);if(!subjects.includes(draft.subject))draft.subject=subjects[0];const sessionKey=notebookSessionKey(draft);
    const allRecords=(await ClassDB.getAllByIndex('records','classId',classItem.id)).filter(item=>item.type==='notebookAssessment'&&!item.deletedAt),records=allRecords.filter(item=>item.sessionKey===sessionKey),summary=await notebookSummaryHtml(classItem,draft,allRecords);
    const cards=await teacherRosterCards(classItem.id,records,{orderMode:teacherOrderMode(),atDate:draft.date,status:record=>record?notebookViewpointText(record):'未評価',statusClass:record=>{if(!record)return'';if(record.status==='unsubmitted')return'alert';if(record.status==='absent')return'warn';const grade=record.grade||notebookOverallGrade(notebookViewpointGrades(record));return grade?`grade-${grade.toLowerCase().replace('+','plus').replace('-','minus')}`:'';}});
    app.innerHTML=teacherToolShell('ノート評価',`${pupilDateNav(draft.date,'notebook-prev','notebook-next')}<section class="panel"><div class="toolbar-line"><div><h1>${esc(classItem.name)}のノート評価</h1><p class="muted">児童名を1回押すと、3観点すべてBで記録します。</p></div>${teacherOrderControlHtml()}</div><div class="tool-controls"><div class="field"><label for="notebook-subject">教科</label><select class="select" id="notebook-subject">${subjects.map(subject=>`<option ${subject===draft.subject?'selected':''}>${subject}</option>`).join('')}</select></div><div class="field"><label for="notebook-unit">単元</label><input class="input" id="notebook-unit" value="${esc(draft.unit)}"></div><div class="field wide"><label for="notebook-title">題名（任意）</label><input class="input" id="notebook-title" value="${esc(draft.title)}" placeholder="空欄なら ${esc(slashDate(draft.date))}"></div></div><div class="button-row end"><button type="button" class="button primary" id="notebook-apply">この内容で表示</button></div>${operationTipHtml('3観点の変え方を見る','通常は1回押すだけで「知B・思B・態B」になります。よくできた観点や気になる観点があるときだけ、同じ名前をもう一度押して変更します。')}<p class="muted small">題名が空欄の場合は「${esc(draft.subject)}　${esc(draft.unit||'単元')}　${esc(slashDate(draft.date))}」と表示します。</p></section>${summary}${cards}`);
    wireToolHome();wireStudentDetails();wireTeacherOrder(renderNotebook);
    document.getElementById('notebook-prev').addEventListener('click',()=>{state.toolDraft.notebook={...draft,date:moveDate(draft.date,-1)};renderNotebook();});document.getElementById('notebook-next').addEventListener('click',()=>{state.toolDraft.notebook={...draft,date:moveDate(draft.date,1)};renderNotebook();});
    document.getElementById('notebook-apply').addEventListener('click',()=>{state.toolDraft.notebook={date:draft.date,subject:document.getElementById('notebook-subject').value.trim(),unit:document.getElementById('notebook-unit').value.trim(),title:document.getElementById('notebook-title').value.trim(),summaryPeriod:notebookSummaryPeriod(draft),summaryOpen:Boolean(draft.summaryOpen)};renderNotebook();});
    document.querySelector('.notebook-summary-panel')?.addEventListener('toggle',event=>{draft.summaryOpen=event.currentTarget.open;});
    document.querySelectorAll('[data-notebook-period]').forEach(button=>button.addEventListener('click',()=>{state.toolDraft.notebook={...draft,summaryPeriod:button.dataset.notebookPeriod};renderNotebook();}));
    document.querySelectorAll('[data-tool-student]').forEach(button=>button.addEventListener('click',()=>handleNotebookTap(button.dataset.toolStudent)));
  }

  async function handleNotebookTap(studentId){
    const classItem=selectedClass();const draft=notebookDraft();
    if(!draft.date||!draft.subject){showToast('日付と教科を選んでください');return;}
    const sessionKey=notebookSessionKey(draft);const id=`notebook_${classItem.id}_${sessionKey}_${studentId}`;const current=await ClassDB.get('records',id);
    if(!current){await saveNotebookGrades(studentId,{...NOTEBOOK_DEFAULT_GRADES});showToast('3観点をすべてBで記録しました');renderNotebook();return;}
    const student=await ClassDB.get('students',studentId);
    const grades=notebookViewpointGrades(current);
    openDialog(`<h2>${esc(student.name)}の3観点評価</h2><p class="muted">変更したい観点だけ選びます。ほかの観点はそのままです。</p><form id="notebook-grade-form">${notebookViewpointPickerHtml(grades)}<div class="button-row section"><button type="button" class="button" id="grade-reset-b">すべてBに戻す</button></div><div class="notebook-status-actions section"><span>作品全体の状態</span><button type="button" class="button" data-status="absent">欠席</button><button type="button" class="button" data-status="unsubmitted">未提出</button></div><div class="dialog-actions"><button type="button" class="button" id="grade-close">キャンセル</button><button type="submit" class="button primary">変更を保存</button></div></form>`);
    wireNotebookViewpointPicker();document.getElementById('grade-reset-b').addEventListener('click',()=>resetNotebookViewpointPicker());document.getElementById('grade-close').addEventListener('click',closeDialog);
    document.getElementById('notebook-grade-form').addEventListener('submit',async event=>{event.preventDefault();await saveNotebookGrades(studentId,readNotebookViewpointGrades());closeDialog();showToast('3観点の評価を更新しました');renderNotebook();});
    document.querySelectorAll('[data-status]').forEach(button=>button.addEventListener('click',async()=>{await saveNotebookGrades(studentId,readNotebookViewpointGrades(),button.dataset.status);closeDialog();showToast(button.dataset.status==='absent'?'欠席にしました':'未提出にしました');renderNotebook();}));
  }

  async function saveNotebookGrades(studentId,viewpointGrades,status='evaluated'){
    const classItem=selectedClass();const draft=notebookDraft();const sessionKey=notebookSessionKey(draft);const id=`notebook_${classItem.id}_${sessionKey}_${studentId}`;const current=await ClassDB.get('records',id);
    const grades={...NOTEBOOK_DEFAULT_GRADES,...viewpointGrades},grade=status==='evaluated'?notebookOverallGrade(grades):null;
    await ClassDB.put('records',{...(current||{}),id,type:'notebookAssessment',classId:classItem.id,studentId,date:draft.date,subject:draft.subject,unit:draft.unit,title:draft.title||slashDate(draft.date),sessionKey,grade,viewpointGrades:grades,status});
  }

  async function weeklyData(classId){
    let records=(await ClassDB.getAllByIndex('records','classId',classId)).filter(item=>!item.deletedAt);
    const allOccurrences=records.filter(item=>item.type==='weeklyOccurrence'),allSubmissions=records.filter(item=>item.type==='weeklySubmission'),weekEnd=moveDate(currentWeekStart(),6);
    const series=new Map();
    allOccurrences.filter(item=>item.recurring&&item.seriesId&&item.seriesActive!==false).forEach(item=>{if(!series.has(item.seriesId))series.set(item.seriesId,[]);series.get(item.seriesId).push(item);});
    let pruned=false;
    for(const items of series.values()){
      const hasStarted=items.some(item=>item.dueDate<=weekEnd);if(!hasStarted)continue;
      for(const item of items.filter(row=>row.dueDate>weekEnd&&!allSubmissions.some(submission=>submission.occurrenceId===row.id))){await ClassDB.remove('records',item.id);pruned=true;}
    }
    if(pruned)records=(await ClassDB.getAllByIndex('records','classId',classId)).filter(item=>!item.deletedAt);
    const occurrences=records.filter(item=>item.type==='weeklyOccurrence'&&item.dueDate<=moveDate(currentWeekStart(),6)).sort((a,b)=>b.dueDate.localeCompare(a.dueDate));
    const submissions=records.filter(item=>item.type==='weeklySubmission');
    const skippedWeeks=await ClassDB.getMeta('weeklySkippedWeeks',[]);
    return{classId,occurrences,submissions,skippedWeeks:Array.isArray(skippedWeeks)?skippedWeeks:[]};
  }

  function missingRecurringWeeks(data){
    const week=currentWeekStart(),latestBySeries=new Map();
    data.occurrences.filter(item=>item.recurring&&item.seriesId&&item.seriesActive!==false).forEach(item=>{const current=latestBySeries.get(item.seriesId);if(!current||item.dueDate>current.dueDate)latestBySeries.set(item.seriesId,item);});
    return[...latestBySeries.values()].filter(item=>!data.occurrences.some(row=>row.seriesId===item.seriesId&&mondayOf(row.dueDate)===week)&&!data.skippedWeeks.includes(`${data.classId}|${item.seriesId}|${week}`));
  }

  function currentWeeklyOccurrences(data,week=currentWeekStart()){return data.occurrences.filter(item=>mondayOf(item.dueDate)===week);}

  let weeklyCreationQueue=Promise.resolve();
  function createCurrentWeeklyOccurrences(items){
    const targetClass=selectedClass();if(!targetClass)return Promise.resolve(null);const operation=weeklyCreationQueue.catch(()=>{}).then(async()=>{const week=currentWeekStart(),weekEnd=moveDate(week,6),records=(await ClassDB.getAllByIndex('records','classId',targetClass.id)).filter(item=>item.type==='weeklyOccurrence'&&!item.deletedAt),seenSeries=new Set(),sources=items.filter(item=>item.seriesId&&!seenSeries.has(item.seriesId)&&seenSeries.add(item.seriesId));let first=null;
      for(const source of sources){const existing=records.find(item=>item.seriesId===source.seriesId&&item.dueDate>=week&&item.dueDate<=weekEnd);if(existing){if(!first)first=existing;continue;}const offset=Math.max(0,Math.min(6,daysBetween(source.dueDate,source.weekStart||mondayOf(source.dueDate))));const dueDate=moveDate(week,offset),saved=await ClassDB.put('records',{id:`weeklyOccurrence_${targetClass.id}_${source.seriesId}_${week}`,type:'weeklyOccurrence',classId:targetClass.id,studentId:null,date:dueDate,dueDate,weekStart:week,title:source.title,seriesId:source.seriesId,recurring:true,seriesActive:true});records.push(saved);if(!first)first=saved;}
      if(first)state.toolDraft.weekly={occurrenceId:first.id,dueDate:first.dueDate,title:first.title};return first;});weeklyCreationQueue=operation;return operation;
  }

  function weeklyRenewalNotice(items,mode){if(!items.length)return'';return`<div class="notice weekly-renewal"><div><strong>今週分がまだ作成されていません</strong><div class="row-meta">${esc(items.map(item=>item.title).join('・'))}を今週も使う場合は作成してください。</div></div><button type="button" class="button primary" data-create-current-week data-create-mode="${mode}">今週分を作る</button></div>`;}

  function wireWeeklyRenewal(items,mode,afterCreate){document.querySelector('[data-create-current-week]')?.addEventListener('click',event=>{const button=event.currentTarget;if(button.disabled)return;button.disabled=true;const create=async()=>{try{await createCurrentWeeklyOccurrences(items);showToast('今週分の宿題を作成しました');await afterCreate();}catch(error){button.disabled=false;showToast(error.message||'今週分を作成できませんでした');}};if(mode==='pupil')requireTeacher(create);else create();});}

  async function maybePromptWeeklyCreation(mode='teacher'){
    const classItem=selectedClass();if(!classItem)return;const data=await weeklyData(classItem.id),missing=missingRecurringWeeks(data);if(!missing.length)return;
    const key=`${classItem.id}|${currentWeekStart()}|${mode}`;if(state.weeklyPromptShown.has(key))return;state.weeklyPromptShown.add(key);
    openDialog(`<h2>今週の新しい宿題を作りますか？</h2><p>${esc(missing.map(item=>item.title).join('・'))}が「毎週」に設定されています。</p><p class="muted">作成すると、今週の提出状況を新しく記録できます。今は閉じても、週宿題画面から作成できます。</p><div class="dialog-actions"><button type="button" class="button" id="weekly-renew-later">今は作らない</button><button type="button" class="button primary" id="weekly-renew-create">今週分を作る</button></div>`);
    document.getElementById('weekly-renew-later').addEventListener('click',closeDialog);
    document.getElementById('weekly-renew-create').addEventListener('click',event=>{const button=event.currentTarget;if(button.disabled)return;button.disabled=true;const create=async()=>{try{await createCurrentWeeklyOccurrences(missing);closeDialog();showToast('今週分の宿題を作成しました');if(mode==='pupil')renderPupil('all');else renderHome();}catch(error){button.disabled=false;showToast(error.message||'今週分を作成できませんでした');}};if(mode==='pupil'){closeDialog();requireTeacher(create);}else create();});
  }

  async function renderWeekly(){
    if(!teacherActive()){renderPupil();return;}
    state.route='teacher-weekly';state.activeTool='weekly';
    const classItem=selectedClass();applyClassTheme(classItem);const data=await weeklyData(classItem.id);const missingRecurring=missingRecurringWeeks(data);
    let draft=state.toolDraft.weekly;
    if(!draft){const latest=data.occurrences[0];draft=state.toolDraft.weekly={occurrenceId:latest?.id||null,dueDate:latest?.dueDate||today(),title:latest?.title||'自主学習'};}
    let occurrence=data.occurrences.find(item=>item.id===draft.occurrenceId)||null;
    if(!occurrence&&data.occurrences.length){occurrence=data.occurrences[0];draft.occurrenceId=occurrence.id;draft.dueDate=occurrence.dueDate;draft.title=occurrence.title;}
    const currentSubmissions=occurrence?data.submissions.filter(item=>item.occurrenceId===occurrence.id):[];
    const missingByStudent=new Map();
    const dueOccurrences=data.occurrences.filter(item=>mondayOf(item.dueDate)===currentWeekStart()&&item.dueDate<=today());
    const roster=await rosterForClass(classItem.id,false,occurrence?.dueDate||today());
    roster.forEach(row=>{const missing=dueOccurrences.filter(week=>!data.submissions.some(item=>item.studentId===row.student.id&&item.occurrenceId===week.id&&item.status==='submitted'));missingByStudent.set(row.student.id,missing);});
    const cards=await teacherRosterCards(classItem.id,currentSubmissions,{orderMode:teacherOrderMode(),preserveSeatShape:true,atDate:occurrence?.dueDate||today(),status:(record,row)=>{const missing=missingByStudent.get(row.student.id);const missed=missing.length;const maxAge=missing.length?Math.max(...missing.map(item=>Math.floor((new Date(today())-new Date(item.dueDate))/86400000))):0;if(record?.status==='submitted')return missed?`提出済み・過去未提出 ${missed}週`:'提出済み';if(record?.status==='forgotten')return'忘れた';if(missed>=2)return`${missed}週未提出`;if(maxAge>=7)return'7日以上未提出';if(maxAge>=5)return'5日以上未提出';if(occurrence?.dueDate<today())return'未提出';return missed?'過去分未提出':'未提出';},statusClass:(record,row)=>{const missing=missingByStudent.get(row.student.id);const maxAge=missing.length?Math.max(...missing.map(item=>Math.floor((new Date(today())-new Date(item.dueDate))/86400000))):0;if(record?.status==='forgotten'||missing.length>=2||maxAge>=7)return'alert';if(maxAge>=5)return'warn';return record?.status==='submitted'?'good':'';}});
    app.innerHTML=teacherToolShell('週宿題',`${weeklyRenewalNotice(missingRecurring,'teacher')}<section class="panel"><div class="toolbar-line"><div><h1>${esc(classItem.name)}の週宿題</h1><p class="muted">今週の宿題を選び、児童名を押して記録します。</p></div>${teacherOrderControlHtml()}</div>${operationTipHtml('押し方と週の扱いを見る','押すたびに、提出 → 忘れた → 未提出の順で変わります。毎週の宿題は、月曜日以降に今週分だけ作成します。')}<div class="weekly-heading"><div class="field"><label for="weekly-select">表示する宿題・週</label><select class="select" id="weekly-select">${data.occurrences.map(item=>`<option value="${item.id}" ${item.id===occurrence?.id?'selected':''}>${esc(shortJpDate(item.dueDate))}　${esc(item.title)}</option>`).join('')}</select></div><button type="button" class="button primary" id="weekly-create">＋ 新しい宿題を作る</button></div>${occurrence?`<p class="current-item"><strong>${esc(occurrence.title)}</strong>　提出予定 ${esc(jpDate(occurrence.dueDate))}${occurrence.recurring?'　・毎週繰り返し':''}</p>`:'<div class="empty-state"><h2>週宿題はまだありません</h2><p>「＋ 新しい宿題を作る」から最初の宿題を登録してください。</p></div>'}<p class="muted small">過去週の提出状況は、児童カードの「詳細」から確認できます。予定日から5日で黄色、7日で赤の目安です。</p></section>${occurrence?cards:''}`);
    if(occurrence){const currentItem=document.querySelector('.current-item');if(occurrence.seriesActive===false)currentItem.innerHTML=currentItem.innerHTML.replace('毎週繰り返し','毎週繰り返し（終了）');currentItem.classList.add('weekly-current-item');currentItem.insertAdjacentHTML('beforeend',`<button type="button" class="button" id="weekly-manage">過去の宿題を整理</button><button type="button" class="button danger subtle" id="weekly-delete">この宿題を削除</button>`);}
    wireToolHome();wireStudentDetails();wireTeacherOrder(renderWeekly);
    document.getElementById('weekly-select')?.addEventListener('change',event=>{const selected=data.occurrences.find(item=>item.id===event.target.value);state.toolDraft.weekly={occurrenceId:selected.id,dueDate:selected.dueDate,title:selected.title};renderWeekly();});
    document.getElementById('weekly-create').addEventListener('click',openWeeklyCreator);
    document.getElementById('weekly-manage')?.addEventListener('click',()=>openWeeklyManager(data));
    document.getElementById('weekly-delete')?.addEventListener('click',()=>confirmWeeklyDeletion(occurrence,data));
    wireWeeklyRenewal(missingRecurring,'teacher',renderWeekly);
    document.querySelectorAll('[data-tool-student]').forEach(button=>button.addEventListener('click',()=>handleTeacherWeeklyTap(button.dataset.toolStudent,occurrence)));
  }

  function mondayOf(value){const date=new Date(`${value}T00:00:00`),day=(date.getDay()+6)%7;date.setDate(date.getDate()-day);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
  function openWeeklyCreator(){const week=currentWeekStart(),weekEnd=moveDate(week,6);openDialog(`<h2>新しい宿題を作る</h2><form id="weekly-create-form"><div class="field"><label for="weekly-new-title">宿題名</label><input class="input" id="weekly-new-title" value="自主学習" required autofocus></div><div class="field section"><label for="weekly-new-date">今週の提出予定日</label><input class="input" id="weekly-new-date" type="date" value="${today()}" min="${week}" max="${weekEnd}" required><span class="muted small">${esc(shortJpDate(week))}から${esc(shortJpDate(weekEnd))}までを選べます。</span></div><label class="check-row"><input type="checkbox" id="weekly-recurring" checked> 毎週の宿題として、次週以降も確認する</label><p class="muted small">年度末まで先に作ることはありません。次の月曜日以降、今週分を作るか確認します。チェックを外すと今週限りです。</p><p class="error" id="weekly-create-error"></p><div class="dialog-actions"><button type="button" class="button" id="weekly-create-cancel">キャンセル</button><button type="submit" class="button primary" id="weekly-create-submit">作成する</button></div></form>`);document.getElementById('weekly-create-cancel').addEventListener('click',closeDialog);let saving=false;document.getElementById('weekly-create-form').addEventListener('submit',async event=>{event.preventDefault();if(saving)return;const title=document.getElementById('weekly-new-title').value.trim(),dueDate=document.getElementById('weekly-new-date').value,recurring=document.getElementById('weekly-recurring').checked,error=document.getElementById('weekly-create-error');if(!title||!dueDate)return;if(dueDate<week||dueDate>weekEnd){error.textContent='提出予定日は今週の月曜日から日曜日の間で選んでください。';return;}const records=await ClassDB.getAllByIndex('records','classId',selectedClass().id),duplicate=records.some(item=>item.type==='weeklyOccurrence'&&!item.deletedAt&&mondayOf(item.dueDate)===week&&item.title.trim()===title);if(duplicate){error.textContent='今週に同じ名前の宿題があります。表示する宿題・週から確認してください。';return;}saving=true;document.getElementById('weekly-create-submit').disabled=true;try{const seriesId=ClassDB.uid('weeklySeries'),first=await ClassDB.put('records',{id:ClassDB.uid('weeklyOccurrence'),type:'weeklyOccurrence',classId:selectedClass().id,studentId:null,date:dueDate,dueDate,weekStart:week,title,seriesId,recurring,seriesActive:recurring});state.toolDraft.weekly={occurrenceId:first.id,dueDate:first.dueDate,title};closeDialog();showToast(recurring?'毎週の宿題として登録しました':'今週限りの宿題を作成しました');renderWeekly();}catch(saveError){saving=false;document.getElementById('weekly-create-submit').disabled=false;error.textContent=saveError.message||'宿題を保存できませんでした。';}});}

  function confirmWeeklyDeletion(occurrence,data){
    if(!occurrence)return;const submissionCount=data.submissions.filter(item=>item.occurrenceId===occurrence.id).length,seriesActive=occurrence.recurring&&occurrence.seriesId&&occurrence.seriesActive!==false;
    openDialog(`<h2>この週の宿題を削除しますか</h2><p><strong>${esc(occurrence.title)}</strong>（${esc(jpDate(occurrence.dueDate))}）を削除します。</p><p class="muted">児童の提出記録 ${submissionCount}件も一緒に30日間ごみ箱へ移します。</p>${seriesActive?'<p class="notice small">毎週繰り返す宿題です。この週だけ削除するか、今後の繰り返しも終了するか選んでください。</p>':''}<div class="dialog-actions"><button type="button" class="button" id="weekly-delete-cancel">キャンセル</button><button type="button" class="button danger" id="weekly-delete-once">${seriesActive?'この週だけ削除':'削除する'}</button>${seriesActive?'<button type="button" class="button danger" id="weekly-delete-series">削除して繰り返しも終了</button>':''}</div>`);
    document.getElementById('weekly-delete-cancel').addEventListener('click',closeDialog);document.getElementById('weekly-delete-once').addEventListener('click',()=>deleteWeeklyOccurrence(occurrence,false));document.getElementById('weekly-delete-series')?.addEventListener('click',()=>deleteWeeklyOccurrence(occurrence,true));
  }

  function openWeeklyManager(data){openDialog(`<h2>過去の宿題を整理</h2><p class="muted">間違えて作った宿題や、表示が不要になった過去の宿題を選んで削除できます。</p><div class="list weekly-manage-list">${data.occurrences.map(item=>{const count=data.submissions.filter(row=>row.occurrenceId===item.id).length;return`<div class="list-row"><div><strong>${esc(item.title)}</strong><div class="row-meta">${esc(jpDate(item.dueDate))}・提出記録 ${count}件${item.recurring?`・毎週${item.seriesActive===false?'（終了）':''}`:''}</div></div><button type="button" class="button danger subtle" data-manage-weekly-delete="${item.id}">削除</button></div>`;}).join('')||'<p class="empty-state">登録済みの宿題はありません。</p>'}</div><div class="dialog-actions"><button type="button" class="button primary" id="weekly-manager-close">閉じる</button></div>`);document.getElementById('weekly-manager-close').addEventListener('click',closeDialog);document.querySelectorAll('[data-manage-weekly-delete]').forEach(button=>button.addEventListener('click',()=>{const item=data.occurrences.find(row=>row.id===button.dataset.manageWeeklyDelete);closeDialog();confirmWeeklyDeletion(item,data);}));}

  async function deleteWeeklyOccurrence(occurrence,stopSeries){
    const classId=occurrence.classId,records=(await ClassDB.getAllByIndex('records','classId',classId)).filter(item=>!item.deletedAt),submissions=records.filter(item=>item.type==='weeklySubmission'&&item.occurrenceId===occurrence.id),removed=[occurrence,...submissions],timestamp=ClassDB.now(),deviceId=ClassDB.deviceId(),puts={trash:removed.map(trashEntryFor)},deletes={records:removed.map(item=>item.id)},seriesOriginals=stopSeries&&occurrence.seriesId?records.filter(item=>item.type==='weeklyOccurrence'&&item.seriesId===occurrence.seriesId&&item.id!==occurrence.id):[],priorSkipped=await ClassDB.getMeta('weeklySkippedWeeks',[]),skipChanged=!stopSeries&&occurrence.recurring&&occurrence.seriesId&&occurrence.seriesActive!==false;
    if(seriesOriginals.length)puts.records=seriesOriginals.map(item=>({...item,seriesActive:false,updatedAt:timestamp,deviceId}));
    if(skipChanged){const key=`${classId}|${occurrence.seriesId}|${mondayOf(occurrence.dueDate)}`,value=[...new Set([...(Array.isArray(priorSkipped)?priorSkipped:[]),key])];puts.meta=[{key:'weeklySkippedWeeks',value,updatedAt:timestamp,deviceId}];}
    await ClassDB.applyBatch({puts,deletes});state.toolDraft.weekly=null;closeDialog();await renderWeekly();showUndoToast(stopSeries?'週宿題を削除し、繰り返しを終了しました':'この週の宿題を削除しました',async()=>{const restoredAt=ClassDB.now(),restoredDevice=ClassDB.deviceId(),undoPuts={records:[...removed,...seriesOriginals].map(item=>({...item,updatedAt:restoredAt,deviceId:restoredDevice}))};if(skipChanged)undoPuts.meta=[{key:'weeklySkippedWeeks',value:Array.isArray(priorSkipped)?priorSkipped:[],updatedAt:restoredAt,deviceId:restoredDevice}];await ClassDB.applyBatch({puts:undoPuts,deletes:{trash:removed.map(item=>`trash_${item.id}`)}});state.toolDraft.weekly={occurrenceId:occurrence.id,dueDate:occurrence.dueDate,title:occurrence.title};renderWeekly();});
  }
  const weeklyTapQueues=new Map();
  function applyWeeklyTap(studentId,occurrence,afterRender){if(!occurrence)return Promise.resolve();const id=`weekly_${occurrence.id}_${studentId}`,classId=occurrence.classId||selectedClass()?.id,previous=weeklyTapQueues.get(id)||Promise.resolve(),operation=previous.catch(()=>{}).then(async()=>{const current=await ClassDB.get('records',id),next=current?.status==='submitted'?'forgotten':current?.status==='forgotten'?'unsubmitted':'submitted';await ClassDB.put('records',{...(current||{}),id,type:'weeklySubmission',classId,studentId,date:occurrence.dueDate,dueDate:occurrence.dueDate,title:occurrence.title,occurrenceId:occurrence.id,status:next});markFeedback(studentId,next);showToast(next==='submitted'?'提出にしました':next==='forgotten'?'忘れたにしました':'未提出に戻しました');await afterRender();return next;}).finally(()=>{if(weeklyTapQueues.get(id)===operation)weeklyTapQueues.delete(id);});weeklyTapQueues.set(id,operation);return operation;}
  function handleTeacherWeeklyTap(studentId,occurrence){return applyWeeklyTap(studentId,occurrence,renderWeekly);}

  async function openWeeklyStudent(studentId){
    const classItem=selectedClass();const student=await ClassDB.get('students',studentId);const data=await weeklyData(classItem.id);
    const checked=new Set(data.submissions.filter(item=>item.studentId===studentId&&item.status==='submitted').map(item=>item.occurrenceId));
    openDialog(`<h2>${esc(student.name)}の週宿題</h2><p class="muted">提出された週を選びます。選択を外して保存すると、提出済みを取り消せます。</p><form id="weekly-student-form"><div class="list">${data.occurrences.map(item=>{const age=Math.floor((new Date(today())-new Date(item.dueDate))/86400000);const warning=!checked.has(item.id)&&age>=7?'・7日以上':!checked.has(item.id)&&age>=5?'・5日以上':'';return`<label class="list-row"><span><strong>${esc(jpDate(item.dueDate))}</strong><span class="row-meta">${esc(item.title)}${warning}</span></span><input type="checkbox" data-occurrence="${item.id}" ${checked.has(item.id)?'checked':''}></label>`;}).join('')||'<p>登録済みの週がありません。</p>'}</div><div class="dialog-actions"><button type="button" class="button" id="weekly-student-close">閉じる</button><button type="submit" class="button primary">保存</button></div></form>`);
    document.getElementById('weekly-student-close').addEventListener('click',closeDialog);
    document.getElementById('weekly-student-form').addEventListener('submit',async event=>{event.preventDefault();const selected=new Set([...document.querySelectorAll('[data-occurrence]:checked')].map(item=>item.dataset.occurrence));for(const occurrence of data.occurrences){const id=`weekly_${occurrence.id}_${studentId}`;const existing=await ClassDB.get('records',id);if(selected.has(occurrence.id))await ClassDB.put('records',{...(existing||{}),id,type:'weeklySubmission',classId:classItem.id,studentId,date:occurrence.dueDate,dueDate:occurrence.dueDate,title:occurrence.title,occurrenceId:occurrence.id,status:'submitted'});else if(existing?.status==='submitted')await ClassDB.put('records',{...existing,status:'unsubmitted'});}closeDialog();showToast('週宿題を更新しました');renderWeekly();});
  }

  async function occasionalData(classId){
    const records=(await ClassDB.getAllByIndex('records','classId',classId)).filter(item=>!item.deletedAt);
    return{items:records.filter(item=>item.type==='occasionalItem').sort((a,b)=>(a.archived-b.archived)||b.dueDate.localeCompare(a.dueDate)),submissions:records.filter(item=>item.type==='occasionalSubmission')};
  }

  async function renderOccasional(){
    if(!teacherActive()){renderPupil();return;}
    state.route='teacher-occasional';state.activeTool='occasional';
    const classItem=selectedClass();applyClassTheme(classItem);const data=await occasionalData(classItem.id);
    let selectedId=state.toolDraft.occasionalId;
    if(!data.items.some(item=>item.id===selectedId))selectedId=data.items.find(item=>!item.archived)?.id||data.items[0]?.id||null;
    state.toolDraft.occasionalId=selectedId;const item=data.items.find(row=>row.id===selectedId)||null;
    const submissions=item?data.submissions.filter(row=>row.itemId===item.id):[];const roster=await rosterForClass(classItem.id,false,item?.dueDate||today());const itemCards=data.items.map(row=>{const submitted=new Set(data.submissions.filter(record=>record.itemId===row.id&&record.status==='submitted').map(record=>record.studentId)).size;return`<button type="button" class="submission-item-card ${row.id===item?.id?'active':''}" data-occasional-item="${row.id}" title="${esc(row.title)}の提出状況を開く"><span>${row.archived?'完結':'対応中'}</span><strong>${esc(row.title)}</strong><small>${esc(shortJpDate(row.dueDate))}・未提出 ${Math.max(0,roster.length-submitted)}人</small></button>`;}).join('');
    const cards=await teacherRosterCards(classItem.id,submissions,{orderMode:teacherOrderMode(),preserveSeatShape:true,atDate:item?.dueDate||today(),status:record=>record?.status==='submitted'?'提出済み':'未提出',statusClass:record=>record?.status==='submitted'?'good':'alert'});
    app.innerHTML=teacherToolShell('提出物',`<section class="panel"><div class="toolbar-line"><div><h1>${esc(classItem.name)}の提出物</h1><p class="muted">集める書類などを登録し、提出状況を確認します。</p></div><button type="button" class="button primary" id="occasional-create">＋ 新しい提出物を作る</button></div><div class="submission-item-list section">${itemCards||'<div class="empty-state"><h2>提出物はまだありません</h2><p>右上の「＋ 新しい提出物を作る」から登録してください。</p></div>'}</div></section>${item?`<section class="panel"><p class="current-item"><strong>${esc(item.title)}</strong>　提出予定 ${esc(jpDate(item.dueDate))}・${item.archived?'回収終了':'回収中'}</p><div class="toolbar-line section"><p class="muted small">児童名を押して提出済みにします。</p><div class="button-row"><button type="button" class="button" id="occasional-edit">内容を編集</button><button type="button" class="button" id="occasional-archive">${item.archived?'回収を再開する':'回収を終える'}</button>${teacherOrderControlHtml()}</div></div></section>${cards}`:''}`);
    wireToolHome();wireStudentDetails();wireTeacherOrder(renderOccasional);
    document.querySelectorAll('[data-occasional-item]').forEach(button=>button.addEventListener('click',()=>{state.toolDraft.occasionalId=button.dataset.occasionalItem;renderOccasional();}));
    document.getElementById('occasional-create').addEventListener('click',()=>openOccasionalEditor());document.getElementById('occasional-edit')?.addEventListener('click',()=>openOccasionalEditor(item));
    document.getElementById('occasional-archive')?.addEventListener('click',async()=>{await ClassDB.put('records',{...item,archived:!item.archived});showToast(item.archived?'提出物の回収を再開しました':'提出物の回収を終了しました');renderOccasional();});
    document.querySelectorAll('[data-tool-student]').forEach(button=>button.addEventListener('click',()=>toggleOccasionalStudent(button.dataset.toolStudent,item)));
  }

  function openOccasionalEditor(item=null){openDialog(`<h2>${item?'提出物を編集':'新しい提出物を作る'}</h2><form id="occasional-form"><div class="field"><label for="occasional-title">提出物名</label><input class="input" id="occasional-title" value="${esc(item?.title||'')}" placeholder="例：同意書" required autofocus></div><div class="field section"><label for="occasional-date">提出予定日</label><input class="input" id="occasional-date" type="date" value="${item?.dueDate||today()}" required></div><label class="check-row"><input type="checkbox" id="occasional-continue" ${item?.continueDisplay!==false?'checked':''}> 未提出者がいる間は翌日以降も表示する</label><p class="error" id="occasional-error"></p><div class="dialog-actions"><button type="button" class="button" id="occasional-cancel">キャンセル</button><button type="submit" class="button primary">保存して表示</button></div></form>`);document.getElementById('occasional-cancel').addEventListener('click',closeDialog);document.getElementById('occasional-form').addEventListener('submit',async event=>{event.preventDefault();const dueDate=document.getElementById('occasional-date').value,title=document.getElementById('occasional-title').value.trim();if(!dueDate||!title)return;const saved=await ClassDB.put('records',{...(item||{}),id:item?.id||ClassDB.uid('occasionalItem'),type:'occasionalItem',classId:selectedClass().id,studentId:null,date:dueDate,dueDate,title,continueDisplay:document.getElementById('occasional-continue').checked,archived:item?.archived||false});state.toolDraft.occasionalId=saved.id;closeDialog();showToast('提出物を保存しました');renderOccasional();});}

  async function toggleOccasionalStudent(studentId,item){
    if(!item||item.archived)return;
    const id=`occasional_${item.id}_${studentId}`;const existing=await ClassDB.get('records',id);
    if(!existing||existing.status!=='submitted'){await ClassDB.put('records',{...(existing||{}),id,type:'occasionalSubmission',classId:selectedClass().id,studentId,date:today(),dueDate:item.dueDate,title:item.title,itemId:item.id,status:'submitted'});markFeedback(studentId,'submitted');showToast('提出済みにしました');renderOccasional();return;}
    const student=await ClassDB.get('students',studentId);
    openDialog(`<h2>提出済みを取り消しますか</h2><p>${esc(student.name)}の「${esc(item.title)}」を未提出へ戻します。</p><div class="dialog-actions"><button type="button" class="button" id="occasional-cancel">戻る</button><button type="button" class="button danger" id="occasional-confirm">提出を取り消す</button></div>`);
    document.getElementById('occasional-cancel').addEventListener('click',closeDialog);
    document.getElementById('occasional-confirm').addEventListener('click',async()=>{await ClassDB.put('records',{...existing,status:'unsubmitted'});markFeedback(studentId,'unsubmitted');closeDialog();showToast('未提出へ戻しました');renderOccasional();});
  }

  async function supportUnits(classId,subject){
    const records=(await ClassDB.getAllByIndex('records','classId',classId)).filter(item=>item.type==='currentUnit'&&item.subject===subject&&!item.deletedAt);
    return records.sort((a,b)=>(a.order||0)-(b.order||0));
  }

  async function ensureSupportUnits(classId,subject){
    let units=await supportUnits(classId,subject);if(units.length)return units;
    const roster=await rosterForClass(classId);const date=today(),memberIds=roster.map(row=>row.student.id);await ClassDB.put('records',{id:ClassDB.uid('currentUnit'),type:'currentUnit',classId,studentId:null,date,subject,name:'単元未設定',memberIds,history:[{date,name:'単元未設定',memberIds}],order:0});
    return supportUnits(classId,subject);
  }

  function unitsAtDate(units,date){
    return units.map(unit=>{const history=(unit.history||[]).filter(item=>!item.date||item.date<=date).sort((a,b)=>(a.date||'').localeCompare(b.date||''));const snapshot=history.at(-1);return snapshot?{...unit,name:snapshot.name,memberIds:[...(snapshot.memberIds||[])]}:unit;});
  }

  function supportDraft(){return state.toolDraft.support||(state.toolDraft.support={date:today(),subject:'国語'});}

  async function renderSupport(){
    if(!teacherActive()){renderPupil();return;}const classItem=selectedClass();if(!isSupportClass(classItem)){showToast('クラス設定で「個別支援級にする」を選ぶと使用できます');renderHome();return;}
    state.route='teacher-support';state.activeTool='support';applyClassTheme(classItem);const draft=supportDraft();const subjects=classSubjects(classItem);if(!subjects.includes(draft.subject))draft.subject=subjects[0];const roster=await rosterForClass(classItem.id);const currentUnits=await ensureSupportUnits(classItem.id,draft.subject);const units=unitsAtDate(currentUnits,draft.date);
    const termStart=draft.date<=state.year.firstTermEnd?state.year.startDate:moveDate(state.year.firstTermEnd,1);const termEnd=draft.date<=state.year.firstTermEnd?state.year.firstTermEnd:state.year.endDate;const allRecords=await ClassDB.getAllByIndex('records','classId',classItem.id);const subjectRecords=allRecords.filter(item=>item.type==='supportRecord'&&item.subject===draft.subject&&item.date>=termStart&&item.date<=termEnd&&!item.deletedAt);const eligibleRoster=roster.filter(row=>studentSupportSubjects(row,classItem).includes(draft.subject));const counts=new Map(eligibleRoster.map(row=>[row.student.id,subjectRecords.filter(item=>item.studentId===row.student.id).length]));const average=eligibleRoster.length?[...counts.values()].reduce((sum,value)=>sum+value,0)/eligibleRoster.length:0;
    const unitForStudent=studentId=>units.find(unit=>(unit.memberIds||[]).includes(studentId));
    const supportButton=row=>{const count=counts.get(row.student.id)||0;const level=count===0?'none':count<=2?'very-low':average>0&&count<average*.7?'low':'';const label=count===0?'記録なし':count<=2?'かなり少ない':level==='low'?'やや少なめ':`${count}件`;return`<button type="button" class="${level}" data-support-student="${row.student.id}">${esc(row.student.name)}<span>${label}</span></button>`;};
    const groups=units.map(unit=>`<section class="support-unit"><span class="unit-kicker">現在の単元</span><h2>${esc(unit.name)}</h2><div class="support-pupils">${eligibleRoster.filter(row=>(unit.memberIds||[]).includes(row.student.id)).map(supportButton).join('')||'<span class="muted">児童なし</span>'}</div></section>`).join('');
    const unassigned=eligibleRoster.filter(row=>!unitForStudent(row.student.id));
    app.innerHTML=teacherToolShell('学習記録',`${pupilDateNav(draft.date,'support-prev','support-next')}<section class="panel"><div class="button-row" style="justify-content:space-between"><div><h1>${esc(classItem.name)}の学習記録</h1><p class="muted">教科を選び、記録したい児童を押します。同じ単元の児童はまとまって表示されます。</p></div><button type="button" class="button" id="edit-units">学習するまとまりを変更</button></div><div class="field" style="max-width:260px"><label for="support-subject">記録する教科</label><select class="select" id="support-subject">${subjects.map(subject=>`<option ${subject===draft.subject?'selected':''}>${subject}</option>`).join('')}</select></div></section><div class="support-unit-grid">${groups}${unassigned.length?`<section class="support-unit alert"><span class="unit-kicker">確認が必要</span><h2>現在の単元が未設定</h2><div class="support-pupils">${unassigned.map(supportButton).join('')}</div></section>`:''}</div>`);
    wireToolHome();document.getElementById('support-prev').addEventListener('click',()=>{draft.date=moveDate(draft.date,-1);renderSupport();});document.getElementById('support-next').addEventListener('click',()=>{draft.date=moveDate(draft.date,1);renderSupport();});
    document.getElementById('support-subject').addEventListener('change',event=>{draft.subject=event.target.value;renderSupport();});document.getElementById('edit-units').addEventListener('click',renderUnitManager);
    document.querySelectorAll('[data-support-student]').forEach(button=>button.addEventListener('click',()=>openSupportRecord(button.dataset.supportStudent)));
  }

  async function renderUnitManager(){
    if(!teacherActive()){renderPupil();return;}state.route='teacher-unit-manager';const classItem=selectedClass();const draft=supportDraft();const roster=await rosterForClass(classItem.id);const eligibleRoster=roster.filter(row=>studentSupportSubjects(row,classItem).includes(draft.subject));const units=await ensureSupportUnits(classItem.id,draft.subject);
    const assigned=new Set(units.flatMap(unit=>unit.memberIds||[]));
    app.innerHTML=teacherToolShell('現在の学習単元',`<section class="panel"><div class="button-row" style="justify-content:space-between"><div><h1>${esc(draft.subject)}で学習するまとまり</h1><p class="muted">同じ単元を学ぶ児童を同じ欄へ入れます。児童名を押し、移動先の欄を押してください。PCではドラッグもできます。</p></div><button type="button" class="button primary" id="add-unit">別の単元を追加</button></div></section><div class="unit-board">${units.map(unit=>unitEditorHtml(unit,eligibleRoster)).join('')}<section class="unit-column" data-unit-drop=""><span class="unit-kicker">確認が必要</span><h2>単元未設定</h2><div class="unit-students">${eligibleRoster.filter(row=>!assigned.has(row.student.id)).map(row=>unitStudentHtml(row.student)).join('')||'<span class="muted">児童なし</span>'}</div></section></div><div class="button-row end section"><button type="button" class="button primary" id="units-done">学習記録へ戻る</button></div>`);
    wireToolHome();document.getElementById('units-done').addEventListener('click',renderSupport);document.getElementById('add-unit').addEventListener('click',()=>openUnitEditor());
    document.querySelectorAll('[data-edit-unit]').forEach(button=>button.addEventListener('click',()=>openUnitEditor(units.find(unit=>unit.id===button.dataset.editUnit))));
    let movingStudentId=null;
    document.querySelectorAll('[data-unit-student]').forEach(button=>{button.addEventListener('dragstart',event=>{movingStudentId=button.dataset.unitStudent;event.dataTransfer.setData('text/plain',movingStudentId);});button.addEventListener('click',()=>{movingStudentId=button.dataset.unitStudent;document.querySelectorAll('[data-unit-student]').forEach(item=>item.classList.toggle('selected',item===button));showToast('移動先の単元を選んでください');});});
    document.querySelectorAll('[data-unit-drop]').forEach(column=>{column.addEventListener('dragover',event=>event.preventDefault());column.addEventListener('drop',async event=>{event.preventDefault();await moveSupportStudent(event.dataTransfer.getData('text/plain')||movingStudentId,column.dataset.unitDrop,units);});column.addEventListener('click',async event=>{if(event.target.closest('[data-unit-student],[data-edit-unit]')||!movingStudentId)return;await moveSupportStudent(movingStudentId,column.dataset.unitDrop,units);});});
  }

  function unitEditorHtml(unit,roster){return `<section class="unit-column" data-unit-drop="${unit.id}"><span class="unit-kicker">現在の単元</span><div class="button-row" style="justify-content:space-between"><h2>${esc(unit.name)}</h2><button type="button" class="detail-button" data-edit-unit="${unit.id}">単元名を編集</button></div><div class="unit-students">${roster.filter(row=>(unit.memberIds||[]).includes(row.student.id)).map(row=>unitStudentHtml(row.student)).join('')||'<span class="muted">児童名を選んで、この欄を押します</span>'}</div></section>`;}
  function unitStudentHtml(student){return `<button type="button" class="unit-student" draggable="true" data-unit-student="${student.id}">${esc(student.name)}</button>`;}
  async function moveSupportStudent(studentId,targetUnitId,units){const date=today();for(const unit of units){const members=(unit.memberIds||[]).filter(id=>id!==studentId);if(unit.id===targetUnitId)members.push(studentId);if(members.length!==(unit.memberIds||[]).length||unit.id===targetUnitId){const history=[...(unit.history||[]),{date,name:unit.name,memberIds:[...new Set(members)]}];await ClassDB.put('records',{...unit,memberIds:[...new Set(members)],history});}}showToast('学習単元を移動しました');renderUnitManager();}

  function openUnitEditor(unit=null){openDialog(`<h2>${unit?'単元名を編集':'現在の学習単元を追加'}</h2><form id="unit-form"><div class="field"><label for="unit-name">単元名</label><input class="input" id="unit-name" value="${esc(unit?.name||'')}" required autofocus></div><div class="dialog-actions"><button type="button" class="button" id="unit-cancel">キャンセル</button><button type="submit" class="button primary">保存</button></div></form>`);document.getElementById('unit-cancel').addEventListener('click',closeDialog);document.getElementById('unit-form').addEventListener('submit',async event=>{event.preventDefault();const draft=supportDraft(),name=document.getElementById('unit-name').value.trim(),date=today(),memberIds=unit?.memberIds||[],history=[...(unit?.history||[]),{date,name,memberIds:[...memberIds]}];await ClassDB.put('records',{...(unit||{}),id:unit?.id||ClassDB.uid('currentUnit'),type:'currentUnit',classId:selectedClass().id,studentId:null,date,subject:draft.subject,name,memberIds,history,order:unit?.order??Date.now()});closeDialog();showToast('単元名を保存しました');renderUnitManager();});}

  async function openSupportRecord(studentId){
    const classItem=selectedClass();const student=await ClassDB.get('students',studentId);const draft=supportDraft();const currentUnits=await ensureSupportUnits(classItem.id,draft.subject);const units=unitsAtDate(currentUnits,draft.date);const unit=units.find(item=>(item.memberIds||[]).includes(studentId));const configured=await ClassDB.getMeta('supportTags',SUPPORT_TAGS);const categories=Object.keys(configured);let selectedCategories=[];let selectedTags={};let activeCategory=null;
    openDialog(`<h2>${esc(student.name)}の記録</h2><p class="muted">${esc(draft.subject)}・${esc(unit?.name||'単元未設定')}・${esc(shortJpDate(draft.date))}</p><form id="support-record-form"><p class="field-label">当てはまる項目</p><div class="tag-list" id="support-categories">${categories.map(category=>`<button type="button" class="tag-chip" data-support-category="${esc(category)}" aria-pressed="false">${esc(category)}</button>`).join('')}</div><div id="support-tags-area" class="section"></div><div class="field section"><label for="support-text">自由記述（任意）</label><textarea class="textarea" id="support-text"></textarea></div><div class="dialog-actions"><button type="button" class="button" id="support-cancel">キャンセル</button><button type="submit" class="button">保存</button><button type="button" class="button primary" id="support-save-next">保存して次の児童</button></div></form>`);
    const renderTags=()=>{const area=document.getElementById('support-tags-area');if(!activeCategory||!selectedCategories.includes(activeCategory)){area.innerHTML='';return;}area.innerHTML=`<p class="field-label">${esc(activeCategory)}のタグ</p><div class="tag-list">${(configured[activeCategory]||[]).map(tag=>`<button type="button" class="tag-chip" data-support-tag="${esc(tag)}" aria-pressed="${selectedTags[activeCategory]?.includes(tag)||false}">${esc(tag)}</button>`).join('')}</div>`;area.querySelectorAll('[data-support-tag]').forEach(button=>button.addEventListener('click',()=>{const list=selectedTags[activeCategory]||(selectedTags[activeCategory]=[]);if(list.includes(button.dataset.supportTag))selectedTags[activeCategory]=list.filter(tag=>tag!==button.dataset.supportTag);else list.push(button.dataset.supportTag);renderTags();}));};
    document.querySelectorAll('[data-support-category]').forEach(button=>button.addEventListener('click',()=>{const category=button.dataset.supportCategory;if(selectedCategories.includes(category)){selectedCategories=selectedCategories.filter(item=>item!==category);button.setAttribute('aria-pressed','false');if(activeCategory===category)activeCategory=selectedCategories.at(-1)||null;}else{selectedCategories.push(category);button.setAttribute('aria-pressed','true');activeCategory=category;}renderTags();}));
    document.getElementById('support-cancel').addEventListener('click',closeDialog);document.getElementById('support-record-form').addEventListener('submit',async event=>{event.preventDefault();await saveSupportRecord(studentId,unit,selectedCategories,selectedTags);closeDialog();renderSupport();});document.getElementById('support-save-next').addEventListener('click',async()=>{await saveSupportRecord(studentId,unit,selectedCategories,selectedTags);const roster=await rosterForClass(classItem.id);const index=roster.findIndex(row=>row.student.id===studentId);closeDialog();if(index<roster.length-1)openSupportRecord(roster[index+1].student.id);else{showToast('最後の児童まで保存しました');renderSupport();}});
  }

  async function saveSupportRecord(studentId,unit,categories,tags){const draft=supportDraft();await ClassDB.put('records',{id:ClassDB.uid('supportRecord'),type:'supportRecord',classId:selectedClass().id,studentId,date:draft.date,subject:draft.subject,unitId:unit?.id||null,unit:unit?.name||'単元未設定',categories,tags,text:document.getElementById('support-text').value.trim()});showToast('学習記録を保存しました');}
