"use strict";

  function currentTermRange(){
    const first=today()<=state.year.firstTermEnd;
    return{label:first?'前期':'後期',start:first?state.year.startDate:moveDate(state.year.firstTermEnd,1),end:first?state.year.firstTermEnd:state.year.endDate};
  }

  async function renderReports(){
    if(!teacherActive()){renderPupil();return;}
    state.route='teacher-reports';state.activeTool='reports';
    const classItem=selectedClass();applyClassTheme(classItem);const term=currentTermRange();
    const all=(await ClassDB.getAllByIndex('records','classId',classItem.id)).filter(item=>['memo','notebookAssessment','supportRecord'].includes(item.type)&&item.date>=term.start&&item.date<=term.end&&!item.deletedAt);
    const cards=await teacherRosterCards(classItem.id,[],{status:(_,row)=>{const count=all.filter(item=>item.studentId===row.student.id).length;return count?`${term.label} ${count}件`:'素材なし';},statusClass:(_,row)=>all.some(item=>item.studentId===row.student.id)?'good':'warn'});
    app.innerHTML=teacherToolShell('所見素材',`<section class="panel"><h1>${esc(classItem.name)}・${term.label}</h1><p class="muted">児童を選ぶと、今学期の児童メモ・ノート評価・学習記録を自動選択します。</p></section>${cards}`);
    wireToolHome();wireStudentDetails();document.querySelectorAll('[data-tool-student]').forEach(button=>button.addEventListener('click',()=>renderReportBuilder(button.dataset.toolStudent)));
  }

  async function renderReportBuilder(studentId){
    if(!teacherActive()){renderPupil();return;}
    state.route='teacher-report-builder';const classItem=selectedClass();const student=await ClassDB.get('students',studentId);if(!student){renderReports();return;}
    const term=currentTermRange();const records=(await ClassDB.getAllByIndex('records','studentId',studentId)).filter(item=>item.classId===classItem.id&&['memo','notebookAssessment','supportRecord'].includes(item.type)&&item.date>=term.start&&item.date<=term.end&&!item.deletedAt).sort((a,b)=>a.date.localeCompare(b.date)||a.updatedAt.localeCompare(b.updatedAt));
    app.innerHTML=teacherToolShell('所見素材',`<div class="button-row" style="justify-content:space-between"><button type="button" class="button" id="reports-back">一覧へ戻る</button><div><h1>${esc(student.name)}</h1><p class="muted">${esc(classItem.name)}・${term.label}</p></div></div><section class="panel section"><div class="button-row" style="justify-content:space-between"><div><h2>使用する記録</h2><p class="muted">すべて選択済みです。不要な記録だけ外してください。</p></div><div class="button-row"><button type="button" class="button" id="report-all">すべて選択</button><button type="button" class="button" id="report-none">すべて外す</button></div></div><div class="report-records">${records.map(reportRecordChoiceHtml).join('')||'<p class="muted">この期間の対象記録はありません。</p>'}</div></section><section class="report-columns section"><div class="panel"><div class="button-row" style="justify-content:space-between"><h2>所見素材</h2><div class="button-row"><button type="button" class="button" data-copy-report="materials">コピー</button><button type="button" class="button" data-save-report="materials">TXT保存</button></div></div><textarea class="textarea report-output" id="report-materials" readonly></textarea></div><div class="panel"><div class="button-row" style="justify-content:space-between"><h2>AI用プロンプト</h2><div class="button-row"><button type="button" class="button" data-copy-report="prompt">コピー</button><button type="button" class="button" data-save-report="prompt">TXT保存</button></div></div><textarea class="textarea report-output" id="report-prompt" readonly></textarea></div></section>`);
    wireToolHome();document.getElementById('reports-back').addEventListener('click',renderReports);
    const refresh=async()=>{const selected=records.filter(record=>document.querySelector(`[data-report-record="${record.id}"]`)?.checked);const materials=buildReportMaterials(selected,student,classItem,term);const template=await ClassDB.getMeta('reportPromptTemplate',defaultReportPrompt());document.getElementById('report-materials').value=materials;document.getElementById('report-prompt').value=fillReportPrompt(template,{name:student.name,className:classItem.name,term:term.label,materials});};
    document.querySelectorAll('[data-report-record]').forEach(input=>input.addEventListener('change',refresh));
    document.getElementById('report-all').addEventListener('click',()=>{document.querySelectorAll('[data-report-record]').forEach(input=>input.checked=true);refresh();});document.getElementById('report-none').addEventListener('click',()=>{document.querySelectorAll('[data-report-record]').forEach(input=>input.checked=false);refresh();});
    document.querySelectorAll('[data-copy-report]').forEach(button=>button.addEventListener('click',async()=>{const area=document.getElementById(button.dataset.copyReport==='materials'?'report-materials':'report-prompt');await copyText(area.value);showToast('コピーしました');}));
    document.querySelectorAll('[data-save-report]').forEach(button=>button.addEventListener('click',()=>{const kind=button.dataset.saveReport;const area=document.getElementById(kind==='materials'?'report-materials':'report-prompt');downloadText(`${student.name}_${term.label}_${kind==='materials'?'所見素材':'AI用プロンプト'}.txt`,area.value);}));
    await refresh();
  }

  function reportRecordChoiceHtml(record){
    const labels={memo:'児童メモ',notebookAssessment:'ノート評価',supportRecord:'学習記録'};let detail='';
    if(record.type==='memo')detail=`${record.subject||'教科なし'}${record.unit?`「${record.unit}」`:''}　${(record.tags||[]).join('・')}${record.text?`　${record.text}`:''}`;
    if(record.type==='notebookAssessment')detail=`${record.subject||''}　${record.unit||''}　${record.title||''}　${notebookViewpointText(record)}${record.note?`　${record.note}`:''}`;
    if(record.type==='supportRecord')detail=`${record.subject||''}　${record.unit||''}　${flattenSupportTags(record).join('・')}${record.text?`　${record.text}`:''}`;
    return `<label class="report-record"><input type="checkbox" data-report-record="${record.id}" checked><span><strong>${esc(shortJpDate(record.date))}　${labels[record.type]}</strong><small>${esc(detail.trim())}</small></span></label>`;
  }

  function flattenSupportTags(record){return Object.values(record.tags||{}).flat().filter(Boolean);}
  function assessmentLabel(record){return notebookViewpointText(record);}
  function buildReportMaterials(records,student,classItem,term){
    const lines=[`${student.name}　${classItem.name}　${term.label} 所見素材`];
    const memos=records.filter(item=>item.type==='memo');
    if(memos.length){lines.push('\n【児童メモ】');memos.forEach(item=>lines.push(`・${slashDate(item.date)} ${item.subject||'教科なし'}${item.unit?`「${item.unit}」`:''}：${[...(item.tags||[]),item.text].filter(Boolean).join('／')}`));}
    const assessments=records.filter(item=>item.type==='notebookAssessment');
    if(assessments.length){lines.push('\n【ノート評価】');const subjects=[...new Set(assessments.map(item=>item.subject||'教科なし'))];subjects.forEach(subject=>{const items=assessments.filter(item=>(item.subject||'教科なし')===subject),evaluated=items.filter(item=>!['absent','unsubmitted'].includes(item.status));const tendency=NOTEBOOK_VIEWPOINTS.map(viewpoint=>{const counts={};for(const item of evaluated){const grade=notebookViewpointGrades(item)[viewpoint.key];counts[grade]=(counts[grade]||0)+1;}return`${viewpoint.label}：${Object.entries(counts).map(([grade,count])=>`${notebookGradeText(grade)} ${count}件`).join('、')||'評価なし'}`;}).join('／');const details=items.map(item=>`${item.unit||'単元未設定'}${item.title?`「${item.title}」`:''}（${assessmentLabel(item)}）${item.note?`［${item.note}］`:''}`).join('、');lines.push(`・${subject}\n  観点別の傾向：${tendency}\n  主な単元・評価：${details}`);});}
    const support=records.filter(item=>item.type==='supportRecord');
    if(support.length){lines.push('\n【学習記録】');support.forEach(item=>{const categories=(item.categories||[]).join('・');const detail=[categories,...flattenSupportTags(item),item.text].filter(Boolean).join('／');lines.push(`・${slashDate(item.date)} ${item.subject||'教科なし'}「${item.unit||'単元未設定'}」：${detail||'記録あり'}`);});}
    if(records.length===0)lines.push('\n（選択された記録はありません）');
    return lines.join('\n');
  }

  function defaultReportPrompt(){return `あなたは小学校の学級担任を支援する文章作成者です。\n以下の所見素材だけを根拠に、{name}の{term}の所見文案を作成してください。\n\n条件：\n・素材にない事実は加えない\n・タグや箇条書きを、自然で具体的な文章にする\n・ノート評価は、知識・技能、思考・判断・表現、主体的に学習に取り組む態度の違いを踏まえる\n・児童のよさ、努力、成長が伝わる肯定的な表現にする\n・同じ語尾の繰り返しを避ける\n・180～220字程度にまとめる\n・完成した所見文だけを出力する\n\n【所属】{class}\n【所見素材】\n{materials}`;}
  function fillReportPrompt(template,data){return String(template).replaceAll('{name}',data.name).replaceAll('{class}',data.className).replaceAll('{term}',data.term).replaceAll('{materials}',data.materials);}
  async function copyText(value){if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(value);return;}const area=document.createElement('textarea');area.value=value;document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();}

  async function renderPromptSettings(){
    const prompt=await ClassDB.getMeta('reportPromptTemplate',defaultReportPrompt());
    document.getElementById('settings-content').innerHTML=`<section class="settings-detail-card"><h1>所見プロンプト設定</h1><p class="muted">全クラス共通です。{name}、{class}、{term}、{materials} は作成時に自動で置き換わります。</p><section class="settings-option-card prompt-token-card" data-card-role="案内"><h2>自動で置き換わる項目</h2><p class="muted small"><code>{name}</code> 児童名　<code>{class}</code> クラス名　<code>{term}</code> 学期　<code>{materials}</code> 選択した記録</p></section><form id="report-prompt-form"><div class="field"><label for="report-prompt-template">AI用プロンプト</label><textarea class="textarea report-output" id="report-prompt-template">${esc(prompt)}</textarea></div><div class="button-row end section"><button type="button" class="button" id="report-prompt-reset">推奨設定に戻す</button><button type="submit" class="button primary">保存</button></div></form></section>`;
    const target=document.getElementById('settings-content');target.insertAdjacentHTML('afterbegin',settingsPageLead('所見の文章設定','所見作成で使う観点や文章の下書きを整えます。','records'));wireSettingsHome(target);
    document.getElementById('report-prompt-reset').addEventListener('click',()=>{document.getElementById('report-prompt-template').value=defaultReportPrompt();});document.getElementById('report-prompt-form').addEventListener('submit',async event=>{event.preventDefault();await ClassDB.setMeta('reportPromptTemplate',document.getElementById('report-prompt-template').value.trim()||defaultReportPrompt());showToast('所見プロンプトを保存しました');});
  }

  async function renderStudentOverview(studentId,tab='summary'){
    if(!teacherActive()){renderPupil();return;}
    if(state.activeTool&&state.activeTool!=='student')state.studentReturnTool=state.activeTool;
    state.route='teacher-student-overview';state.activeTool='student';
    const classItem=selectedClass();applyClassTheme(classItem);const roster=await rosterForClass(classItem.id);const index=roster.findIndex(row=>row.student.id===studentId);const student=await ClassDB.get('students',studentId),periods=await enrollmentPeriodsForStudent(classItem.id,studentId),currentEnrollment=periods.find(item=>!item.endDate)||periods[0];
    if(!student){renderHome();return;}
    const all=(await ClassDB.getAllByIndex('records','studentId',studentId)).filter(item=>item.classId===classItem.id&&!item.deletedAt);
    const termStart=today()<=state.year.firstTermEnd?state.year.startDate:moveDate(state.year.firstTermEnd,1);
    const records=all.filter(item=>item.date>=termStart&&item.date<=state.year.endDate).sort((a,b)=>b.date.localeCompare(a.date)||b.updatedAt.localeCompare(a.updatedAt));
    const memos=records.filter(item=>item.type==='memo');
    const authored=records.filter(item=>['memo','notebookAssessment','certificate','supportRecord'].includes(item.type));
    const certificates=all.filter(item=>item.type==='certificate').sort((a,b)=>b.date.localeCompare(a.date)),certificateDays=certificates[0]?Math.max(0,daysBetween(today(),certificates[0].date)):null;
    const daily=all.filter(item=>item.type==='dailyHomework'&&['forgotten','partialForgotten'].includes(item.status)&&!item.resolvedAt&&dateInEnrollment(item.date,currentEnrollment));
    const weekly=await weeklyData(classItem.id);const weeklyMissing=weekly.occurrences.filter(item=>item.dueDate<today()&&dateInEnrollment(item.dueDate,currentEnrollment)&&!weekly.submissions.some(row=>row.studentId===studentId&&row.occurrenceId===item.id&&row.status==='submitted'));
    const occasional=await occasionalData(classItem.id);const occasionalMissing=occasional.items.filter(item=>!item.archived&&dateInEnrollment(item.dueDate,currentEnrollment)&&!occasional.submissions.some(row=>row.studentId===studentId&&row.itemId===item.id&&row.status==='submitted'));
    const tabs=[['summary','概要'],['memo','メモ'],['assessment','評価'],['certificate','賞状'],['homework','宿題・提出物']];
    const addLabels={memo:'＋ メモを追加',assessment:'＋ ノート評価を追加',certificate:'＋ ミニ賞状を追加',homework:'＋ 提出物を記録'},todayDaily=all.find(item=>item.type==='dailyHomework'&&item.date===today());const unresolvedHtml=daily.map(item=>unresolvedRowHtml('daily',item,'毎日の宿題',item.date)).join('')+weeklyMissing.map(item=>unresolvedRowHtml('weekly',item,item.title,item.dueDate)).join('')+occasionalMissing.map(item=>unresolvedRowHtml('occasional',item,item.title,item.dueDate)).join('');
    let content='';
    if(tab==='summary'){const oldestHomework=[...daily.map(x=>x.date),...weeklyMissing.map(x=>x.dueDate)].sort()[0],oldestSubmission=[...occasionalMissing].sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0];content=`<div class="overview-layout"><section class="overview-stats"><button type="button" class="overview-stat static"><strong>最後の記録</strong><div>${authored[0]?jpDate(authored[0].date):'記録なし'}</div></button><button type="button" class="overview-stat actionable ${(daily.length+weeklyMissing.length)?'needs-action':''}" data-overview-tab="homework"><strong>宿題未解決</strong><div>${daily.length+weeklyMissing.length}件${oldestHomework?`・最古 ${jpDate(oldestHomework)}`:''}</div><span>押して確認・解決 ›</span></button><button type="button" class="overview-stat actionable ${occasionalMissing.length?'needs-action':''}" data-overview-tab="homework"><strong>提出物未解決</strong><div>${occasionalMissing.length}件${oldestSubmission?`・最古 ${jpDate(oldestSubmission.dueDate)}`:''}</div><span>押して確認・解決 ›</span></button><button type="button" class="overview-stat actionable" data-overview-tab="certificate"><strong>ミニ賞状</strong><div>今年度 ${certificates.length}回${certificateDays!==null?`・前回から${certificateDays}日`:'・未配付'}</div><span>履歴・追加 ›</span></button></section><section class="panel"><div class="toolbar-line"><h2>最近の児童メモ</h2><button type="button" class="button primary" data-student-add="memo">＋ メモを追加</button></div><div class="record-list">${memos.slice(0,3).map(recordItemHtml).join('')||'<p class="muted">まだありません。</p>'}</div>${memos.length>3?'<button type="button" class="button section" data-overview-tab="memo">すべて見る</button>':''}</section></div>`;}
    else if(tab==='homework'){const history=records.filter(item=>['dailyHomework','weeklySubmission','occasionalSubmission'].includes(item.type)),dailyStatus=todayDaily?.status||'unconfirmed';content=`<section class="panel"><h2>今日の毎日の宿題</h2><p class="muted small">カードの通常操作にない「一部忘れた」も、ここから直接記録できます。</p><div class="daily-choice section">${[['submitted','✓ 提出'],['forgotten','! 忘れた'],['partialForgotten','△ 一部忘れた'],['absent','— 欠席']].map(([value,label])=>`<button type="button" data-detail-daily-status="${value}" aria-pressed="${dailyStatus===value}">${label}</button>`).join('')}</div></section><section class="panel"><h2>児童用画面の表示</h2><label class="check-row"><input type="checkbox" id="hide-pupil-homework-status" ${currentEnrollment?.hidePupilHomeworkStatus?'checked':''}> 児童用の一覧・毎日の宿題では、この児童の状態を表示しない</label><p class="muted small">名前だけを表示し、未提出・月間回数・達成アイコンをほかの児童から見えないようにします。教師用画面には通常どおり表示します。</p></section><section class="panel"><div class="toolbar-line"><div><h2>未解決の宿題・提出物</h2><p class="muted">解決した項目は、ここからすぐ反映できます。</p></div><button type="button" class="button primary" data-student-add="homework">${addLabels.homework}</button></div><div class="unresolved-list section">${unresolvedHtml||'<div class="empty-state"><strong>未解決項目はありません</strong></div>'}</div></section><section class="panel"><h2>この期間の履歴</h2><div class="record-list">${history.map(recordItemHtml).join('')||'<p class="muted">この期間の記録はありません。</p>'}</div></section>`;}
    else{const filtered=tab==='memo'?memos:tab==='assessment'?records.filter(item=>item.type==='notebookAssessment'):records.filter(item=>item.type==='certificate');content=`<section class="panel"><div class="toolbar-line"><h2>${tabs.find(item=>item[0]===tab)?.[1]||'記録'}</h2><button type="button" class="button primary" data-student-add="${tab}">${addLabels[tab]}</button></div><div class="record-list section">${filtered.map(recordItemHtml).join('')||'<p class="muted">この期間の記録はありません。上のボタンから追加できます。</p>'}</div></section>`;}
    const statusText=currentEnrollment?.endDate?`${jpDate(currentEnrollment.startDate||state.year.startDate)}～${jpDate(currentEnrollment.endDate)}在籍（転出済み）`:`出席番号 ${currentEnrollment?.number||'―'}`;
    app.innerHTML=teacherToolShell('児童概要',`<div class="student-overview-top"><button type="button" class="button student-overview-close" id="student-overview-close">‹ 一覧へ戻る</button><div class="student-overview-heading"><button type="button" class="button" id="student-prev" ${index<=0?'disabled':''}>前</button><div><h1>${esc(student.name)}</h1><p class="muted">${esc(classItem.name)}・${esc(statusText)}</p></div><button type="button" class="button" id="student-next" ${index<0||index>=roster.length-1?'disabled':''}>次</button></div></div><nav class="student-overview-tabs" aria-label="${esc(student.name)}の記録項目">${tabs.map(([id,label])=>`<button type="button" class="student-overview-tab" data-overview-tab="${id}" aria-selected="${tab===id}">${label}</button>`).join('')}</nav>${content}`);
    wireToolHome();
    document.getElementById('student-overview-close')?.addEventListener('click',()=>{const destination=state.studentReturnTool;state.studentReturnTool=null;if(destination==='settings'){openSettingsPage('classes');}else if(destination&&destination!=='student')openTool(destination);else renderHome();});
    document.getElementById('student-prev')?.addEventListener('click',()=>renderStudentOverview(roster[index-1].student.id,tab));document.getElementById('student-next')?.addEventListener('click',()=>renderStudentOverview(roster[index+1].student.id,tab));
    document.querySelectorAll('[data-overview-tab]').forEach(button=>button.addEventListener('click',()=>renderStudentOverview(studentId,button.dataset.overviewTab)));
    document.querySelectorAll('[data-record-id]').forEach(button=>button.addEventListener('click',()=>openRecordDetail(button.dataset.recordId,studentId,tab)));
    document.querySelectorAll('[data-student-add]').forEach(button=>button.addEventListener('click',()=>openStudentQuickAdd(button.dataset.studentAdd,studentId,tab)));
    document.getElementById('hide-pupil-homework-status')?.addEventListener('change',async event=>{if(!currentEnrollment)return;await ClassDB.put('enrollments',{...currentEnrollment,hidePupilHomeworkStatus:event.target.checked});showToast(event.target.checked?'児童用画面では状態を隠します':'児童用画面に状態を表示します');});
    document.querySelectorAll('[data-detail-daily-status]').forEach(button=>button.addEventListener('click',async()=>{await setDailyStatus(studentId,today(),button.dataset.detailDailyStatus);showToast(`${button.textContent.trim()}にしました`);renderStudentOverview(studentId,'homework');}));
    document.querySelectorAll('[data-resolve-daily]').forEach(button=>button.addEventListener('click',async()=>{const record=await ClassDB.get('records',button.dataset.resolveDaily);if(!record)return;await resolvePrior(record);renderStudentOverview(studentId,'homework');showUndoToast('宿題を解決済みにしました',async()=>{await ClassDB.put('records',record);renderStudentOverview(studentId,'homework');});}));
    document.querySelectorAll('[data-resolve-weekly]').forEach(button=>button.addEventListener('click',async()=>{const occurrence=weekly.occurrences.find(item=>item.id===button.dataset.resolveWeekly);if(!occurrence)return;const id=`weekly_${occurrence.id}_${studentId}`,current=await ClassDB.get('records',id);await ClassDB.put('records',{...(current||{}),id,type:'weeklySubmission',classId:classItem.id,studentId,date:occurrence.dueDate,dueDate:occurrence.dueDate,title:occurrence.title,occurrenceId:occurrence.id,status:'submitted'});renderStudentOverview(studentId,'homework');showUndoToast('週宿題を提出済みにしました',async()=>{if(current)await ClassDB.putRaw('records',current);else await ClassDB.remove('records',id);renderStudentOverview(studentId,'homework');});}));
    document.querySelectorAll('[data-resolve-occasional]').forEach(button=>button.addEventListener('click',async()=>{const item=occasional.items.find(row=>row.id===button.dataset.resolveOccasional);if(!item)return;const id=`occasional_${item.id}_${studentId}`,current=await ClassDB.get('records',id);await ClassDB.put('records',{...(current||{}),id,type:'occasionalSubmission',classId:classItem.id,studentId,date:today(),dueDate:item.dueDate,title:item.title,itemId:item.id,status:'submitted'});renderStudentOverview(studentId,'homework');showUndoToast('提出済みにしました',async()=>{if(current)await ClassDB.putRaw('records',current);else await ClassDB.remove('records',id);renderStudentOverview(studentId,'homework');});}));
  }

  function unresolvedRowHtml(kind,item,title,date){const labels={daily:'忘れ物を解決',weekly:'提出済みにする',occasional:'提出済みにする'},attrs={daily:`data-resolve-daily="${item.id}"`,weekly:`data-resolve-weekly="${item.id}"`,occasional:`data-resolve-occasional="${item.id}"`},dailyState=item.status==='partialForgotten'?'一部忘れたまま':'忘れたまま';return`<div class="unresolved-row"><div><strong>${esc(title)}</strong><span>${esc(jpDate(date))}・${kind==='daily'?dailyState:'未提出'}</span></div><button type="button" class="button primary" ${attrs[kind]}>${labels[kind]}</button></div>`;}

  async function openStudentQuickAdd(kind,studentId,returnTab){if(kind==='memo'){openStudentMemoAdd(studentId,returnTab);return;}if(kind==='assessment'){openStudentAssessmentAdd(studentId,returnTab);return;}if(kind==='certificate'){openStudentCertificateAdd(studentId,returnTab);return;}if(kind==='homework')openStudentSubmissionAdd(studentId,returnTab);}

  async function openStudentMemoAdd(studentId,returnTab){const student=await ClassDB.get('students',studentId),classItem=selectedClass(),tags=await ClassDB.getMeta('memoTags',MEMO_TAGS);openDialog(`<h2>${esc(student.name)}のメモを追加</h2><form id="quick-memo-form"><div class="form-grid"><div class="field"><label for="quick-memo-date">日付</label><input class="input" id="quick-memo-date" type="date" value="${today()}" required></div><div class="field"><label for="quick-memo-subject">教科</label><select class="select" id="quick-memo-subject"><option value="">教科なし</option>${classSubjects(classItem).map(subject=>`<option>${esc(subject)}</option>`).join('')}</select></div><div class="field full"><span class="field-label">プラス評価タグ</span><div class="tag-list">${tags.map(tag=>`<button type="button" class="tag-chip" data-quick-memo-tag="${esc(tag)}" aria-pressed="false">${esc(tag)}</button>`).join('')}</div></div><div class="field full"><label for="quick-memo-text">自由記述（任意）</label><textarea class="textarea" id="quick-memo-text"></textarea></div></div><div class="dialog-actions"><button type="button" class="button" data-quick-cancel>キャンセル</button><button type="submit" class="button primary">保存</button></div></form>`);document.querySelectorAll('[data-quick-memo-tag]').forEach(button=>button.addEventListener('click',()=>button.setAttribute('aria-pressed',String(button.getAttribute('aria-pressed')!=='true'))));wireQuickCancel();document.getElementById('quick-memo-form').addEventListener('submit',async event=>{event.preventDefault();const selected=[...document.querySelectorAll('[data-quick-memo-tag][aria-pressed="true"]')].map(button=>button.dataset.quickMemoTag);await ClassDB.put('records',{id:ClassDB.uid('memo'),type:'memo',classId:classItem.id,studentId,date:document.getElementById('quick-memo-date').value,subject:document.getElementById('quick-memo-subject').value,tags:selected,text:document.getElementById('quick-memo-text').value.trim()});closeDialog();showToast('児童メモを追加しました');renderStudentOverview(studentId,returnTab);});}

  async function openStudentAssessmentAdd(studentId,returnTab){const student=await ClassDB.get('students',studentId),classItem=selectedClass(),subjects=classSubjects(classItem);openDialog(`<h2>${esc(student.name)}のノート評価を追加</h2><form id="quick-assessment-form"><div class="form-grid"><div class="field"><label for="quick-assessment-date">日付</label><input class="input" id="quick-assessment-date" type="date" value="${today()}" required></div><div class="field"><label for="quick-assessment-subject">教科</label><select class="select" id="quick-assessment-subject">${subjects.map(subject=>`<option>${esc(subject)}</option>`).join('')}</select></div><div class="field"><label for="quick-assessment-unit">単元</label><input class="input" id="quick-assessment-unit"></div><div class="field"><label for="quick-assessment-title">題名（任意）</label><input class="input" id="quick-assessment-title"></div></div><div class="section"><span class="field-label">3観点の評価</span><p class="muted small">初期値はすべてBです。変更する観点だけ選びます。</p>${notebookViewpointPickerHtml({...NOTEBOOK_DEFAULT_GRADES})}</div><div class="field section"><label for="quick-assessment-status">作品全体の状態</label><select class="select" id="quick-assessment-status"><option value="evaluated">評価する</option><option value="absent">欠席</option><option value="unsubmitted">未提出</option></select></div><div class="dialog-actions"><button type="button" class="button" data-quick-cancel>キャンセル</button><button type="submit" class="button primary">保存</button></div></form>`);wireNotebookViewpointPicker();wireQuickCancel();document.getElementById('quick-assessment-form').addEventListener('submit',async event=>{event.preventDefault();const draft={date:document.getElementById('quick-assessment-date').value,subject:document.getElementById('quick-assessment-subject').value,unit:document.getElementById('quick-assessment-unit').value.trim(),title:document.getElementById('quick-assessment-title').value.trim()},status=document.getElementById('quick-assessment-status').value,viewpointGrades=readNotebookViewpointGrades(),sessionKey=notebookSessionKey(draft);await ClassDB.put('records',{id:`notebook_${classItem.id}_${sessionKey}_${studentId}`,type:'notebookAssessment',classId:classItem.id,studentId,date:draft.date,subject:draft.subject,unit:draft.unit,title:draft.title||slashDate(draft.date),sessionKey,grade:status==='evaluated'?notebookOverallGrade(viewpointGrades):null,viewpointGrades,status});closeDialog();showToast('ノート評価を追加しました');renderStudentOverview(studentId,returnTab);});}

  async function openStudentCertificateAdd(studentId,returnTab){const student=await ClassDB.get('students',studentId),classItem=selectedClass(),tags=await ClassDB.getMeta('certificateTags',['最後まで取り組んだ','工夫した','友達を助けた','よく発表した','丁寧に仕上げた','成長が見られた']);openDialog(`<h2>${esc(student.name)}のミニ賞状を追加</h2><form id="quick-certificate-form"><div class="field"><label for="quick-certificate-date">日付</label><input class="input" id="quick-certificate-date" type="date" value="${today()}" required></div><div class="tag-list section">${tags.map(tag=>`<button type="button" class="tag-chip" data-quick-certificate-tag="${esc(tag)}" aria-pressed="false">${esc(tag)}</button>`).join('')}</div><div class="field section"><label for="quick-certificate-text">メモ（任意）</label><textarea class="textarea" id="quick-certificate-text"></textarea></div><div class="dialog-actions"><button type="button" class="button" data-quick-cancel>キャンセル</button><button type="submit" class="button primary">保存</button></div></form>`);document.querySelectorAll('[data-quick-certificate-tag]').forEach(button=>button.addEventListener('click',()=>button.setAttribute('aria-pressed',String(button.getAttribute('aria-pressed')!=='true'))));wireQuickCancel();document.getElementById('quick-certificate-form').addEventListener('submit',async event=>{event.preventDefault();const date=document.getElementById('quick-certificate-date').value,id=`certificate_${classItem.id}_${date}_${studentId}`,current=await ClassDB.get('records',id),selected=[...document.querySelectorAll('[data-quick-certificate-tag][aria-pressed="true"]')].map(button=>button.dataset.quickCertificateTag),text=document.getElementById('quick-certificate-text').value.trim();await ClassDB.put('records',{...(current||{}),id,type:'certificate',classId:classItem.id,studentId,date,tags:[...new Set([...(current?.tags||[]),...selected])],text:text||current?.text||''});closeDialog();showToast('ミニ賞状を追加しました');renderStudentOverview(studentId,returnTab);});}

  async function openStudentSubmissionAdd(studentId,returnTab){const student=await ClassDB.get('students',studentId),classItem=selectedClass(),data=await occasionalData(classItem.id),active=data.items.filter(item=>!item.archived),submitted=new Set(data.submissions.filter(item=>item.studentId===studentId&&item.status==='submitted').map(item=>item.itemId)),available=active.filter(item=>!submitted.has(item.id));openDialog(`<h2>${esc(student.name)}の提出物を記録</h2>${available.length?`<form id="quick-submission-form"><div class="field"><label for="quick-submission-item">提出物</label><select class="select" id="quick-submission-item">${available.map(item=>`<option value="${item.id}">${esc(item.title)}・${esc(shortJpDate(item.dueDate))}</option>`).join('')}</select></div><div class="dialog-actions"><button type="button" class="button" data-quick-cancel>キャンセル</button><button type="submit" class="button primary">提出済みにする</button></div></form>`:`<p class="muted">未提出の登録済み提出物はありません。</p><div class="dialog-actions"><button type="button" class="button" data-quick-cancel>閉じる</button><button type="button" class="button primary" id="quick-create-submission">新しい提出物を作る</button></div>`}`);wireQuickCancel();document.getElementById('quick-submission-form')?.addEventListener('submit',async event=>{event.preventDefault();const item=available.find(row=>row.id===document.getElementById('quick-submission-item').value),id=`occasional_${item.id}_${studentId}`;await ClassDB.put('records',{id,type:'occasionalSubmission',classId:classItem.id,studentId,date:today(),dueDate:item.dueDate,title:item.title,itemId:item.id,status:'submitted'});closeDialog();showToast('提出済みにしました');renderStudentOverview(studentId,returnTab);});document.getElementById('quick-create-submission')?.addEventListener('click',()=>{closeDialog();openOccasionalEditor();});}
  function wireQuickCancel(){document.querySelector('[data-quick-cancel]')?.addEventListener('click',closeDialog);}

  function recordItemHtml(record){const labels={memo:'児童メモ',notebookAssessment:'ノート評価',certificate:'ミニ賞状',dailyHomework:'毎日の宿題',weeklySubmission:'週宿題',occasionalSubmission:'提出物',supportRecord:'学習記録'};const detail=record.type==='memo'?`${record.subject||'教科なし'} ${record.unit||''} ${(record.tags||[]).join('・')} ${record.viewpoint||''} ${record.text||''}`:record.type==='notebookAssessment'?`${record.subject||''} ${record.unit||''} ${record.title||''} ${notebookViewpointText(record)} ${record.note||''}`:record.type==='certificate'?(record.tags||[]).join('・')||'渡した':record.title||record.status||'';return`<button type="button" class="record-item" data-record-id="${record.id}"><strong>${esc(jpDate(record.date))}　${esc(labels[record.type]||record.type)}</strong><div class="row-meta">${esc(detail)}</div></button>`;}

  async function openRecordDetail(recordId,studentId,tab){
    const record=await ClassDB.get('records',recordId);if(!record)return;
    const classItem=selectedClass(),labels={memo:'児童メモ',notebookAssessment:'ノート評価',certificate:'ミニ賞状',supportRecord:'学習記録',dailyHomework:'毎日の宿題',weeklySubmission:'週宿題',occasionalSubmission:'提出物'},subjectOptions=`<option value="">教科なし</option>${classSubjects(classItem).map(subject=>`<option value="${esc(subject)}" ${record.subject===subject?'selected':''}>${esc(subject)}</option>`).join('')}`;
    let fields=`<div class="field"><label for="detail-date">日付</label><input class="input" id="detail-date" type="date" value="${esc(record.date||today())}" required></div>`;
    if(record.type==='memo')fields+=`<div class="field"><label for="detail-subject">教科</label><select class="select" id="detail-subject">${subjectOptions}</select></div><div class="field"><label for="detail-unit">単元</label><input class="input" id="detail-unit" value="${esc(record.unit||'')}"></div><div class="field"><label for="detail-tags">タグ（読点区切り）</label><input class="input" id="detail-tags" value="${esc((record.tags||[]).join('、'))}"></div><div class="field"><label for="detail-text">自由記述</label><textarea class="textarea" id="detail-text">${esc(record.text||'')}</textarea></div>`;
    else if(record.type==='notebookAssessment')fields+=`<div class="field"><label for="detail-subject">教科</label><select class="select" id="detail-subject">${subjectOptions}</select></div><div class="field"><label for="detail-unit">単元</label><input class="input" id="detail-unit" value="${esc(record.unit||'')}"></div><div class="field"><label for="detail-title">題名</label><input class="input" id="detail-title" value="${esc(record.title||'')}"></div><div class="section"><span class="field-label">3観点の評価</span>${notebookViewpointPickerHtml(notebookViewpointGrades(record))}</div><div class="field section"><label for="detail-assessment-note">メモ（任意）</label><textarea class="textarea" id="detail-assessment-note">${esc(record.note||'')}</textarea></div><div class="field section"><label for="detail-assessment-status">作品全体の状態</label><select class="select" id="detail-assessment-status"><option value="evaluated" ${!['absent','unsubmitted'].includes(record.status)?'selected':''}>評価する</option><option value="absent" ${record.status==='absent'?'selected':''}>欠席</option><option value="unsubmitted" ${record.status==='unsubmitted'?'selected':''}>未提出</option></select></div>`;
    else if(record.type==='certificate')fields+=`<div class="field"><label for="detail-tags">理由タグ（読点区切り）</label><input class="input" id="detail-tags" value="${esc((record.tags||[]).join('、'))}"></div><div class="field"><label for="detail-text">メモ</label><textarea class="textarea" id="detail-text">${esc(record.text||'')}</textarea></div>`;
    else if(record.type==='supportRecord')fields+=`<div class="field"><label for="detail-subject">教科</label><select class="select" id="detail-subject">${subjectOptions}</select></div><div class="field"><label for="detail-unit">単元</label><input class="input" id="detail-unit" value="${esc(record.unit||'')}"></div><div class="field"><label for="detail-text">自由記述</label><textarea class="textarea" id="detail-text">${esc(record.text||'')}</textarea></div>`;
    else fields+=`<div class="field"><label for="detail-status">状態</label><select class="select" id="detail-status">${[['submitted','提出済み'],['forgotten','忘れた'],['partialForgotten','一部忘れた'],['unsubmitted','未提出'],['unconfirmed','未確認'],['absent','欠席']].map(([value,label])=>`<option value="${value}" ${record.status===value?'selected':''}>${label}</option>`).join('')}</select></div><div class="field"><label for="detail-title">名称</label><input class="input" id="detail-title" value="${esc(record.title||'')}"></div>`;
    openDialog(`<h2>${esc(labels[record.type]||'記録')}を編集</h2><form id="detail-form">${fields}<p class="error" id="detail-error"></p><div class="dialog-actions"><button type="button" class="button danger" id="detail-delete">削除</button><button type="button" class="button" id="detail-close">閉じる</button><button type="submit" class="button primary">変更を保存</button></div></form>`);if(record.type==='notebookAssessment')wireNotebookViewpointPicker();
    document.getElementById('detail-close').addEventListener('click',closeDialog);
    document.getElementById('detail-form').addEventListener('submit',async event=>{event.preventDefault();const changed={...record,date:document.getElementById('detail-date').value};if(document.getElementById('detail-subject'))changed.subject=document.getElementById('detail-subject').value;if(document.getElementById('detail-unit'))changed.unit=document.getElementById('detail-unit').value.trim();if(document.getElementById('detail-title'))changed.title=document.getElementById('detail-title').value.trim();if(document.getElementById('detail-text'))changed.text=document.getElementById('detail-text').value.trim();if(document.getElementById('detail-assessment-note'))changed.note=document.getElementById('detail-assessment-note').value.trim();if(document.getElementById('detail-tags'))changed.tags=[...new Set(document.getElementById('detail-tags').value.split(/[、,\n]/).map(value=>value.trim()).filter(Boolean))];if(document.getElementById('detail-assessment-status')){changed.viewpointGrades=readNotebookViewpointGrades();changed.status=document.getElementById('detail-assessment-status').value;changed.grade=changed.status==='evaluated'?notebookOverallGrade(changed.viewpointGrades):null;}if(document.getElementById('detail-status')){changed.status=document.getElementById('detail-status').value;if(record.type==='dailyHomework')Object.assign(changed,dailyHistory(record,changed.status));}await ClassDB.put('records',changed);closeDialog();renderStudentOverview(studentId,tab);showUndoToast('記録を更新しました',async()=>{await ClassDB.putRaw('records',record);renderStudentOverview(studentId,tab);});});
    document.getElementById('detail-delete').addEventListener('click',()=>{openDialog(`<h2>この記録を削除しますか</h2><p>30日間はごみ箱に残り、データ管理から復元できます。</p><div class="dialog-actions"><button type="button" class="button" id="delete-cancel">キャンセル</button><button type="button" class="button danger" id="delete-confirm">削除</button></div>`);document.getElementById('delete-cancel').addEventListener('click',closeDialog);document.getElementById('delete-confirm').addEventListener('click',async()=>{await moveToTrash(record);closeDialog();renderStudentOverview(studentId,tab);showUndoToast('ごみ箱へ移動しました',async()=>{await ClassDB.putRaw('records',record);await ClassDB.remove('trash',`trash_${record.id}`);renderStudentOverview(studentId,tab);});});});
  }
