"use strict";

  async function renderDataExchange(inSettings=false){
    if(!teacherActive()){renderPupil();return;}
    state.route=inSettings?'teacher-settings':'teacher-data';state.activeTool=inSettings?'settings':'data';state.dataInSettings=inSettings;applyClassTheme(selectedClass());
    const device=await ClassDB.getMeta('syncDeviceName',syncDeviceDefault());
    const lastBackup=await ClassDB.getMeta('lastBackupAt',null);
    const syncHistory=await ClassDB.getMeta('syncHistory',[]);
    const syncConflicts=await currentYearSyncConflicts();
    const preSyncSnapshots=(await ClassDB.getMeta('preSyncSnapshots',[])).filter(item=>Date.parse(item.createdAt)>=Date.now()-30*86400000).slice(0,3);
    const trash=(await ClassDB.getAll('trash')).filter(trashBelongsToCurrentYear).sort((a,b)=>String(b.deletedAt).localeCompare(String(a.deletedAt)));
    const term=currentTermRange();
    const body=`
      <section class="settings-detail-card data-heading" data-card-role="選択"><h2>データを扱う</h2><p>日常の記録は自動保存されています。端末間の同期やファイルの保存・取込を行います。</p><nav class="data-flow-guide settings-route-grid" aria-label="データ操作の使い分け">${settingsNavigationCard({id:'data-sync',title:'端末間で同期',description:'別の端末の記録を取り込んでまとめる',action:'開く',attribute:'data-data-section',className:'data-operation-card',depthNote:false})}${settingsNavigationCard({id:'data-backup',title:'バックアップを保存',description:'故障や年度末に備えて保存する',action:'開く',attribute:'data-data-section',className:'data-operation-card',depthNote:false})}${settingsNavigationCard({id:'data-export',title:'表を出力・ファイルを取込',description:'Excelや別のファイルを扱う',action:'開く',attribute:'data-data-section',className:'data-operation-card',depthNote:false})}${settingsNavigationCard({id:'data-restore',title:'削除データを復元',description:'誤って削除した記録やクラスを戻す',action:'開く',attribute:'data-data-section',className:'data-operation-card',depthNote:false})}</nav></section>
      <section class="settings-detail-card credential-status" data-card-role="状態" id="data-sync"><h2>端末間で記録を同期</h2><div><span class="status-pill good">教師画面PIN：認証済み</span><span class="status-pill ${state.sessionSecret?'good':'neutral'}">データ保護パスワード：${state.sessionSecret?'確認済み':'未確認'}</span></div><p class="muted small">別の端末で行った記録を、この端末の記録に追加・更新します。ファイルの作成と取込には年度パスワードを使います。</p><div class="form-grid section"><div class="field"><label for="sync-device-name">ファイル名に使う端末名 <small>例：職員室PC・教室iPad</small></label><input class="input" id="sync-device-name" value="${esc(device)}"></div><div class="field" style="align-self:end"><button type="button" class="button primary" id="sync-export">この端末の記録をファイルに保存</button></div><div class="field full"><label for="sync-import">別の端末で作ったファイルを選ぶ</label><input class="input" id="sync-import" type="file" accept=".json,.json.txt,application/json,text/plain"></div></div><details class="sync-guide-after"><summary>同期の流れを見る</summary>${syncGuideHtml()}</details></section>
      <details class="settings-detail-card data-advanced" data-card-role="履歴"><summary>最近の同期・保存履歴を確認する</summary><div class="button-row section" style="justify-content:space-between"><p class="muted">この端末で行った最近の履歴です。</p><button type="button" class="button" id="sync-history-refresh">更新</button></div>${syncHistoryHtml(syncHistory)}</details>
      <section class="settings-detail-card data-advanced" data-card-role="同期競合"><h2>同期競合の確認</h2><p class="muted">同時編集などで内容が分かれた記録を確認します。通常の児童一覧には表示されません。</p><div class="button-row"><span class="status-pill ${syncConflicts.length?'warn':'good'}">${syncConflicts.length?`${syncConflicts.length}件が要確認`:'要確認なし'}</span>${syncConflicts.length?'<button type="button" class="button" id="sync-conflict-review">確認・解決する</button>':''}</div></section>
      <details class="settings-detail-card data-advanced" data-card-role="同期の確認" ><summary>同期で困ったときの確認（${preSyncSnapshots.length}件）</summary><div class="section"><p class="muted">同期前の状態を最大3回分・30日間保持しています。同期結果を確認したい場合に使います。</p>${preSyncSnapshots.length?`<div class="list section">${preSyncSnapshots.map(item=>`<div class="list-row"><div><strong>${esc(item.yearLabel)}</strong><div class="row-meta">同期前 ${esc(new Date(item.createdAt).toLocaleString('ja-JP'))}</div></div><button type="button" class="button" data-pre-sync-restore="${item.id}">この状態へ戻す</button></div>`).join('')}</div>`:'<p class="empty-state">同期前の保存はまだありません。</p>'}</div></details>
      <section class="settings-detail-card" data-card-role="保存" id="data-backup"><h2>故障に備えて保存する</h2><p class="muted">端末が壊れた場合や年度末の保管に備え、すべてのデータを安全なファイルにします。</p>${settingsStatusCard({title:'最終ファイル保存',value:lastBackup?new Date(lastBackup).toLocaleString('ja-JP'):'まだありません',description:'日常の記録は端末内へ自動保存されています。',scope:'',tone:lastBackup?'good':'warn'})}<div class="button-row section"><button type="button" class="button primary" id="backup-export">バックアップを保存</button><label class="button">バックアップから復旧<input id="backup-import" type="file" accept=".json,.json.txt,application/json,text/plain" hidden></label></div></section>
      <details class="settings-detail-card data-advanced" data-card-role="補助"><summary>前年度に保存したデータを確認する</summary><p class="muted section">アプリへ戻さず、保管した年度・クラス・人数・記録件数だけを確認します。</p><label class="button">保管ファイルを選ぶ<input id="archive-inspect" type="file" accept=".json,.json.txt,application/json,text/plain" hidden></label></details>
      <details class="settings-detail-card data-advanced" data-card-role="補助" id="data-export"><summary>Excelで確認する一覧を作る</summary><div class="section"><p class="muted">選んだ期間の提出状況やノート評価を、PCのExcelで開ける表として保存します。</p><div class="form-grid"><div class="field"><label for="csv-class">クラス</label><select class="select" id="csv-class">${state.classes.map(item=>`<option value="${item.id}" ${item.id===state.selectedClassId?'selected':''}>${esc(item.name)}</option>`).join('')}</select></div><div></div><div class="field"><label for="csv-start">開始日</label><input class="input" id="csv-start" type="date" value="${term.start}"></div><div class="field"><label for="csv-end">終了日</label><input class="input" id="csv-end" type="date" value="${term.end}"></div></div><p class="error" id="csv-error" role="alert"></p><div class="button-row section"><button type="button" class="button primary" id="submission-csv">提出状況の表を保存</button><button type="button" class="button primary" id="assessment-csv">ノート評価の表を保存</button></div></div></details>
      <details class="settings-detail-card data-advanced" data-card-role="補助"><summary>別の端末・ファイルから取り込む</summary><div class="section"><p class="muted">ファイルの内容を確認してから、対応する記録や名簿へ取り込みます。選んだだけでは保存されません。内容を確認して確定します。</p><div class="button-row"><label class="button primary">ファイルを選んで内容を確認<input id="smart-import-files" type="file" accept=".json,.csv,.txt,.xlsx,application/json,text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" multiple hidden></label><button type="button" class="button" id="external-record-import">表を貼り付けて取り込む</button><button type="button" class="button" id="legacy-scan">この端末に残る旧データを確認</button></div><p class="muted small" id="smart-import-status" role="status">まだファイルは選ばれていません。</p></div></details>
      <details class="settings-detail-card data-advanced" data-card-role="補助" id="data-restore"><summary>削除した記録やクラスを戻す（ごみ箱 ${trash.length}件）</summary><div class="section"><p class="muted">削除した記録やクラスは30日間ここから戻せます。現在年度のデータだけを表示しています。${trash.length>50?`<br>表示中 ${Math.min(state.trashDisplayLimit||50,trash.length)}件／全${trash.length}件。`:''}</p>${trash.length?`<div class="list section">${trash.slice(0,state.trashDisplayLimit||50).map(item=>`<div class="list-row"><div><strong>${esc(item.kind==='classBundle'?`${item.classBundle.class.name}（クラス）`:item.record?.title||({memo:'児童メモ',notebookAssessment:'ノート評価',certificate:'ミニ賞状'}[item.record?.type]||'記録'))}</strong><div class="row-meta">${item.kind==='classBundle'?`名簿 ${item.classBundle.enrollments.length}人・記録 ${item.classBundle.records.length}件・`:''}${esc(jpDate(item.record?.date))}削除 ${esc(new Date(item.deletedAt).toLocaleString('ja-JP'))}</div></div><button type="button" class="button" data-trash-restore="${item.id}">復元</button></div>`).join('')}</div>${trash.length>(state.trashDisplayLimit||50)?`<div class="button-row section"><button type="button" class="button" id="trash-more">さらに50件表示</button></div>`:''}`:'<p class="empty-state">ごみ箱は空です。</p>'}</div></details>
      <details class="settings-detail-card data-advanced" data-card-role="補助"><summary>アプリの表示が古いとき</summary><p class="muted section">現在の公開版：v${APP_VERSION}<br>アップデート日時：${APP_UPDATED_AT}<br>GitHub Pagesの表示が古いと感じた場合だけ、更新確認を実行してください。</p><button type="button" class="button" id="app-update-check">更新を確認して再読み込み</button></details>
      <details class="settings-detail-card danger-zone data-advanced" data-card-role="危険"><summary>クラスやデータを削除する</summary><p class="muted section">必要な保存ファイルを作ったことを確認してから使います。以前のツールのデータは削除しません。</p><div class="settings-role-grid section">${settingsDangerCard({id:'delete-class-records',title:'現在のクラスの記録を削除',description:'名簿は残し、現在のクラスの記録だけをごみ箱へ移します。',action:'記録の削除を確認する',scope:'現在のクラス',attribute:'id'})}${settingsDangerCard({id:'delete-current-class',title:'名簿を含めてクラスを削除',description:'現在のクラス、名簿、関連する記録をごみ箱へ移します。',action:'クラスの削除を確認する',scope:'現在のクラス',attribute:'id'})}${settingsDangerCard({id:'delete-all-data',title:'全データを削除',description:'このアプリの現在データを削除します。以前のツールのデータは残ります。',action:'全データの削除を確認する',scope:'この端末の全データ',attribute:'id'})}</div></details>`;
    if(inSettings&&document.getElementById('settings-content')){const target=document.getElementById('settings-content');target.innerHTML=settingsPageLead('データ管理','端末間の同期、ファイルの取込、バックアップを行います。','safety')+body;wireSettingsHome(target);wireDataSectionTabs(target);}else{app.innerHTML=teacherToolShell('データ管理',body);wireToolHome();wireDataSectionTabs(app);}
    document.getElementById('sync-device-name').addEventListener('change',async event=>{await ClassDB.setMeta('syncDeviceName',event.target.value.trim()||syncDeviceDefault());showToast('端末名を保存しました');});
    document.getElementById('sync-export').addEventListener('click',event=>runOnce(event.currentTarget,async()=>{await saveDeviceNameFromScreen();const saved=await createEncryptedFile('sync');if(saved)showToast('暗号化同期ファイルを保存しました');}));
    document.getElementById('backup-export').addEventListener('click',event=>runOnce(event.currentTarget,async()=>{await saveDeviceNameFromScreen();const saved=await createEncryptedFile('backup');if(saved)showToast('暗号化バックアップを保存しました');}));
    document.getElementById('sync-history-refresh').addEventListener('click',event=>runOnce(event.currentTarget,async()=>renderDataExchange(inSettings)));
    document.getElementById('sync-conflict-review')?.addEventListener('click',()=>openSyncConflictReview());
    document.getElementById('sync-import').addEventListener('change',event=>readEncryptedImport(event.target.files[0]));
    document.getElementById('sync-practice-export').addEventListener('click',createSyncPracticeFile);
    document.getElementById('sync-practice-import').addEventListener('change',event=>inspectSyncPracticeFile(event.target.files[0]));
    document.getElementById('backup-import').addEventListener('change',event=>restoreBackupFile(event.target.files[0]));
    document.getElementById('archive-inspect').addEventListener('change',event=>inspectArchiveFile(event.target.files[0]));
    document.getElementById('submission-csv').addEventListener('click',event=>runOnce(event.currentTarget,()=>exportClassCsv('submission')));
    document.getElementById('assessment-csv').addEventListener('click',event=>runOnce(event.currentTarget,()=>exportClassCsv('assessment')));
    document.getElementById('legacy-scan').addEventListener('click',()=>openLegacyMigrationReview(LegacyMigration.fromStorage()));document.getElementById('external-record-import').addEventListener('click',()=>openExternalImport());
    document.getElementById('smart-import-files').addEventListener('change',async event=>{const files=[...event.target.files],status=document.getElementById('smart-import-status');event.target.value='';if(!files.length)return;if(status)status.textContent=`${files.length}個のファイルを読み取っています…`;await inspectSmartImportFiles(files);});
    document.querySelectorAll('[data-trash-restore]').forEach(button=>button.addEventListener('click',async()=>{const count=await restoreTrashRecord(button.dataset.trashRestore);showToast(count>1?`宿題と提出記録${count-1}件を復元しました`:'記録を復元しました');renderDataExchange(inSettings);}));
    document.getElementById('trash-more')?.addEventListener('click',()=>{state.trashDisplayLimit=(state.trashDisplayLimit||50)+50;renderDataExchange(inSettings);});
    document.querySelectorAll('[data-pre-sync-restore]').forEach(button=>button.addEventListener('click',()=>restorePreSyncSnapshot(button.dataset.preSyncRestore,inSettings)));
    document.getElementById('app-update-check').addEventListener('click',async()=>{const registration=await navigator.serviceWorker?.getRegistration();await registration?.update();if('caches'in window)for(const key of await caches.keys())if(key!==`class-support-shell-v${APP_VERSION}`)await caches.delete(key);location.reload();});
    document.getElementById('delete-current-class').addEventListener('click',confirmDeleteCurrentClass);
    document.getElementById('delete-class-records').addEventListener('click',confirmDeleteClassRecords);
    document.getElementById('delete-all-data').addEventListener('click',confirmDeleteAllData);
  }

  function renderDataSettings(){renderDataExchange(true);}

  async function openDataManagement(){openSettingsPage('data');}
