"use strict";

async function weeklyData(classId){
  let records=(await ClassDB.getAllByIndex('records','classId',classId)).filter(normalRecord);
  const currentDay=today(),staleForgotten=records.filter(item=>item.type==='weeklySubmission'&&item.status==='forgotten'&&!item.autoForgotten&&String(item.forgottenOn||item.statusDate||item.updatedAt||item.date||'').slice(0,10)<currentDay);
  if(staleForgotten.length){const updates=staleForgotten.map(item=>({...item,status:'unsubmitted',forgottenOn:null,statusDate:currentDay}));await ClassDB.applyBatch({puts:{records:updates}});const updateById=new Map(updates.map(item=>[item.id,item]));records=records.map(item=>updateById.get(item.id)||item);}
  records=await applyWeeklyAutoForget(records,classId,currentDay);
  // 先行して作成した週宿題は残します。繰り返し分だけは月曜日以降に作成を案内します。
  const allOccurrences=records.filter(item=>item.type==='weeklyOccurrence'&&item.dueDate<=moveDate(currentWeekStart(),6)).sort((a,b)=>b.dueDate.localeCompare(a.dueDate));
  const occurrences=allOccurrences.filter(item=>!item.hidden);
  const submissions=records.filter(item=>item.type==='weeklySubmission');
  const skippedWeeks=await ClassDB.getMeta('weeklySkippedWeeks',[]);
  return{classId,allRecords:records,occurrences,allOccurrences,submissions,skippedWeeks:Array.isArray(skippedWeeks)?skippedWeeks:[]};
}

function missingRecurringWeeks(data){
  const week=currentWeekStart(),latestBySeries=new Map();
  const allOccurrences=data.allOccurrences||data.occurrences;
  allOccurrences.filter(item=>item.recurring&&item.seriesId&&item.seriesActive!==false).forEach(item=>{const current=latestBySeries.get(item.seriesId);if(!current||item.dueDate>current.dueDate)latestBySeries.set(item.seriesId,item);});
  return[...latestBySeries.values()].filter(item=>!allOccurrences.some(row=>row.seriesId===item.seriesId&&mondayOf(row.dueDate)===week)&&!data.skippedWeeks.includes(`${data.classId}|${item.seriesId}|${week}`));
}

function currentWeeklyOccurrences(data,week=currentWeekStart()){return data.occurrences.filter(item=>mondayOf(item.dueDate)===week);}

let weeklyCreationQueue=Promise.resolve();
function createCurrentWeeklyOccurrences(items){
  const targetClass=selectedClass();if(!targetClass)return Promise.resolve(null);const operation=weeklyCreationQueue.catch(()=>{}).then(async()=>{const week=currentWeekStart(),weekEnd=moveDate(week,6),records=(await ClassDB.getAllByIndex('records','classId',targetClass.id)).filter(item=>item.type==='weeklyOccurrence'&&!item.deletedAt),seenSeries=new Set(),sources=items.filter(item=>item.seriesId&&!seenSeries.has(item.seriesId)&&seenSeries.add(item.seriesId));let first=null;
    for(const source of sources){const existing=records.find(item=>item.seriesId===source.seriesId&&item.dueDate>=week&&item.dueDate<=weekEnd);if(existing){if(!first)first=existing;continue;}const offset=Math.max(0,Math.min(6,daysBetween(source.dueDate,source.weekStart||mondayOf(source.dueDate))));const dueDate=moveDate(week,offset),saved=await ClassDB.put('records',{id:`weeklyOccurrence_${targetClass.id}_${source.seriesId}_${week}`,type:'weeklyOccurrence',classId:targetClass.id,studentId:null,date:dueDate,dueDate,weekStart:week,title:source.title,seriesId:source.seriesId,recurring:true,seriesActive:true});records.push(saved);if(!first)first=saved;}
    if(first)state.toolDraft.weekly={occurrenceId:first.id,dueDate:first.dueDate,title:first.title};return first;});weeklyCreationQueue=operation;return operation;
}

function weeklyRenewalNotice(items,mode){if(!items.length)return'';return`<div class="notice weekly-renewal"><div><strong>今週分がまだ作成されていません</strong><div class="row-meta">${esc(items.map(item=>item.title).join('・'))}を今週も使う場合は作成してください。</div></div><button type="button" class="button primary" data-create-current-week data-create-mode="${mode}">今週分を作る</button></div>`;}

function weeklyDeadlineNoticeHtml(occurrence){if(!occurrence?.autoForgetOnSaturday||!occurrence.autoForgetDate)return'';const threshold=Math.max(1,Number(occurrence.autoForgetAbsenceThreshold)||3);return`<div class="notice weekly-auto-forget-notice"><strong>${esc(pupilText('金曜日までに提出してください','きんようびまでに だしてね'))}</strong><div class="row-meta">${esc(pupilText(`未提出のまま${shortJpDate(occurrence.autoForgetDate)}以降にアプリを開くと、「忘れた」として記録されます。月〜金に${threshold}日以上欠席した児童は自動の忘れから免除されます。`,`ださないまま ${pupilDateText(occurrence.autoForgetDate)} いこうに アプリを ひらくと、「わすれた」になります。げつ〜きんに ${threshold}にち いじょう おやすみした ひとは おやすみです。`))}</div></div>`;}

async function injectWeeklyDeadlineNotice(){const content=document.getElementById('pupil-content');if(!content||content.querySelector('.weekly-auto-forget-notice'))return;const classItem=selectedClass();if(!classItem)return;const data=await weeklyData(classItem.id),current=currentWeeklyOccurrences(data),occurrence=current.find(item=>item.id===state.pupilWeeklyId)||current[0];if(occurrence)content.insertAdjacentHTML('afterbegin',weeklyDeadlineNoticeHtml(occurrence));}

function wireWeeklyRenewal(items,mode,afterCreate){document.querySelector('[data-create-current-week]')?.addEventListener('click',event=>{const button=event.currentTarget;if(button.disabled)return;button.disabled=true;const create=async()=>{try{await createCurrentWeeklyOccurrences(items);showToast('今週分の宿題を作成しました');await afterCreate();}catch(error){button.disabled=false;showToast(error.message||'今週分を作成できませんでした');}};if(mode==='pupil')requireTeacher(create);else create();});}

async function maybePromptWeeklyCreation(mode='teacher'){
  const classItem=selectedClass();if(!classItem)return;const data=await weeklyData(classItem.id),missing=missingRecurringWeeks(data);if(!missing.length)return;
  const key=`${classItem.id}|${currentWeekStart()}|${mode}`;if(state.weeklyPromptShown.has(key))return;state.weeklyPromptShown.add(key);
  openDialog(`<h2>今週の新しい宿題を作りますか？</h2><p>${esc(missing.map(item=>item.title).join('・'))}が「毎週」に設定されています。</p><p class="muted">作成すると、今週の提出状況を新しく記録できます。今は閉じても、週宿題画面から作成できます。</p><div class="dialog-actions"><button type="button" class="button" id="weekly-renew-later">今は作らない</button><button type="button" class="button primary" id="weekly-renew-create">今週分を作る</button></div>`);
  document.getElementById('weekly-renew-later').addEventListener('click',requestDialogClose);
  document.getElementById('weekly-renew-create').addEventListener('click',event=>{const button=event.currentTarget;if(button.disabled)return;button.disabled=true;const create=async()=>{try{await createCurrentWeeklyOccurrences(missing);closeDialog();showToast('今週分の宿題を作成しました');if(mode==='pupil')renderPupil('all');else renderHome();}catch(error){button.disabled=false;showToast(error.message||'今週分を作成できませんでした');}};if(mode==='pupil'){closeDialog();requireTeacher(create);}else create();});
}

async function renderWeekly(){
  if(!teacherActive()){renderPupil();return;}
  state.route='teacher-weekly';state.activeTool='weekly';
  const classItem=selectedClass();applyClassTheme(classItem);const data=await weeklyData(classItem.id);const missingRecurring=missingRecurringWeeks(data);
  let draft=state.toolDraft.weekly;
  if(!draft){const latest=data.occurrences[0];draft=state.toolDraft.weekly={occurrenceId:latest?.id||null,dueDate:latest?.dueDate||today(),title:latest?.title||'自主学習'};}
  let occurrence=data.occurrences.find(item=>item.id===draft.occurrenceId)||null;
  if(!occurrence&&data.occurrences.length){occurrence=data.occurrences[0];draft.occurrenceId=occurrence.id;draft.dueDate=occurrence.dueDate;draft.title=occurrence.title;}
  const currentSubmissions=occurrence?data.submissions.filter(item=>item.occurrenceId===occurrence.id):[];
  const missingByStudent=new Map();
  const dueOccurrences=data.occurrences.filter(item=>mondayOf(item.dueDate)===currentWeekStart()&&item.dueDate<=today());
  const roster=await rosterForClass(classItem.id,false,occurrence?.dueDate||today());
  roster.forEach(row=>{const missing=submissionExempt(row)?[]:dueOccurrences.filter(week=>!data.submissions.some(item=>item.studentId===row.student.id&&item.occurrenceId===week.id&&item.status==='submitted'));missingByStudent.set(row.student.id,missing);});
  const cards=await teacherRosterCards(classItem.id,currentSubmissions,{allRecords:data.allRecords,orderMode:teacherOrderMode(),preserveSeatShape:true,atDate:occurrence?.dueDate||today(),seatOnly:row=>submissionExempt(row),status:(record,row)=>{if(submissionExempt(row))return'';const missing=missingByStudent.get(row.student.id)||[];const missed=missing.length;const maxAge=missing.length?Math.max(...missing.map(item=>Math.floor((new Date(today())-new Date(item.dueDate))/86400000))):0;if(record?.status==='submitted')return missed?`提出済み・過去未提出 ${missed}週`:'提出済み';if(record?.status==='forgotten')return'忘れた';if(missed>=2)return`${missed}週未提出`;if(maxAge>=7)return'7日以上未提出';if(maxAge>=5)return'5日以上未提出';if(occurrence?.dueDate<today())return'未提出';return missed?'過去分未提出':'未提出';},statusClass:(record,row)=>{if(submissionExempt(row))return'muted';const missing=missingByStudent.get(row.student.id)||[];const maxAge=missing.length?Math.max(...missing.map(item=>Math.floor((new Date(today())-new Date(item.dueDate))/86400000))):0;if(record?.status==='forgotten'||missing.length>=2||maxAge>=7)return'alert';if(maxAge>=5)return'warn';return record?.status==='submitted'?'good':'';}});
  const utilities=homeworkUtilitiesHtml({helpKey:'weekly',tapDetail:'押すたびに、提出 → 忘れた → 未提出の順で変わります。毎週の宿題は、月曜日以降に今週分だけ作成します。',settingsSummary:'過去週・表示管理の案内',settingsHtml:'<p class="muted small">過去週の提出状況は、児童カードの「詳細」から確認できます。予定日から5日で黄色、7日で赤の目安です。</p>'});
  app.innerHTML=teacherToolShell('週宿題',`${weeklyRenewalNotice(missingRecurring,'teacher')}<section class="panel weekly-guide"><div class="toolbar-line"><h2>${esc(classItem.name)}の週宿題</h2>${teacherOrderControlHtml()}</div><div class="weekly-heading"><div class="field"><label for="weekly-select">表示する宿題・週</label><select class="select" id="weekly-select">${data.occurrences.map(item=>`<option value="${item.id}" ${item.id===occurrence?.id?'selected':''}>${esc(shortJpDate(item.dueDate))}　${esc(item.title)}</option>`).join('')}</select></div><div class="button-row"><button type="button" class="button" id="weekly-manage">表示・終了を管理</button><button type="button" class="button primary" id="weekly-create">＋ 新しい宿題を作る</button></div></div>${occurrence?`<p class="current-item">提出予定 ${esc(jpDate(occurrence.dueDate))}${occurrence.recurring?'　・毎週繰り返し':''}${occurrence.seriesActive===false?'（終了）':''}</p>`:'<div class="empty-state"><h2>表示中の週宿題はありません</h2><p>「＋ 新しい宿題を作る」から登録するか、「表示・終了を管理」から過去の宿題を再表示できます。</p></div>'}</section>${occurrence?cards:''}${utilities}`);
  wireToolHome();wireStudentDetails();wireTeacherOrder(renderWeekly);
  document.getElementById('weekly-select')?.addEventListener('change',event=>{const selected=data.occurrences.find(item=>item.id===event.target.value);state.toolDraft.weekly={occurrenceId:selected.id,dueDate:selected.dueDate,title:selected.title};renderWeekly();});
  document.getElementById('weekly-create').addEventListener('click',openWeeklyCreator);
  document.getElementById('weekly-manage')?.addEventListener('click',()=>openWeeklyManager(data));
  wireWeeklyRenewal(missingRecurring,'teacher',renderWeekly);
  document.querySelectorAll('[data-tool-student]').forEach(button=>button.addEventListener('click',async()=>{const row=(await rosterForClass(classItem.id)).find(item=>item.student.id===button.dataset.toolStudent);if(row&&submissionExempt(row))return;handleTeacherWeeklyTap(button.dataset.toolStudent,occurrence);}));
}

function mondayOf(value){const date=new Date(`${value}T00:00:00`),day=(date.getDay()+6)%7;date.setDate(date.getDate()-day);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function nextSaturday(value=today()){const date=new Date(`${value}T00:00:00`),delta=(6-date.getDay()+7)%7||7;date.setDate(date.getDate()+delta);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function openWeeklyCreator(){const week=currentWeekStart();openDialog(`<h2>新しい宿題を作る</h2><form id="weekly-create-form"><div class="field"><label for="weekly-new-title">宿題名</label><input class="input" id="weekly-new-title" value="自主学習" required autofocus></div><div class="field section"><label for="weekly-new-date">提出予定日</label><input class="input" id="weekly-new-date" type="date" value="${today()}" required><span class="muted small">今週以外の日付も選べます。先に作った宿題も記録として残ります。</span></div><label class="check-row"><input type="checkbox" id="weekly-recurring" checked> 毎週の宿題として、次週以降も確認する</label><p class="muted small">繰り返し分は、月曜日以降に今週分を作るか確認します。チェックを外すと、この提出予定日だけです。</p><p class="error" id="weekly-create-error"></p><div class="dialog-actions"><button type="button" class="button" id="weekly-create-cancel">キャンセル</button><button type="submit" class="button primary" id="weekly-create-submit">作成する</button></div></form>`);document.getElementById('weekly-create-cancel').addEventListener('click',requestDialogClose);let saving=false;document.getElementById('weekly-create-form').addEventListener('submit',async event=>{event.preventDefault();if(saving)return;const title=document.getElementById('weekly-new-title').value.trim(),dueDate=document.getElementById('weekly-new-date').value,recurring=document.getElementById('weekly-recurring').checked,error=document.getElementById('weekly-create-error');if(!title||!dueDate)return;const records=await ClassDB.getAllByIndex('records','classId',selectedClass().id),duplicate=records.some(item=>item.type==='weeklyOccurrence'&&!item.deletedAt&&item.dueDate===dueDate&&item.title.trim()===title);if(duplicate){error.textContent='同じ提出予定日に同じ名前の宿題があります。表示する宿題・週から確認してください。';return;}saving=true;document.getElementById('weekly-create-submit').disabled=true;try{const seriesId=ClassDB.uid('weeklySeries'),first=await ClassDB.put('records',{id:ClassDB.uid('weeklyOccurrence'),type:'weeklyOccurrence',classId:selectedClass().id,studentId:null,date:dueDate,dueDate,weekStart:mondayOf(dueDate),title,seriesId,recurring,seriesActive:recurring});state.toolDraft.weekly={occurrenceId:first.id,dueDate:first.dueDate,title};closeDialog();showToast(recurring?'毎週の宿題として登録しました':'この週だけの宿題を登録しました');renderWeekly();}catch(saveError){saving=false;document.getElementById('weekly-create-submit').disabled=false;error.textContent=saveError.message||'宿題を保存できませんでした。';}});}

async function setWeeklyVisibility(ids,hidden){const records=await ClassDB.getAll('records'),targets=records.filter(item=>ids.includes(item.id)&&item.type==='weeklyOccurrence'&&!item.deletedAt),timestamp=ClassDB.now(),deviceId=ClassDB.deviceId();await ClassDB.applyBatch({puts:{records:targets.map(item=>({...item,hidden,updatedAt:timestamp,deviceId}))}});state.toolDraft.weekly=null;closeDialog();showToast(hidden?`${targets.length}件を通常画面から隠しました`:`${targets.length}件を表示に戻しました`);renderWeekly();}
async function endWeeklySeries(occurrence){const records=await ClassDB.getAllByIndex('records','classId',occurrence.classId),timestamp=ClassDB.now(),deviceId=ClassDB.deviceId(),targets=occurrence.recurring&&occurrence.seriesId?records.filter(item=>item.type==='weeklyOccurrence'&&item.seriesId===occurrence.seriesId&&!item.deletedAt):[occurrence];await ClassDB.applyBatch({puts:{records:targets.map(item=>({...item,seriesActive:false,endedAt:timestamp,updatedAt:timestamp,deviceId}))}});state.toolDraft.weekly=null;closeDialog();showToast(occurrence.recurring?'今後の繰り返しを終了しました。提出記録は残っています。':'この週宿題を終了しました。提出記録は残っています。');renderWeekly();}
async function resumeWeeklySeries(occurrence){const records=await ClassDB.getAllByIndex('records','classId',occurrence.classId),timestamp=ClassDB.now(),deviceId=ClassDB.deviceId(),targets=occurrence.recurring&&occurrence.seriesId?records.filter(item=>item.type==='weeklyOccurrence'&&item.seriesId===occurrence.seriesId&&!item.deletedAt):[occurrence];await ClassDB.applyBatch({puts:{records:targets.map(item=>({...item,seriesActive:item.recurring?true:item.seriesActive,endedAt:null,updatedAt:timestamp,deviceId}))}});closeDialog();showToast('週宿題を再開しました');renderWeekly();}
/* v137: 複数選択の操作は、選んだときだけ一覧の直下に出す。 */
function openWeeklyManager(data){
  const items=data.allOccurrences||data.occurrences,counts=new Map();data.submissions.forEach(row=>counts.set(row.occurrenceId,(counts.get(row.occurrenceId)||0)+1));
  openDialog(`<h2>週宿題を管理</h2><p class="muted">提出記録は削除されません。普段使わない宿題は非表示にできます。</p><div class="weekly-manager-filters" role="tablist" aria-label="週宿題の絞り込み"><button type="button" class="button" data-weekly-manager-filter="visible" aria-pressed="true">表示中</button><button type="button" class="button" data-weekly-manager-filter="hidden" aria-pressed="false">非表示</button><button type="button" class="button" data-weekly-manager-filter="ended" aria-pressed="false">終了済み</button><button type="button" class="button" data-weekly-manager-filter="all" aria-pressed="false">すべて</button></div><div class="field section"><label for="weekly-manager-search">宿題名・日付で探す</label><input class="input" id="weekly-manager-search" type="search" placeholder="例：自主学習、9月"></div><form id="weekly-manager-form"><div class="list weekly-manage-list" id="weekly-manage-list"></div><div class="weekly-selection-actions" id="weekly-selection-actions" hidden><span id="weekly-selection-count"></span><div class="button-row"><button type="button" class="button" id="weekly-hide-selected">表示しない</button><button type="button" class="button" id="weekly-show-selected">再表示する</button></div></div><div class="field section"><label for="weekly-end-select">繰り返しを終了・再開する宿題</label><select class="select" id="weekly-end-select">${items.map(item=>`<option value="${item.id}">${esc(shortJpDate(item.dueDate))}　${esc(item.title)}${item.recurring&&item.seriesActive===false?'（終了）':''}</option>`).join('')}</select></div><div class="button-row"><button type="button" class="button" id="weekly-end-series">繰り返しを終了</button><button type="button" class="button" id="weekly-resume-series">繰り返しを再開</button></div><div class="dialog-actions"><button type="button" class="button primary" id="weekly-manager-close">閉じる</button></div></form>`,'dialog-xwide');
  let filter='visible';const selectedIds=new Set(),selectionBar=document.getElementById('weekly-selection-actions'),updateSelection=()=>{const count=selectedIds.size;selectionBar.hidden=!count;document.getElementById('weekly-selection-count').textContent=`${count}件選択中`;};
  const renderList=()=>{const query=document.getElementById('weekly-manager-search').value.trim().toLowerCase(),filtered=items.filter(item=>{const mode=item.seriesActive===false?'ended':item.hidden?'hidden':'visible',text=`${item.title} ${item.dueDate}`.toLowerCase();return(filter==='all'||filter===mode)&&(!query||text.includes(query));});document.getElementById('weekly-manage-list').innerHTML=filtered.map(item=>`<label class="list-row"><input type="checkbox" data-weekly-manage-select="${item.id}" ${selectedIds.has(item.id)?'checked':''}><div><strong>${esc(item.title)}${item.hidden?'（非表示）':''}</strong><div class="row-meta">${esc(jpDate(item.dueDate))}・提出記録 ${counts.get(item.id)||0}件${item.recurring?`・毎週${item.seriesActive===false?'（終了）':''}`:''}</div></div></label>`).join('')||'<p class="empty-state">該当する宿題はありません。</p>';document.querySelectorAll('[data-weekly-manager-filter]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.weeklyManagerFilter===filter)));document.querySelectorAll('[data-weekly-manage-select]').forEach(input=>input.addEventListener('change',()=>{input.checked?selectedIds.add(input.dataset.weeklyManageSelect):selectedIds.delete(input.dataset.weeklyManageSelect);updateSelection();}));updateSelection();};
  document.querySelectorAll('[data-weekly-manager-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.weeklyManagerFilter;renderList();}));document.getElementById('weekly-manager-search').addEventListener('input',renderList);document.getElementById('weekly-manager-close').addEventListener('click',requestDialogClose);document.getElementById('weekly-hide-selected').addEventListener('click',()=>setWeeklyVisibility([...selectedIds],true));document.getElementById('weekly-show-selected').addEventListener('click',()=>setWeeklyVisibility([...selectedIds],false));document.getElementById('weekly-end-series').addEventListener('click',()=>{const item=items.find(row=>row.id===document.getElementById('weekly-end-select').value);if(item)endWeeklySeries(item);});document.getElementById('weekly-resume-series').addEventListener('click',()=>{const item=items.find(row=>row.id===document.getElementById('weekly-end-select').value);if(item)resumeWeeklySeries(item);});renderList();
}
const weeklyTapQueues=new Map();
function applyWeeklyTap(studentId,occurrence,afterRender){if(!occurrence)return Promise.resolve();const id=`weekly_${occurrence.id}_${studentId}`,classId=occurrence.classId||selectedClass()?.id,previous=weeklyTapQueues.get(id)||Promise.resolve(),operation=previous.catch(()=>{}).then(async()=>{const current=await ClassDB.get('records',id),next=current?.status==='submitted'?'forgotten':current?.status==='forgotten'?'unsubmitted':'submitted';await ClassDB.put('records',{...(current||{}),id,type:'weeklySubmission',classId,studentId,date:occurrence.dueDate,dueDate:occurrence.dueDate,title:occurrence.title,occurrenceId:occurrence.id,status:next,forgottenOn:next==='forgotten'?today():null,statusDate:today()});markFeedback(studentId,next);const message=next==='submitted'?'提出にしました':next==='forgotten'?'忘れたにしました':'未提出に戻しました';await afterRender();if(afterRender===renderWeekly)showUndoToast(message,async()=>{if(current)await ClassDB.put('records',current);else await moveToTrash(await ClassDB.get('records',id));await afterRender();});else showToast(message);return next;}).finally(()=>{if(weeklyTapQueues.get(id)===operation)weeklyTapQueues.delete(id);});weeklyTapQueues.set(id,operation);return operation;}
function handleTeacherWeeklyTap(studentId,occurrence){return applyWeeklyTap(studentId,occurrence,renderWeekly);}

