"use strict";

  const TEST_VIEWPOINTS=[{key:'knowledge',label:'知識・技能',patterns:[/知/]} ,{key:'thinking',label:'思考・判断・表現',patterns:[/思|判|表|読む|書く|話|聞/]} ,{key:'attitude',label:'主体的に学習に取り組む態度',patterns:[/態/]}];
  const numberValue=value=>{const parsed=Number(String(value??'').replace(/,/g,'').trim());return Number.isFinite(parsed)?parsed:null;};
  const cellText=(rows,row,column)=>String(rows[row]?.[column]??'').trim();
  function testViewpoint(label){return TEST_VIEWPOINTS.find(item=>item.patterns.some(pattern=>pattern.test(String(label))))?.key||'';}
  function testWorkbookSheets(sheets){
    return sheets.map(sheet=>{
      const rows=sheet.rows,headerIndex=rows.findIndex(row=>row.some(value=>/^(番|番号|出席番号)$/.test(String(value).replace(/\s/g,'')))&&row.some(value=>/名前|氏名/.test(String(value))));
      if(headerIndex<1)return{...sheet,tests:[],students:[],reason:'番号・名前の見出しが見つかりません'};
      const header=rows[headerIndex],numberColumn=header.findIndex(value=>/^(番|番号|出席番号)$/.test(String(value).replace(/\s/g,''))),nameColumn=header.findIndex(value=>/名前|氏名/.test(String(value))),viewpointRow=rows[headerIndex-1]||[],unitRow=rows[headerIndex-2]||[],roundRow=rows[headerIndex-3]||[];
      const starts=[];for(let column=nameColumn+1;column<header.length;column++)if(cellText(rows,headerIndex-2,column))starts.push(column);
      const tests=starts.map((start,index)=>{const end=(starts[index+1]??header.length)-1,rawTitle=cellText(rows,headerIndex-2,start)||cellText(rows,headerIndex-3,start)||`テスト${index+1}`,title=rawTitle.replace(/\s+/g,' ').trim();const columns=[];for(let column=start;column<=end;column++){const max=numberValue(header[column]),label=cellText(rows,headerIndex-1,column);if(max===null||max<=0||/合計|総得点/.test(label))continue;columns.push({column,label:label||`得点${column-start+1}`,max,viewpoint:testViewpoint(label)});}return{id:`${sheet.name}|${index}|${title}`,title,round:cellText(rows,headerIndex-3,start),columns};}).filter(test=>test.columns.length);
      const students=[];for(let rowIndex=headerIndex+1;rowIndex<rows.length;rowIndex++){const number=numberValue(rows[rowIndex]?.[numberColumn]),name=cellText(rows,rowIndex,nameColumn);if(number===null||!name||/学級平均|平均/.test(name))continue;students.push({number:String(number),name,rowIndex});}
      return{...sheet,headerIndex,numberColumn,nameColumn,tests,students,reason:tests.length?'':'テストの配点・観点が見つかりません'};
    }).filter(sheet=>sheet.tests.length||sheet.students.length);
  }
  async function openTestImport(){
    openDialog(`<h2>テスト採点表を取り込む</h2><p class="muted">Excel（.xlsx）を選ぶと、教科・テスト名・番号・氏名・得点を確認してから登録します。元のExcelは変更しません。</p><form id="test-import-file-form"><div class="field"><label for="test-import-file">テスト採点表（Excel）</label><input class="input" id="test-import-file" type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" required></div><p class="error" id="test-import-error" role="alert"></p><div class="dialog-actions"><button type="button" class="button" id="test-import-cancel">キャンセル</button><button type="submit" class="button primary">内容を確認</button></div></form>`);
    document.getElementById('test-import-cancel').addEventListener('click',closeDialog);
    document.getElementById('test-import-file-form').addEventListener('submit',async event=>{event.preventDefault();const file=document.getElementById('test-import-file').files[0],error=document.getElementById('test-import-error');try{if(!file)throw new Error('Excelファイルを選んでください。');const sheets=testWorkbookSheets(await XlsxRosterReader.readWorkbook(file));if(!sheets.some(sheet=>sheet.tests.length))throw new Error('テストの配点・観点が読み取れませんでした。番号・名前・配点の行がある採点表を選んでください。');openTestImportPreview(file.name,sheets);}catch(cause){error.textContent=cause.message||'Excelを読み取れませんでした。';}});
  }
  async function openTestImportPreview(fileName,sheets){
    const classItem=selectedClass(),roster=await rosterForClass(classItem.id),byNumber=new Map(roster.filter(row=>row.enrollment.number!==''&&row.enrollment.number!==null).map(row=>[String(row.enrollment.number),row])),byName=new Map(roster.map(row=>[normalizeStudentName(row.student.name),row]));
    const detected=sheets.flatMap(sheet=>sheet.tests.map(test=>{const matches=sheet.students.map(student=>({student,row:byNumber.get(student.number)||byName.get(normalizeStudentName(student.name))||null})),matched=matches.filter(item=>item.row).length;return{sheet,test,matches,matched};}));
    openDialog(`<h2>取り込むテストを確認</h2><p class="muted">${esc(fileName)}。同じ番号を優先し、次に氏名（空白を無視）で名簿と結び付けます。合わない児童は登録しません。</p><form id="test-import-preview"><div class="form-grid"><div class="field"><label for="test-import-date">実施日</label><input class="input" id="test-import-date" type="date" value="${today()}" required></div><div class="field"><label for="test-import-term">期間</label><select class="select" id="test-import-term"><option value="auto">日付から自動</option><option value="front">前期</option><option value="back">後期</option></select></div></div><div class="test-import-list section">${detected.map((item,index)=>`<label class="test-import-choice"><input type="checkbox" data-test-import-index="${index}" checked><span><strong>${esc(item.sheet.name)}：${esc(item.test.title)}</strong><small>${item.test.columns.map(column=>`${esc(column.label)} ${column.max}点`).join(' ／ ')}　${item.matched}/${item.matches.length}人を名簿に結び付け</small></span></label>`).join('')}</div><p class="notice small">点数は後から成績管理で確認・削除できます。通知表の評定は自動で決まりません。</p><div class="dialog-actions"><button type="button" class="button" id="test-preview-back">戻る</button><button type="submit" class="button primary">選んだテストを登録</button></div></form>`);
    document.getElementById('test-preview-back').addEventListener('click',openTestImport);
    document.getElementById('test-import-preview').addEventListener('submit',async event=>{event.preventDefault();const picked=[...document.querySelectorAll('[data-test-import-index]:checked')].map(input=>detected[Number(input.dataset.testImportIndex)]),date=document.getElementById('test-import-date').value,termChoice=document.getElementById('test-import-term').value,term=termChoice==='auto'?(date<=state.year.firstTermEnd?'front':'back'):termChoice;if(!picked.length){showToast('取り込むテストを1つ以上選んでください');return;}const records=[];for(const item of picked)for(const match of item.matches){if(!match.row)continue;const scores=item.test.columns.map(column=>({label:column.label,viewpoint:column.viewpoint,point:numberValue(item.sheet.rows[match.student.rowIndex]?.[column.column]),max:column.max})).filter(score=>score.point!==null);if(!scores.length)continue;const total=scores.reduce((sum,score)=>sum+score.point,0),maxTotal=scores.reduce((sum,score)=>sum+score.max,0),id=`testScore_${classItem.id}_${simpleHash([fileName,item.test.id,date,match.row.student.id].join('|'))}`;records.push({id,type:'testScore',classId:classItem.id,studentId:match.row.student.id,date,term,subject:item.sheet.name,title:item.test.title,round:item.test.round,sourceFile:fileName,sourceTestId:item.test.id,total,maxTotal,scores});}
      for(const record of records)record.sourceTestId=`${fileName}|${record.sourceTestId}`;
      await ClassDB.putMany('records',records);closeDialog();showToast(`${records.length}人分のテスト得点を登録しました`);renderGradebook();
    });
  }
  function gradePeriodRange(period){return notebookSummaryPeriodRange(period);}
  function testStudentSummary(records){const valid=records.filter(record=>Number.isFinite(record.total)&&Number.isFinite(record.maxTotal)&&record.maxTotal>0),sum=valid.reduce((value,record)=>value+record.total,0),max=valid.reduce((value,record)=>value+record.maxTotal,0);return{count:valid.length,percentage:max?sum/max*100:null};}
  function gradebookRows(roster,tests,notes){const testsByStudent=new Map(),notesByStudent=new Map();tests.forEach(record=>{if(!testsByStudent.has(record.studentId))testsByStudent.set(record.studentId,[]);testsByStudent.get(record.studentId).push(record);});notes.forEach(record=>{if(!notesByStudent.has(record.studentId))notesByStudent.set(record.studentId,[]);notesByStudent.get(record.studentId).push(record);});return roster.map(row=>({row,tests:testStudentSummary(testsByStudent.get(row.student.id)||[]),notebook:notebookStudentSummary(notesByStudent.get(row.student.id)||[])}));}
  async function renderGradebook(){
    if(!teacherActive()){renderPupil();return;}state.route='teacher-grades';state.activeTool='grades';const classItem=selectedClass();applyClassTheme(classItem);const draft=state.toolDraft.grades||{subject:'all',period:'front'},subjects=classSubjects(classItem),period=gradePeriodRange(draft.period),allRecords=(await ClassDB.getAllByIndex('records','classId',classItem.id)).filter(item=>!item.deletedAt),tests=allRecords.filter(item=>item.type==='testScore'&&item.date>=period.start&&item.date<=period.end&&(draft.subject==='all'||item.subject===draft.subject)),notes=allRecords.filter(item=>item.type==='notebookAssessment'&&item.date>=period.start&&item.date<=period.end&&(draft.subject==='all'||item.subject===draft.subject)),roster=await rosterForRange(classItem.id,period.start,period.end),rows=gradebookRows(roster,tests,notes),testGroups=[...new Map(tests.map(item=>[item.sourceTestId,{id:item.sourceTestId,subject:item.subject,title:item.title,date:item.date,count:0}])).values()];testGroups.forEach(group=>group.count=tests.filter(item=>item.sourceTestId===group.id).length);
    app.innerHTML=teacherToolShell('成績管理',`<section class="panel gradebook-head"><div class="toolbar-line"><div><h1>${esc(classItem.name)}の成績管理</h1><p class="muted">テスト得点とノート評価を並べて、成績を考える材料を確認します。評定は自動で決定しません。</p></div><button type="button" class="button primary" id="grade-import">Excelのテスト採点表を取り込む</button></div><div class="tool-controls"><div class="field"><label for="grade-subject">教科</label><select class="select" id="grade-subject"><option value="all">全教科</option>${subjects.map(subject=>`<option value="${esc(subject)}" ${subject===draft.subject?'selected':''}>${esc(subject)}</option>`).join('')}</select></div><div class="field"><label for="grade-period">期間</label><select class="select" id="grade-period"><option value="front" ${draft.period==='front'?'selected':''}>前期</option><option value="back" ${draft.period==='back'?'selected':''}>後期</option><option value="year" ${draft.period==='year'?'selected':''}>年間</option></select></div><div class="field action-field"><button type="button" class="button" id="grade-apply">表示を更新</button></div></div></section><section class="panel gradebook-table-panel"><h2>児童ごとの一覧</h2><p class="muted small">テストは合計得点÷配点の得点率、ノートは知・思・態をA=5〜C=1として平均した値です。</p><div class="gradebook-table">${rows.map(item=>`<article class="gradebook-row"><div><span class="student-number">${esc(item.row.enrollment.number||'—')}</span><strong>${esc(item.row.student.name)}</strong></div><div><span>テスト</span><strong>${item.tests.percentage===null?'—':`${item.tests.percentage.toFixed(1)}%`}</strong><small>${item.tests.count}回</small></div><div><span>ノート（3観点）</span><strong>${item.notebook.average===null?'—':`${item.notebook.average.toFixed(2)} ${notebookAverageLabel(item.notebook.average)}`}</strong><small>${item.notebook.count}回</small></div><div class="gradebook-points">${NOTEBOOK_VIEWPOINTS.map(point=>`<span>${point.short} ${item.notebook.viewpoints[point.key].average===null?'—':item.notebook.viewpoints[point.key].average.toFixed(2)}</span>`).join('')}</div></article>`).join('')||'<p class="empty-state">この期間に在籍する児童がいません。</p>'}</div></section><section class="panel"><h2>取り込んだテスト</h2>${testGroups.length?`<div class="list">${testGroups.map(group=>`<div class="list-row"><div><strong>${esc(group.subject)}　${esc(group.title)}</strong><div class="row-meta">${esc(jpDate(group.date))}・${group.count}人分</div></div><button type="button" class="button danger" data-grade-delete="${esc(group.id)}">このテストを削除</button></div>`).join('')}</div>`:'<p class="empty-state">まだテスト得点がありません。Excelの採点表を取り込むと、ここに表示します。</p>'}</section>`);
    wireToolHome();document.getElementById('grade-import').addEventListener('click',openTestImport);document.getElementById('grade-apply').addEventListener('click',()=>{state.toolDraft.grades={subject:document.getElementById('grade-subject').value,period:document.getElementById('grade-period').value};renderGradebook();});document.querySelectorAll('[data-grade-delete]').forEach(button=>button.addEventListener('click',()=>openDeleteTest(button.dataset.gradeDelete)));
  }
  async function openDeleteTest(sourceTestId){const classItem=selectedClass(),records=(await ClassDB.getAllByIndex('records','classId',classItem.id)).filter(item=>item.type==='testScore'&&item.sourceTestId===sourceTestId&&!item.deletedAt),sample=records[0];openDialog(`<h2>テスト得点を削除しますか</h2><p>${esc(sample?.subject||'')}「${esc(sample?.title||'')}」の${records.length}人分を削除します。ノート評価は削除されません。</p><div class="dialog-actions"><button type="button" class="button" id="grade-delete-cancel">キャンセル</button><button type="button" class="button danger" id="grade-delete-confirm">削除する</button></div>`);document.getElementById('grade-delete-cancel').addEventListener('click',closeDialog);document.getElementById('grade-delete-confirm').addEventListener('click',async()=>{await ClassDB.putMany('records',records.map(record=>({...record,deletedAt:ClassDB.now()})));closeDialog();showToast('テスト得点を削除しました');renderGradebook();});}
