"use strict";

  async function renderDataExchange(inSettings=false){
    if(!teacherActive()){renderPupil();return;}
    state.route=inSettings?'teacher-settings':'teacher-data';state.activeTool=inSettings?'settings':'data';state.dataInSettings=inSettings;applyClassTheme(selectedClass());
    const device=await ClassDB.getMeta('syncDeviceName',syncDeviceDefault());
    const lastBackup=await ClassDB.getMeta('lastBackupAt',null);
    const syncHistory=await ClassDB.getMeta('syncHistory',[]);
    const preSyncSnapshots=(await ClassDB.getMeta('preSyncSnapshots',[])).filter(item=>Date.parse(item.createdAt)>=Date.now()-30*86400000).slice(0,3);
    const trash=(await ClassDB.getAll('trash')).filter(item=>item.record?.classId&&state.classes.some(classItem=>classItem.id===item.record.classId)).sort((a,b)=>String(b.deletedAt).localeCompare(String(a.deletedAt)));
    const term=currentTermRange();
    const body=`
      <section class="panel data-heading"><h2>今日行う操作</h2><p>日常の記録は自動保存されています。目的に合う操作を選んでください。</p><nav class="data-flow-guide" aria-label="データ操作の使い分け"><button type="button" data-data-section="data-sync"><b>同期</b><span><strong>iPadとPCの記録をまとめる</strong><small>両方の端末で記録したあと</small></span><i aria-hidden="true">›</i></button><button type="button" data-data-section="data-backup"><b>保存</b><span><strong>故障に備えて保存する</strong><small>月に1回・年度末</small></span><i aria-hidden="true">›</i></button><button type="button" data-data-section="data-export"><b>入出力</b><span><strong>Excel・以前のデータを扱う</strong><small>一覧の保存・取込</small></span><i aria-hidden="true">›</i></button><button type="button" data-data-section="data-restore"><b>復元</b><span><strong>保存した時点へ戻す</strong><small>現在の記録を置き換えます</small></span><i aria-hidden="true">›</i></button></nav></section>
      <section class="panel credential-status" id="data-sync"><h2>iPadとPCの記録をまとめる</h2><div><span class="status-pill good">教師画面PIN：認証済み</span><span class="status-pill ${state.sessionSecret?'good':'neutral'}">データ保護パスワード：${state.sessionSecret?'確認済み':'未確認'}</span></div><p class="muted small">両方の端末で別々に付けた記録を一つにします。作成・取り込みには年度のデータ保護パスワードを使います。復旧コードは、パスワードを忘れた場合だけ使用します。</p>${syncGuideHtml()}<div class="form-grid section"><div class="field"><label for="sync-device-name">この端末の名前 <small>例：職員室PC・教室iPad</small></label><input class="input" id="sync-device-name" value="${esc(device)}"></div><div class="field" style="align-self:end"><button type="button" class="button primary" id="sync-export">移す元の端末でファイルを作る</button></div><div class="field full"><label for="sync-import">移動先の端末でファイルを取り込む</label><input class="input" id="sync-import" type="file" accept=".json,.json.txt,application/json,text/plain"></div></div></section>
      <details class="panel data-advanced"><summary>最近の同期・保存履歴を確認する</summary><div class="button-row section" style="justify-content:space-between"><p class="muted">この端末で行った最近の履歴です。</p><button type="button" class="button" id="sync-history-refresh">更新</button></div>${syncHistoryHtml(syncHistory)}</details>
      <details class="panel data-advanced"><summary>直前の同期前へ戻す（${preSyncSnapshots.length}件）</summary><div class="section"><p class="muted">同期の直前に自動保存した状態を、最大3回分・30日間保持します。同期結果に問題があった場合だけ使います。</p>${preSyncSnapshots.length?`<div class="list section">${preSyncSnapshots.map(item=>`<div class="list-row"><div><strong>${esc(item.yearLabel)}</strong><div class="row-meta">同期前 ${esc(new Date(item.createdAt).toLocaleString('ja-JP'))}</div></div><button type="button" class="button" data-pre-sync-restore="${item.id}">この状態へ戻す</button></div>`).join('')}</div>`:'<p class="empty-state">同期前の保存はまだありません。</p>'}</div></details>
      <section class="panel" id="data-backup"><h2>故障に備えて保存する</h2><p class="muted">端末が壊れた場合や年度末の保管に備え、すべてのデータを安全なファイルにします。最終保存：${lastBackup?esc(new Date(lastBackup).toLocaleString('ja-JP')):'まだありません'}</p><div class="button-row"><button type="button" class="button primary" id="backup-export">全データを安全なファイルに保存</button><label class="button">保存したデータを戻す<input id="backup-import" type="file" accept=".json,.json.txt,application/json,text/plain" hidden></label></div></section>
      <details class="panel data-advanced"><summary>前年度に保存したデータを確認する</summary><p class="muted section">アプリへ戻さず、保管した年度・クラス・人数・記録件数だけを確認します。</p><label class="button">保管ファイルを選ぶ<input id="archive-inspect" type="file" accept=".json,.json.txt,application/json,text/plain" hidden></label></details>
      <details class="panel data-advanced" id="data-export"><summary>Excelで確認する一覧を作る</summary><div class="section"><p class="muted">選んだ期間の提出状況やノート評価を、PCのExcelで開ける表として保存します。</p><div class="form-grid"><div class="field"><label for="csv-class">クラス</label><select class="select" id="csv-class">${state.classes.map(item=>`<option value="${item.id}" ${item.id===state.selectedClassId?'selected':''}>${esc(item.name)}</option>`).join('')}</select></div><div></div><div class="field"><label for="csv-start">開始日</label><input class="input" id="csv-start" type="date" value="${term.start}"></div><div class="field"><label for="csv-end">終了日</label><input class="input" id="csv-end" type="date" value="${term.end}"></div></div><p class="error" id="csv-error" role="alert"></p><div class="button-row section"><button type="button" class="button primary" id="submission-csv">提出状況の表を保存</button><button type="button" class="button primary" id="assessment-csv">ノート評価の表を保存</button></div></div></details>
      <details class="panel data-advanced"><summary>以前のデータを取り込む</summary><div class="section"><p class="muted">ファイルの内容を確認して、対応する記録や名簿へ移します。ファイルを選んだだけでは保存されません。必ず次に「内容を確認」の画面が出ます。</p><div class="button-row"><label class="button primary">ファイルを選んで内容を確認<input id="smart-import-files" type="file" accept=".json,.csv,.txt,.xlsx,application/json,text/csv,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" multiple hidden></label><button type="button" class="button" id="external-record-import">表を貼り付けて取り込む</button><button type="button" class="button" id="legacy-scan">この端末の以前のデータを確認</button></div><p class="muted small" id="smart-import-status" role="status">まだファイルは選ばれていません。</p></div></details>
      <details class="panel data-advanced" id="data-restore"><summary>削除した記録を戻す（ごみ箱 ${trash.length}件）</summary><div class="section"><p class="muted">削除した記録は30日間ここから戻せます。</p>${trash.length?`<div class="list section">${trash.slice(0,50).map(item=>`<div class="list-row"><div><strong>${esc(item.record?.title||({memo:'児童メモ',notebookAssessment:'ノート評価',certificate:'ミニ賞状'}[item.record?.type]||'記録'))}</strong><div class="row-meta">${esc(jpDate(item.record?.date))}・削除 ${esc(new Date(item.deletedAt).toLocaleString('ja-JP'))}</div></div><button type="button" class="button" data-trash-restore="${item.id}">復元</button></div>`).join('')}</div>`:'<p class="empty-state">ごみ箱は空です。</p>'}</div></details>
      <details class="panel data-advanced"><summary>アプリの表示が古いとき</summary><p class="muted section">現在の公開版：v${APP_VERSION}<br>アップデート日時：${APP_UPDATED_AT}<br>GitHub Pagesの表示が古いと感じた場合だけ、更新確認を実行してください。</p><button type="button" class="button" id="app-update-check">更新を確認して再読み込み</button></details>
      <details class="panel danger-zone data-advanced"><summary>クラスやデータを削除する</summary><p class="muted section">必要な保存ファイルを作ったことを確認してから使います。以前のツールのデータは削除しません。</p><div class="button-row"><button type="button" class="button danger" id="delete-class-records">現在のクラスの記録を削除</button><button type="button" class="button danger" id="delete-current-class">名簿を含めてクラスを削除</button><button type="button" class="button danger" id="delete-all-data">全データを削除（旧版データは残す）</button></div></details>`;
    if(inSettings&&document.getElementById('settings-content')){const target=document.getElementById('settings-content');target.innerHTML=settingsPageLead('同期・保存・復元','iPadとPCの記録をまとめたり、故障に備えて保存したりします。','safety')+body;cardifySettingsPanels(target);wireSettingsHome(target);wireDataSectionTabs(target);}else{app.innerHTML=teacherToolShell('データ管理',body);wireToolHome();wireDataSectionTabs(app);}
    document.getElementById('sync-device-name').addEventListener('change',async event=>{await ClassDB.setMeta('syncDeviceName',event.target.value.trim()||syncDeviceDefault());showToast('端末名を保存しました');});
    document.getElementById('sync-export').addEventListener('click',event=>runOnce(event.currentTarget,async()=>{await saveDeviceNameFromScreen();const saved=await createEncryptedFile('sync');if(saved)showToast('暗号化同期ファイルを保存しました');}));
    document.getElementById('backup-export').addEventListener('click',event=>runOnce(event.currentTarget,async()=>{await saveDeviceNameFromScreen();const saved=await createEncryptedFile('backup');if(saved)showToast('暗号化バックアップを保存しました');}));
    document.getElementById('sync-history-refresh').addEventListener('click',event=>runOnce(event.currentTarget,async()=>renderDataExchange(inSettings)));
    document.getElementById('sync-import').addEventListener('change',event=>readEncryptedImport(event.target.files[0]));
    document.getElementById('sync-practice-export').addEventListener('click',createSyncPracticeFile);
    document.getElementById('sync-practice-import').addEventListener('change',event=>inspectSyncPracticeFile(event.target.files[0]));
    document.getElementById('backup-import').addEventListener('change',event=>restoreBackupFile(event.target.files[0]));
    document.getElementById('archive-inspect').addEventListener('change',event=>inspectArchiveFile(event.target.files[0]));
    document.getElementById('submission-csv').addEventListener('click',event=>runOnce(event.currentTarget,()=>exportClassCsv('submission')));
    document.getElementById('assessment-csv').addEventListener('click',event=>runOnce(event.currentTarget,()=>exportClassCsv('assessment')));
    document.getElementById('legacy-scan').addEventListener('click',()=>openLegacyMigrationReview(LegacyMigration.fromStorage()));document.getElementById('external-record-import').addEventListener('click',()=>openExternalImport());
    document.getElementById('smart-import-files').addEventListener('change',async event=>{const files=[...event.target.files],status=document.getElementById('smart-import-status');event.target.value='';if(!files.length)return;if(status)status.textContent=`${files.length}個のファイルを読み取っています…`;await inspectSmartImportFiles(files);});
    document.querySelectorAll('[data-trash-restore]').forEach(button=>button.addEventListener('click',async()=>{const count=await restoreTrashRecord(button.dataset.trashRestore);showToast(count>1?`宿題と提出記録${count-1}件を復元しました`:'記録を復元しました');renderDataExchange(inSettings);}));
    document.querySelectorAll('[data-pre-sync-restore]').forEach(button=>button.addEventListener('click',()=>restorePreSyncSnapshot(button.dataset.preSyncRestore,inSettings)));
    document.getElementById('app-update-check').addEventListener('click',async()=>{const registration=await navigator.serviceWorker?.getRegistration();await registration?.update();if('caches'in window)for(const key of await caches.keys())if(key!==`class-support-shell-v${APP_VERSION}`)await caches.delete(key);location.reload();});
    document.getElementById('delete-current-class').addEventListener('click',confirmDeleteCurrentClass);
    document.getElementById('delete-class-records').addEventListener('click',confirmDeleteClassRecords);
    document.getElementById('delete-all-data').addEventListener('click',confirmDeleteAllData);
  }

  function renderDataSettings(){renderDataExchange(true);}

  async function openDataManagement(){state.settingsTab='data';await renderSettings();await renderDataExchange(true);}

