"use strict";
const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.resolve(__dirname,"..");
const app=fs.readFileSync(path.join(root,"app.js"),"utf8");
const core=fs.readFileSync(path.join(root,"app-core.js"),"utf8");
const records=fs.readFileSync(path.join(root,"app-settings-records.js"),"utf8");
const security=fs.readFileSync(path.join(root,"app-settings-security.js"),"utf8");
assert.match(app,/event\.target\.closest\('form'\)/);
assert.doesNotMatch(app,/document\.addEventListener\('submit',event=>\{clearFormDraft/);
assert.match(core,/function completeFormDraft\(form\)\{/);
assert.match(core,/const target=form\|\|document\.activeElement\?\.closest\?\.\('form'\)\|\|\[\.\.\.document\.querySelectorAll\('form'\)\]/);
assert.match(core,/if\(hasUnsavedDraft\(\)&&!window\.confirm/);
assert.match(core,/function requestDialogClose\(\)/);
assert.match(core,/dialog\.addEventListener\('cancel',event=>\{event\.preventDefault\(\);requestDialogClose\(\);\}\)/);
assert.match(core,/function closeDialog\(options=\{\}\)\{const form=dialog\.querySelector\('form'\);if\(form&&!options\.keepDraft\)clearFormDraft\(form\);/);
assert.equal((records.match(/const form=event\.currentTarget/g)||[]).length,3);
assert.match(security,/const form=event\.currentTarget/);
assert.doesNotMatch(records,/completeFormDraft\(event\.currentTarget\)/);
assert.doesNotMatch(security,/completeFormDraft\(event\.currentTarget\)/);
console.log("draft-protection-regression: passed");
